// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/kezaeiv/clssc/wps/grenade2.mdl
models/kezaeiv/clssc/wps/p_2uzis.mdl
models/kezaeiv/clssc/wps/p_2uzis_gold.mdl
models/kezaeiv/clssc/wps/p_gauss.mdl
models/kezaeiv/clssc/wps/p_minigunidle.mdl
models/kezaeiv/clssc/wps/p_minigunspin.mdl
models/kezaeiv/clssc/wps/p_shock.mdl
models/kezaeiv/clssc/wps/p_uzi.mdl
models/kezaeiv/clssc/wps/p_uzi_gold.mdl
models/kezaeiv/clssc/wps/saw_shell.mdl
models/kezaeiv/clssc/wps/shell_357.mdl
models/kezaeiv/clssc/wps/shell_762.mdl
models/kezaeiv/clssc/wps/v_bgrap.mdl
models/kezaeiv/clssc/wps/v_crowbar.mdl
models/kezaeiv/clssc/wps/v_desert_eagle.mdl
models/kezaeiv/clssc/wps/v_gauss2.mdl
models/kezaeiv/clssc/wps/v_grenade.mdl
models/kezaeiv/clssc/wps/v_medkit.mdl
models/kezaeiv/clssc/wps/v_minigun.mdl
models/kezaeiv/clssc/wps/v_pipe_wrench.mdl
models/kezaeiv/clssc/wps/v_satchel.mdl
models/kezaeiv/clssc/wps/v_shock.mdl
models/kezaeiv/clssc/wps/v_squeak.mdl
models/kezaeiv/clssc/wps/v_tripmine.mdl
models/kezaeiv/clssc/wps/v_uzi.mdl
models/kezaeiv/clssc/wps/w_2uzis.mdl
models/kezaeiv/clssc/wps/w_2uzis_gold.mdl
models/kezaeiv/clssc/wps/w_gauss.mdl
models/kezaeiv/clssc/wps/w_grenade2.mdl
models/kezaeiv/clssc/wps/w_minigun.mdl
models/kezaeiv/clssc/wps/w_satchel2.mdl
models/kezaeiv/clssc/wps/w_shock.mdl
models/kezaeiv/clssc/wps/w_shock_rifle.mdl
models/kezaeiv/clssc/wps/w_tripmine2.mdl
models/kezaeiv/clssc/wps/w_uzi.mdl
models/kezaeiv/clssc/wps/w_uzi_clip.mdl
models/kezaeiv/clssc/wps/w_uzi_gold.mdl
models/kezaeiv/custom_weapons/ammo/anthrax.mdl
models/kezaeiv/custom_weapons/ammo/arrows2.mdl
models/kezaeiv/custom_weapons/ammo/bullets.mdl
models/kezaeiv/custom_weapons/ammo/darkmatter.mdl
models/kezaeiv/custom_weapons/ammo/erholungszelle.mdl
models/kezaeiv/custom_weapons/ammo/freedomclip.mdl
models/kezaeiv/custom_weapons/ammo/iron_shells_box.mdl
models/kezaeiv/custom_weapons/ammo/nails.mdl
models/kezaeiv/custom_weapons/ammo/plasma2.mdl
models/kezaeiv/custom_weapons/ammo/rockets.mdl
models/kezaeiv/custom_weapons/ammo/sniper.mdl
models/kezaeiv/custom_weapons/amr/p_amr.mdl
models/kezaeiv/custom_weapons/amr/v_amr.mdl
models/kezaeiv/custom_weapons/amr/w_amr.mdl
models/kezaeiv/custom_weapons/anvil/iron_shell.mdl
models/kezaeiv/custom_weapons/anvil/p_anvil.mdl
models/kezaeiv/custom_weapons/anvil/v_anvil2.mdl
models/kezaeiv/custom_weapons/anvil/w_anvil.mdl
models/kezaeiv/custom_weapons/balista/p_balista.mdl
models/kezaeiv/custom_weapons/balista/titanium_bolt.mdl
models/kezaeiv/custom_weapons/balista/v_balista.mdl
models/kezaeiv/custom_weapons/balista/w_balista.mdl
models/kezaeiv/custom_weapons/commando/p_commando.mdl
models/kezaeiv/custom_weapons/commando/v_commando.mdl
models/kezaeiv/custom_weapons/commando/w_commando.mdl
models/kezaeiv/custom_weapons/dev/p_devastator.mdl
models/kezaeiv/custom_weapons/dev/v_devastator.mdl
models/kezaeiv/custom_weapons/dev/w_devastator.mdl
models/kezaeiv/custom_weapons/dstinger/crimson_nail.mdl
models/kezaeiv/custom_weapons/dstinger/p_dstinger.mdl
models/kezaeiv/custom_weapons/dstinger/tiberium_nail.mdl
models/kezaeiv/custom_weapons/dstinger/toxic_nail.mdl
models/kezaeiv/custom_weapons/dstinger/v_dstinger.mdl
models/kezaeiv/custom_weapons/dstinger/w_dstinger.mdl
models/kezaeiv/custom_weapons/ehve/p_ehve.mdl
models/kezaeiv/custom_weapons/ehve/v_ehve.mdl
models/kezaeiv/custom_weapons/ehve/w_ehve.mdl
models/kezaeiv/custom_weapons/freedom/1812.mdl
models/kezaeiv/custom_weapons/freedom/p_freedom.mdl
models/kezaeiv/custom_weapons/freedom/v_freedom.mdl
models/kezaeiv/custom_weapons/freedom/w_freedom.mdl
models/kezaeiv/custom_weapons/frostbite/frost_nade.mdl
models/kezaeiv/custom_weapons/frostbite/frost_nail.mdl
models/kezaeiv/custom_weapons/frostbite/p_frostbite.mdl
models/kezaeiv/custom_weapons/frostbite/v_frostbite.mdl
models/kezaeiv/custom_weapons/frostbite/w_frostbite.mdl
models/kezaeiv/custom_weapons/hyper_blaster/missile.mdl
models/kezaeiv/custom_weapons/hyper_blaster/p_hblaster2.mdl
models/kezaeiv/custom_weapons/hyper_blaster/v_hblaster2.mdl
models/kezaeiv/custom_weapons/hyper_blaster/w_hblaster2.mdl
models/kezaeiv/custom_weapons/mprl/p_mprl.mdl
models/kezaeiv/custom_weapons/mprl/v_mprl.mdl
models/kezaeiv/custom_weapons/mprl/w_mprl.mdl
models/kezaeiv/custom_weapons/obsidian/p_obsidian.mdl
models/kezaeiv/custom_weapons/obsidian/plasma_nade.mdl
models/kezaeiv/custom_weapons/obsidian/v_obsidian.mdl
models/kezaeiv/custom_weapons/obsidian/w_obsidian.mdl
models/kezaeiv/custom_weapons/partner/p_kez_partner.mdl
models/kezaeiv/custom_weapons/partner/v_kez_partner.mdl
models/kezaeiv/custom_weapons/partner/w_kez_partner.mdl
models/kezaeiv/custom_weapons/plasma_slayer/p_slayer.mdl
models/kezaeiv/custom_weapons/plasma_slayer/v_slayer.mdl
models/kezaeiv/custom_weapons/plasma_slayer/w_slayer.mdl
models/kezaeiv/custom_weapons/prodigy/p_prodigy.mdl
models/kezaeiv/custom_weapons/prodigy/prodigy_plant.mdl
models/kezaeiv/custom_weapons/prodigy/prodigy_spore.mdl
models/kezaeiv/custom_weapons/prodigy/v_prodigy.mdl
models/kezaeiv/custom_weapons/prodigy/w_prodigy.mdl
models/kezaeiv/custom_weapons/purifier/v2/p_purifier.mdl
models/kezaeiv/custom_weapons/purifier/v2/v_purifier.mdl
models/kezaeiv/custom_weapons/purifier/v2/w_purifier.mdl
models/kezaeiv/custom_weapons/raptor/p_raptor2.mdl
models/kezaeiv/custom_weapons/raptor/v_raptor2.mdl
models/kezaeiv/custom_weapons/raptor/w_raptor2.mdl
models/kezaeiv/custom_weapons/seeker/p_seeker2.mdl
models/kezaeiv/custom_weapons/seeker/v_seeker2.mdl
models/kezaeiv/custom_weapons/seeker/w_seeker2.mdl
models/kezaeiv/custom_weapons/shredder/p_shredder2.mdl
models/kezaeiv/custom_weapons/shredder/v_shredder2.mdl
models/kezaeiv/custom_weapons/shredder/w_shredder2.mdl
models/kezaeiv/custom_weapons/surv/p_survivor2.mdl
models/kezaeiv/custom_weapons/surv/v_survivor2.mdl
models/kezaeiv/custom_weapons/surv/w_survivor2.mdl
models/kezaeiv/icons/mk_logo_blue.mdl
models/kezaeiv/icons/mk_logo_crimson.mdl
models/kezaeiv/kz_npcs/snglrt2/adriano_shadow.mdl
models/kezaeiv/kz_npcs/snglrt2/agrunt.mdl
models/kezaeiv/kz_npcs/snglrt2/agruntf.mdl
models/kezaeiv/kz_npcs/snglrt2/apache.mdl
models/kezaeiv/kz_npcs/snglrt2/apachef.mdl
models/kezaeiv/kz_npcs/snglrt2/baby_voltigore.mdl
models/kezaeiv/kz_npcs/snglrt2/babygarg.mdl
models/kezaeiv/kz_npcs/snglrt2/babygargf.mdl
models/kezaeiv/kz_npcs/snglrt2/barnabushev.mdl
models/kezaeiv/kz_npcs/snglrt2/barneyhev.mdl
models/kezaeiv/kz_npcs/snglrt2/bgman.mdl
models/kezaeiv/kz_npcs/snglrt2/bullsquid.mdl
models/kezaeiv/kz_npcs/snglrt2/chubby.mdl
models/kezaeiv/kz_npcs/snglrt2/chumtoad.mdl
models/kezaeiv/kz_npcs/snglrt2/controller_master.mdl
models/kezaeiv/kz_npcs/snglrt2/gonome.mdl
models/kezaeiv/kz_npcs/snglrt2/gonome_devourer.mdl
models/kezaeiv/kz_npcs/snglrt2/hassassin.mdl
models/kezaeiv/kz_npcs/snglrt2/hassassinf.mdl
models/kezaeiv/kz_npcs/snglrt2/headcrab.mdl
models/kezaeiv/kz_npcs/snglrt2/hgrunt_grn_demoman.mdl
models/kezaeiv/kz_npcs/snglrt2/hgrunt_medicf.mdl
models/kezaeiv/kz_npcs/snglrt2/hgrunt_opforf.mdl
models/kezaeiv/kz_npcs/snglrt2/hgrunt_red_leader.mdl
models/kezaeiv/kz_npcs/snglrt2/hgrunt_torchf.mdl
models/kezaeiv/kz_npcs/snglrt2/hgrunt_yllw_mp5.mdl
models/kezaeiv/kz_npcs/snglrt2/hgruntf.mdl
models/kezaeiv/kz_npcs/snglrt2/houndeye_green.mdl
models/kezaeiv/kz_npcs/snglrt2/hwgrunt.mdl
models/kezaeiv/kz_npcs/snglrt2/hwgruntf.mdl
models/kezaeiv/kz_npcs/snglrt2/islave_aggressive.mdl
models/kezaeiv/kz_npcs/snglrt2/islave_v2.mdl
models/kezaeiv/kz_npcs/snglrt2/islavef.mdl
models/kezaeiv/kz_npcs/snglrt2/islaveslap.mdl
models/kezaeiv/kz_npcs/snglrt2/kingpin.mdl
models/kezaeiv/kz_npcs/snglrt2/massn_ghost2.mdl
models/kezaeiv/kz_npcs/snglrt2/massn_kamikaze.mdl
models/kezaeiv/kz_npcs/snglrt2/massn_tactical.mdl
models/kezaeiv/kz_npcs/snglrt2/massnf.mdl
models/kezaeiv/kz_npcs/snglrt2/osprey.mdl
models/kezaeiv/kz_npcs/snglrt2/ospreyf.mdl
models/kezaeiv/kz_npcs/snglrt2/pit_drone_spike2.mdl
models/kezaeiv/kz_npcs/snglrt2/pit_red_predator.mdl
models/kezaeiv/kz_npcs/snglrt2/robo_blck_dstryr.mdl
models/kezaeiv/kz_npcs/snglrt2/robo_grunt.mdl
models/kezaeiv/kz_npcs/snglrt2/robo_purple.mdl
models/kezaeiv/kz_npcs/snglrt2/robo_red_leader_v2.mdl
models/kezaeiv/kz_npcs/snglrt2/sentry_red.mdl
models/kezaeiv/kz_npcs/snglrt2/strooper_blu_prodigy.mdl
models/kezaeiv/kz_npcs/snglrt2/strooper_red_violent.mdl
models/kezaeiv/kz_npcs/snglrt2/strooper_vio_suppresor.mdl
models/kezaeiv/kz_npcs/snglrt2/tor.mdl
models/kezaeiv/kz_npcs/snglrt2/torf.mdl
models/kezaeiv/kz_npcs/snglrt2/voltigore.mdl
models/kezaeiv/kz_npcs/snglrt2/young_adriano_estefano.mdl
models/kezaeiv/kz_npcs/snglrt2/zombie.mdl
models/kezaeiv/kz_npcs/snglrt2/zombie_barney.mdl
models/kezaeiv/kz_npcs/snglrt2/zombie_soldier.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
sound/kezaeiv/c_wep/ammo/arrows.wav
sound/kezaeiv/c_wep/ammo/bullets.wav
sound/kezaeiv/c_wep/ammo/darkmatter.wav
sound/kezaeiv/c_wep/ammo/energy.wav
sound/kezaeiv/c_wep/ammo/health.wav
sound/kezaeiv/c_wep/ammo/nails.wav
sound/kezaeiv/c_wep/ammo/pku_ammo1.wav
sound/kezaeiv/c_wep/ammo/pku_ammo2.wav
sound/kezaeiv/c_wep/ammo/plasma.wav
sound/kezaeiv/c_wep/ammo/rockets.wav
sound/kezaeiv/c_wep/ammo/shells.wav
sound/kezaeiv/c_wep/ammo/sniper.wav
sound/kezaeiv/c_wep/amr/igi_psgs1.wav
sound/kezaeiv/c_wep/amr/ss_snpr1.wav
sound/kezaeiv/c_wep/amr/ss_snpr2.wav
sound/kezaeiv/c_wep/amr/ss_snpr3.wav
sound/kezaeiv/c_wep/amr/wlf_stn1.wav
sound/kezaeiv/c_wep/anv/1shot.wav
sound/kezaeiv/c_wep/anv/2shots.wav
sound/kezaeiv/c_wep/anv/bigshot.wav
sound/kezaeiv/c_wep/bal/bal_sht3.wav
sound/kezaeiv/c_wep/bal/f_hit1.wav
sound/kezaeiv/c_wep/bal/f_hit2.wav
sound/kezaeiv/c_wep/com/cm_b1.wav
sound/kezaeiv/c_wep/com/cm_g1.wav
sound/kezaeiv/c_wep/com/cm_s1.wav
sound/kezaeiv/c_wep/de9/de_sh.wav
sound/kezaeiv/c_wep/destr/rail.wav
sound/kezaeiv/c_wep/dev/dev_crack.wav
sound/kezaeiv/c_wep/dev/dev_hit.wav
sound/kezaeiv/c_wep/dev/dev_meltdown.wav
sound/kezaeiv/c_wep/dev/dev_prism.wav
sound/kezaeiv/c_wep/dev/dev_rel2.wav
sound/kezaeiv/c_wep/dev/dev_rel3.wav
sound/kezaeiv/c_wep/dstngr/nail_hit_flesh.wav
sound/kezaeiv/c_wep/dstngr/nail_hit_wall.wav
sound/kezaeiv/c_wep/dstngr/spr_nail_hit.wav
sound/kezaeiv/c_wep/dstngr/sting01.wav
sound/kezaeiv/c_wep/dstngr/sting02.wav
sound/kezaeiv/c_wep/dstngr/sting03.wav
sound/kezaeiv/c_wep/dstngr/super_nail.wav
sound/kezaeiv/c_wep/dstngr/tibrifle.wav
sound/kezaeiv/c_wep/dstngr/tox_hlth01.wav
sound/kezaeiv/c_wep/ehve/lightning.wav
sound/kezaeiv/c_wep/ehve/plasmaball.wav
sound/kezaeiv/c_wep/ehve/roach_blast.wav
sound/kezaeiv/c_wep/ehve/volt1.wav
sound/kezaeiv/c_wep/ehve/volt2.wav
sound/kezaeiv/c_wep/ehve/volt3.wav
sound/kezaeiv/c_wep/frdm/1812.wav
sound/kezaeiv/c_wep/frdm/1812end.wav
sound/kezaeiv/c_wep/frdm/1812start.wav
sound/kezaeiv/c_wep/frdm/fire.wav
sound/kezaeiv/c_wep/frdm/rkt1.wav
sound/kezaeiv/c_wep/frdm/rotd.wav
sound/kezaeiv/c_wep/frdm/rotu.wav
sound/kezaeiv/c_wep/frdm/srs_boom.wav
sound/kezaeiv/c_wep/frdm/srs_cancel.wav
sound/kezaeiv/c_wep/frdm/srs_fire.wav
sound/kezaeiv/c_wep/frst/ghst1.wav
sound/kezaeiv/c_wep/frst/silenced.wav
sound/kezaeiv/c_wep/frst/snipe.wav
sound/kezaeiv/c_wep/frst/ss2_nade.wav
sound/kezaeiv/c_wep/hblst/hb_nova_hit.wav
sound/kezaeiv/c_wep/hblst/hb_plsm.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_blast.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_chrg.wav
sound/kezaeiv/c_wep/hblst/hb_plsm_nova_fly01.wav
sound/kezaeiv/c_wep/knf/k_flesh.wav
sound/kezaeiv/c_wep/knf/k_slash1.wav
sound/kezaeiv/c_wep/knf/k_slash2.wav
sound/kezaeiv/c_wep/knf/k_thrw.wav
sound/kezaeiv/c_wep/knf/slsh01.wav
sound/kezaeiv/c_wep/knf/slsh02.wav
sound/kezaeiv/c_wep/knf/slsh03.wav
sound/kezaeiv/c_wep/knf/slsh04.wav
sound/kezaeiv/c_wep/knf/vcut.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce1.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce2.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce3.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce4.wav
sound/kezaeiv/c_wep/misc/bounce/g_bounce5.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit1.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit2.wav
sound/kezaeiv/c_wep/misc/bounce/grenade_hit3.wav
sound/kezaeiv/c_wep/misc/enrg_hit.wav
sound/kezaeiv/c_wep/misc/exp1.wav
sound/kezaeiv/c_wep/misc/exp2.wav
sound/kezaeiv/c_wep/misc/exp3.wav
sound/kezaeiv/c_wep/misc/exp5.wav
sound/kezaeiv/c_wep/misc/item_respawn.wav
sound/kezaeiv/c_wep/misc/noammo.wav
sound/kezaeiv/c_wep/misc/quad.wav
sound/kezaeiv/c_wep/mprl/rkt_bounce.wav
sound/kezaeiv/c_wep/mprl/rkt_fly_1_4s.wav
sound/kezaeiv/c_wep/mprl/rkt_fly_3s.wav
sound/kezaeiv/c_wep/mprl/rkt_fly_7s.wav
sound/kezaeiv/c_wep/mprl/rkt_hit.wav
sound/kezaeiv/c_wep/mprl/rl_shoot.wav
sound/kezaeiv/c_wep/mprl/rl_shoot2.wav
sound/kezaeiv/c_wep/mprl/rl_shoot3.wav
sound/kezaeiv/c_wep/mprl/rl_shoot4.wav
sound/kezaeiv/c_wep/obs/burn1.wav
sound/kezaeiv/c_wep/obs/burn2.wav
sound/kezaeiv/c_wep/obs/flm1.wav
sound/kezaeiv/c_wep/obs/flm2.wav
sound/kezaeiv/c_wep/obs/obs_sg.wav
sound/kezaeiv/c_wep/obs/plsm_nade.wav
sound/kezaeiv/c_wep/par/lightning loop.wav
sound/kezaeiv/c_wep/par/p_rail2.wav
sound/kezaeiv/c_wep/purifier/lg_fire_loop.wav
sound/kezaeiv/c_wep/purifier/lg_fire_start.wav
sound/kezaeiv/c_wep/purifier/lg_hit1.wav
sound/kezaeiv/c_wep/purifier/lg_hit2.wav
sound/kezaeiv/c_wep/purifier/lg_hit3.wav
sound/kezaeiv/c_wep/rptr/r_focus_shot.wav
sound/kezaeiv/c_wep/rptr/r_shot.wav
sound/kezaeiv/c_wep/rptr/r_sp.wav
sound/kezaeiv/c_wep/rptr/r_zoom.wav
sound/kezaeiv/c_wep/shrd/shrdr_1.wav
sound/kezaeiv/c_wep/shrd/shrdr_2.wav
sound/kezaeiv/c_wep/shrd/shrdr_shotty.wav
sound/kezaeiv/c_wep/surv/pipe.wav
sound/kezaeiv/misc/cp_nod_reinf.mp3
sound/kezaeiv/misc/teleport.wav
sound/kezaeiv/music/forwerwar2.ogg
sound/kezaeiv/music/kc_trs/tenebrerossosangue01.ogg
sound/kezaeiv/music/kc_trs/tenebrerossosangue02.ogg
sound/kezaeiv/music/kc_trs/tenebrerossosangue03.ogg
sound/kezaeiv/music/run.ogg
sound/kezaeiv/music/runningmad.ogg
sound/kezaeiv/music/ushas.ogg
sound/kezaeiv/null.wav
sound/kezaeiv/singularity/npc/csgo_deag_shot.wav
sound/kezaeiv/singularity/npc/dusk_shotgun_shot.wav
sound/kezaeiv/singularity/npc/dusk_super_shotgun_shot.wav
sound/kezaeiv/singularity/npc/hgrunt_3shot.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit1.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit2.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit3.wav
sound/kezaeiv/singularity/npc/igi2_dragunov_shot.wav
sound/kezaeiv/singularity/npc/igi2_g36_shot.wav
sound/kezaeiv/singularity/npc/quake3_grenade_shot.wav
sound/kezaeiv/singularity/npc/quake4_plasma_shot.wav
sound/kezaeiv/singularity/npc/starcraft_ghost_rifle.wav
sound/kezaeiv/singularity/npc/tu_fire1.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/squeek/sqk_startled.wav
sound/squeek/sqk_strugglefit1.wav
sound/squeek/sqk_strugglefit2.wav
sound/squeek/sqk_strugglefit3.wav
sound/squeek/sqk_strugglenip1.wav
sound/squeek/sqk_strugglenip2.wav
sound/weapons/357_close.wav
sound/weapons/357_hammerpull.wav
sound/weapons/357_open.wav
sound/weapons/357_reload.wav
sound/weapons/357_shellin.wav
sound/weapons/357_shellsdrop.wav
sound/weapons/alien_draw.wav
sound/weapons/alien_holster.wav
sound/weapons/alien_shake.wav
sound/weapons/alien_sway.wav
sound/weapons/crossbow_bolt.wav
sound/weapons/crossbow_draw.wav
sound/weapons/crossbow_fidget.wav
sound/weapons/crossbow_maghold.wav
sound/weapons/crossbow_magin.wav
sound/weapons/crossbow_magout.wav
sound/weapons/crossbow_magready.wav
sound/weapons/crossbow_pull.wav
sound/weapons/deagle_clipin.wav
sound/weapons/deagle_clipout.wav
sound/weapons/deagle_movement.wav
sound/weapons/deagle_slide.wav
sound/weapons/deagle_slideback.wav
sound/weapons/deagle_sliderelease.wav
sound/weapons/egon_handle1.wav
sound/weapons/egon_handle2.wav
sound/weapons/fidget_2.wav
sound/weapons/fidget_3.wav
sound/weapons/fidget_4.wav
sound/weapons/fidget_6.wav
sound/weapons/gauss_fidget.wav
sound/weapons/glock_clipin.wav
sound/weapons/glock_clipout.wav
sound/weapons/glock_empty.wav
sound/weapons/glock_slideback.wav
sound/weapons/glock_slideforward.wav
sound/weapons/glock_sliderelease.wav
sound/weapons/grenade_pinpull.wav
sound/weapons/grenade_throw.wav
sound/weapons/hks_clic1.wav
sound/weapons/kz_scock_back.wav
sound/weapons/kz_scock_forward.wav
sound/weapons/m40a1_clipin.wav
sound/weapons/m40a1_clipout.wav
sound/weapons/m40a1_cliptap.wav
sound/weapons/m41a_load.wav
sound/weapons/M4_boltpull.wav
sound/weapons/M4_clipin.wav
sound/weapons/M4_clipmiddle.wav
sound/weapons/M4_clipout.wav
sound/weapons/M4_cliptap.wav
sound/weapons/medkit_click.wav
sound/weapons/medkit_closed.wav
sound/weapons/medkit_open.wav
sound/weapons/MP5_clipinsert1.wav
sound/weapons/MP5_cliprelease1.wav
sound/weapons/mp5_grenadelauncher_1.wav
sound/weapons/mp5_grenadelauncher_2.wav
sound/weapons/mp5_m203_grenade_drop.wav
sound/weapons/mp5_m203_grenade_insert.wav
sound/weapons/reload_done.wav
sound/weapons/RPG_fidget.wav
sound/weapons/rpg_getrocket.wav
sound/weapons/rpg_load.wav
sound/weapons/spas12_foley.wav
sound/weapons/spas_idle4.wav
sound/weapons/splauncher_draw.wav
sound/weapons/splauncher_idle.wav
sound/weapons/start_reload.wav
sound/weapons/uzi_akimbo_pull1.wav
sound/weapons/uzi_akimbo_pull2.wav
sound/weapons/uzi_boltback.wav
sound/weapons/uzi_clip_connect.wav
sound/weapons/uzi_deploy1.wav
sound/weapons/uzi_reload1.wav
sound/weapons/uzi_reload2.wav
sound/weapons/uzi_reload_left1.wav
sound/weapons/uzi_reload_left2.wav
sound/weapons/uzi_reload_right1.wav
sound/weapons/uzi_reload_right2.wav
sound/weapons/weapon_catch.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
sprites/kezaeiv/c_wep4/weapon_amr.txt
sprites/kezaeiv/c_wep4/weapon_anvil.txt
sprites/kezaeiv/c_wep4/weapon_balista.txt
sprites/kezaeiv/c_wep4/weapon_commando.txt
sprites/kezaeiv/c_wep4/weapon_devastator.txt
sprites/kezaeiv/c_wep4/weapon_duality_stinger.txt
sprites/kezaeiv/c_wep4/weapon_ehve.txt
sprites/kezaeiv/c_wep4/weapon_freedom_machine.txt
sprites/kezaeiv/c_wep4/weapon_frostbite.txt
sprites/kezaeiv/c_wep4/weapon_hyper_blaster.txt
sprites/kezaeiv/c_wep4/weapon_kez_partner.txt
sprites/kezaeiv/c_wep4/weapon_mprl.txt
sprites/kezaeiv/c_wep4/weapon_obsidian.txt
sprites/kezaeiv/c_wep4/weapon_plasma_slayer.txt
sprites/kezaeiv/c_wep4/weapon_prodigy_launcher.txt
sprites/kezaeiv/c_wep4/weapon_purifier.txt
sprites/kezaeiv/c_wep4/weapon_raptor_sniper.txt
sprites/kezaeiv/c_wep4/weapon_seeker.txt
sprites/kezaeiv/c_wep4/weapon_shredder.txt
sprites/kezaeiv/c_wep4/weapon_survivor.txt
sprites/kezaeiv/fx/b-tele_prpl_bl.spr
sprites/kezaeiv/fx/b-tele_prpl_pk.spr
sprites/kezaeiv/fx/hotglow_crimson.spr
sprites/kezaeiv/fx/hotglow_prpl.spr
sprites/kezaeiv/fx/kz_vcut_bl.spr
sprites/kezaeiv/fx/laser_crshr_cy.spr
sprites/kezaeiv/fx/laser_crshr_wht.spr
sprites/kezaeiv/kezammo_v2.spr
sprites/kezaeiv/kezcrosshairs.spr
sprites/kezaeiv/kezsniper2.spr
sprites/kezaeiv/kweps.spr
sprites/kezaeiv/kweps2.spr
sprites/kezaeiv/prtl/kz_exit1.spr
sprites/kezaeiv/xpl/pitdronespit_bl.spr
sprites/kezaeiv/xpl/spore_exp_01_bl.spr
sprites/kezaeiv/xpl/spore_exp_01_rd.spr
sprites/kezaeiv/xpl/spore_exp_c_01_bl.spr
sprites/kezaeiv/xpl/spore_exp_c_01_rd.spr
sprites/kezaeiv/xpl/zxlp_blue.spr
sprites/kezaeiv/xpl/zxlp_crimson.spr
sprites/kezaeiv/xpl/zxlp_lila.spr
sprites/kezaeiv/xpl/zxlp_purple.spr
sprites/kezaeiv/xpl/zxpl_green.spr
