// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/barney_civ.mdl
models/barney_decay.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/eye_scanner_broken.mdl
models/flare.mdl
models/flashlight.mdl
models/gorepile.mdl
models/obj_chair.mdl
models/scientist_bshift.mdl
models/scientist_op4.mdl
models/sink.mdl
models/zombie_construction.mdl
models/zombie_soldier2.mdl
models/zombie_soldier3.mdl
sound/agamemnon/ag_damn.wav
sound/agamemnon/ag_headroll.wav
sound/agamemnon/ag_meet0.wav
sound/agamemnon/ag_meet1.wav
sound/agamemnon/ag_meet2.wav
sound/agamemnon/ag_meet3.wav
sound/agamemnon/ag_meet4.wav
sound/agamemnon/ag_meet5.wav
sound/agamemnon/ag_meet6.wav
sound/agamemnon/ag_meet7.wav
sound/agamemnon/ag_paymess.wav
sound/agamemnon/ag_tv1_0testing.wav
sound/agamemnon/ag_tv1_1yesgood.wav
sound/agamemnon/ag_tv1_2anywhere.wav
sound/agamemnon/ag_tv4_0foundguard.wav
sound/agamemnon/ag_tv4_1codes.wav
sound/agamemnon/ag_tv4_2await.wav
sound/agamemnon/ag_tv5wrong.wav
sound/barney/ba_blocked.wav
sound/barney/ba_goodshoot.wav
sound/barney/ba_gundying.wav
sound/barney/ba_laugh01.wav
sound/barney/ba_laugh02.wav
sound/barney/ba_laugh03.wav
sound/barney/ba_longnite.wav
sound/barney/ba_movie.wav
sound/barney/ba_protect.wav
sound/barney/ba_safe1.wav
sound/barney/ba_shit.wav
sound/barney/ba_soldier.wav
sound/barney/ba_spawn.wav
sound/barney/goodteam.wav
sound/barney/mil_nevermakeit.wav
sound/barney/nocandoo.wav
sound/barney/otis_cantfigure.wav
sound/barney/otis_friends.wav
sound/barney/otis_hiya.wav
sound/barney/otis_janitor.wav
sound/barney/otis_mmmm.wav
sound/barney/otis_reputation.wav
sound/barney/otis_stupidmachines.wav
sound/barney/withoutme.wav
sound/env/amb_mechanical.wav
sound/env/amb_wind.wav
sound/env/amb_zombies.wav
sound/env/battle_loop1.wav
sound/env/battle_loop2.wav
sound/env/door_smack.wav
sound/env/fluorescent.wav
sound/env/generator_alarm.wav
sound/env/osprey_rotors.wav
sound/env/osprey_takeoff.wav
sound/env/splash_large.wav
sound/env/te_strike2.wav
sound/env/tunnel.wav
sound/env/tunnel2.wav
sound/env/xen_heart.wav
sound/gman/gman_again.wav
sound/gman/gman_belong.wav
sound/gman/gman_comebacknow.wav
sound/gman/gman_cutoff.wav
sound/gman/gman_getbackhere.wav
sound/gman/gman_huff.wav
sound/gman/gman_laugh01.wav
sound/gman/gman_meetagain.wav
sound/gman/gman_nicetohaveyou.wav
sound/gman/gman_notforlong.wav
sound/gman/gman_notthistime.wav
sound/gman/gman_ohno.wav
sound/gman/gman_oldtimes.wav
sound/gman/gman_payattention.wav
sound/gman/gman_prepare.wav
sound/gman/gman_ratherbusy.wav
sound/gman/gman_see.wav
sound/gman/gman_snarl01.wav
sound/gman/gman_snarl02.wav
sound/gman/gman_snarl03.wav
sound/gman/gman_thatsallfornow.wav
sound/gman/gman_thatwillbeall.wav
sound/gman/gman_wellsh.wav
sound/gman/gman_wellsh2.wav
sound/hgrunt/gr_snark.wav
sound/military/mgun1.wav
sound/military/mil_alienambush.wav
sound/military/mil_backuphere.wav
sound/military/mil_backupnorth.wav
sound/military/mil_casualties.wav
sound/military/mil_onturret.wav
sound/military/mil_retreat.wav
sound/military/tripwire.wav
sound/oghs/misc/cp02_03.mp3
sound/scientist/breakthings.wav
sound/scientist/d01_sci10_interesting.wav
sound/scientist/d01_sci14_right.wav
sound/scientist/drunk.wav
sound/scientist/fork_impossible.wav
sound/scientist/fork_phd.wav
sound/scientist/fork_theoretically.wav
sound/scientist/nil.wav
sound/scientist/sc_holdyourself.wav
sound/scientist/sc_please.wav
sound/scientist/snarkbody.wav
sound/scientist/thankgod.wav
sound/scientist/tramangry.wav
sound/scientist/tramcough.wav
sound/seer/nil_die.wav
sound/seer/nil_man_notman.wav
sound/singularity/misc/teleport.wav
sound/voxlines/vox_shutdown.wav
sprites/newfire3.spr
sprites/redglow.spr
sprites/singularity/prtl/kz_exit1.spr
sprites/spotlight.spr
