// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/5ton.mdl
models/barney_bshift.mdl
models/barney_civ.mdl
models/bradley.mdl
models/cactus01.mdl
models/cactus02.mdl
models/cactus03.mdl
models/combat_suv_anim.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/flare.mdl
models/flyer.mdl
models/flyer_gibs.mdl
models/gorepile.mdl
models/pcvvest.mdl
models/scientist_bshift.mdl
models/scientist_cleansuit.mdl
models/truck_research.mdl
models/zombie_barney2.mdl
sound/agamemnon/ag_damn.wav
sound/agamemnon/ag_headroll.wav
sound/agamemnon/ag_meet0.wav
sound/agamemnon/ag_meet1.wav
sound/agamemnon/ag_meet2.wav
sound/agamemnon/ag_meet3.wav
sound/agamemnon/ag_meet4.wav
sound/agamemnon/ag_meet5.wav
sound/agamemnon/ag_meet6.wav
sound/agamemnon/ag_meet7.wav
sound/agamemnon/ag_paymess.wav
sound/agamemnon/ag_tv1_0testing.wav
sound/agamemnon/ag_tv1_1yesgood.wav
sound/agamemnon/ag_tv1_2anywhere.wav
sound/agamemnon/ag_tv4_0foundguard.wav
sound/agamemnon/ag_tv4_1codes.wav
sound/agamemnon/ag_tv4_2await.wav
sound/agamemnon/ag_tv5wrong.wav
sound/barney/ba_blocked.wav
sound/barney/ba_goodshoot.wav
sound/barney/ba_gundying.wav
sound/barney/ba_laugh01.wav
sound/barney/ba_laugh02.wav
sound/barney/ba_laugh03.wav
sound/barney/ba_longnite.wav
sound/barney/ba_movie.wav
sound/barney/ba_protect.wav
sound/barney/ba_safe1.wav
sound/barney/ba_shit.wav
sound/barney/ba_soldier.wav
sound/barney/ba_spawn.wav
sound/barney/goodteam.wav
sound/barney/mil_nevermakeit.wav
sound/barney/nocandoo.wav
sound/barney/otis_cantfigure.wav
sound/barney/otis_friends.wav
sound/barney/otis_hiya.wav
sound/barney/otis_janitor.wav
sound/barney/otis_mmmm.wav
sound/barney/otis_reputation.wav
sound/barney/otis_stupidmachines.wav
sound/barney/withoutme.wav
sound/env/battle_loop1.wav
sound/env/battle_loop2.wav
sound/env/generator_alarm.wav
sound/env/jet_flyby_quick.wav
sound/env/mortar_background_01.wav
sound/env/osprey_rotors.wav
sound/env/te_strike1.wav
sound/env/te_strike2.wav
sound/env/vent.wav
sound/flyer/flyer_appear.wav
sound/flyer/flyer_die.wav
sound/flyer/flyer_idle.wav
sound/flyer/flyerbeam.wav
sound/flyer/ospreycrash.wav
sound/flyer/zapper_warmup2.wav
sound/gman/gman_again.wav
sound/gman/gman_belong.wav
sound/gman/gman_comebacknow.wav
sound/gman/gman_cutoff.wav
sound/gman/gman_getbackhere.wav
sound/gman/gman_huff.wav
sound/gman/gman_laugh01.wav
sound/gman/gman_meetagain.wav
sound/gman/gman_nicetohaveyou.wav
sound/gman/gman_notforlong.wav
sound/gman/gman_notthistime.wav
sound/gman/gman_ohno.wav
sound/gman/gman_oldtimes.wav
sound/gman/gman_payattention.wav
sound/gman/gman_prepare.wav
sound/gman/gman_ratherbusy.wav
sound/gman/gman_scare.wav
sound/gman/gman_see.wav
sound/gman/gman_snarl01.wav
sound/gman/gman_snarl02.wav
sound/gman/gman_snarl03.wav
sound/gman/gman_thatsallfornow.wav
sound/gman/gman_thatwillbeall.wav
sound/gman/gman_wellsh.wav
sound/gman/gman_wellsh2.wav
sound/military/exitdoorpanel.wav
sound/military/g3_copy.wav
sound/military/major_mortar.wav
sound/military/mil_hold.wav
sound/military/mil_rocket1.wav
sound/military/mil_suppress.wav
sound/military/mil_sweep.wav
sound/military/mil_tank1.wav
sound/military/mil_tank2.wav
sound/military/mil_tank3.wav
sound/military/mil_targetmortar.wav
sound/military/mortar_activate.wav
sound/military/ofmortar.wav
sound/military/osprey_shit.wav
sound/military/tankdrivein1.wav
sound/military/tankdrivein2.wav
sound/military/truck_stop.wav
sound/military/turretrot1.wav
sound/military/turretrot2.wav
sound/oghs/misc/cp02_03.mp3
sound/outtro/portal1.wav
sound/outtro/portal2.wav
sound/outtro/portal3.wav
sound/outtro/portal4.wav
sound/scientist/breakthings.wav
sound/scientist/d01_sci10_interesting.wav
sound/scientist/d01_sci14_right.wav
sound/scientist/drunk.wav
sound/scientist/fork_impossible.wav
sound/scientist/fork_phd.wav
sound/scientist/fork_theoretically.wav
sound/scientist/nil.wav
sound/scientist/sc_holdyourself.wav
sound/scientist/sc_please.wav
sound/scientist/thankgod.wav
sound/scientist/tramangry.wav
sound/scientist/tramcough.wav
sound/seer/nil_die.wav
sound/seer/nil_man_notman.wav
sound/seer/x_die1.wav
sound/singularity/misc/teleport.wav
sprites/newfire1.spr
sprites/newfire2.spr
sprites/newfire3.spr
sprites/redglow.spr
sprites/singularity/prtl/kz_exit1.spr
sprites/spotlight.spr
