// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/fi/EYE_SCANNER.mdl
models/fi/floater.mdl
models/fi/gamma.mdl
models/fi/houndeye_dead.mdl
models/fi/props/forklift.mdl
models/fi/sentry.mdl
models/fi/truck_research.mdl
models/fi/v_displacer.mdl
models/fi/w_cone.mdl
models/fi/worker.mdl
models/fi/zombie.mdl
models/fi/zombie01.mdl
models/fi/zombie02.mdl
models/fi/zombie03.mdl
models/fi/zombie04.mdl
models/fi/zombie_barney.mdl
models/fi/zombie_soldier.mdl
sound/fi/barney/ba_dooraccess.wav
sound/fi/barney/ba_gamma.wav
sound/fi/barney/ba_scanner.wav
sound/fi/barney/ba_whyyouhere.wav
sound/fi/barney/ba_youneedme.wav
sound/fi/fgrunt/fg_headevac.wav
sound/fi/fgrunt/fg_novfreeman.wav
sound/fi/fgrunt/fg_novhello.wav
sound/fi/fgrunt/fg_novnowaya.wav
sound/fi/fgrunt/fg_novnowayb.wav
sound/fi/fgrunt/fg_shephard1.wav
sound/fi/fgrunt/fg_shephard2.wav
sound/fi/fgrunt/fg_shephard3.wav
sound/fi/fgrunt/tg_power.wav
sound/fi/fgrunt/tg_stuck.wav
sound/fi/fgrunt/tg_zombies.wav
sound/fi/floater/floater_howl.wav
sound/fi/floater/floater_pain1.wav
sound/fi/floater/floater_pain2.wav
sound/fi/floater/floater_pain3.wav
sound/fi/floater/floater_spinup.wav
sound/fi/greg/gg_blowgates.wav
sound/fi/greg/gg_cantbelieve.wav
sound/fi/greg/gg_keepseye.wav
sound/fi/greg/gg_ohcrap.wav
sound/fi/hl2/eli_kleinerstop.wav
sound/fi/hl2/eli_whatgoingon.wav
sound/fi/hl2/kl_greatscott.wav
sound/fi/keller/dk_newstuff.wav
sound/fi/kevin/kv_accompany.wav
sound/fi/kevin/kv_antiair.wav
sound/fi/kevin/kv_barney.wav
sound/fi/kevin/kv_blackops.wav
sound/fi/kevin/kv_connect.wav
sound/fi/kevin/kv_contact.wav
sound/fi/kevin/kv_darkness.wav
sound/fi/kevin/kv_death.wav
sound/fi/kevin/kv_doorway.wav
sound/fi/kevin/kv_evac.wav
sound/fi/kevin/kv_freeman.wav
sound/fi/kevin/kv_hearme.wav
sound/fi/kevin/kv_hereiam.wav
sound/fi/kevin/kv_keys.wav
sound/fi/kevin/kv_limaisnear.wav
sound/fi/kevin/kv_lucky.wav
sound/fi/kevin/kv_mantarays.wav
sound/fi/kevin/kv_newobj.wav
sound/fi/kevin/kv_november.wav
sound/fi/kevin/kv_objectives.wav
sound/fi/kevin/kv_onthetrack.wav
sound/fi/kevin/kv_othersci.wav
sound/fi/kevin/kv_radio.wav
sound/fi/kevin/kv_return.wav
sound/fi/kevin/kv_reunite.wav
sound/fi/kevin/kv_rocket.wav
sound/fi/kevin/kv_rosenberg.wav
sound/fi/kevin/kv_satellite.wav
sound/fi/kevin/kv_sectore.wav
sound/fi/kevin/kv_setuptrap.wav
sound/fi/kevin/kv_squadalpha.wav
sound/fi/kevin/kv_theymad.wav
sound/fi/materials.txt
sound/fi/panthereye/pa_idle1.wav
sound/fi/panthereye/pa_idle2.wav
sound/fi/panthereye/pa_idle3.wav
sound/fi/panthereye/pa_idle4.wav
sound/fi/scientist/sc_biobye.wav
sound/fi/scientist/sc_biogamma.wav
sound/fi/scientist/sc_biogarg.wav
sound/fi/scientist/sc_biohello.wav
sound/fi/scientist/sc_bioletsgo.wav
sound/fi/scientist/sc_bioplan.wav
sound/fi/scientist/sc_biotest.wav
sound/fi/scientist/sc_biounlock.wav
sound/fi/scientist/sc_bothwork.wav
sound/fi/scientist/sc_commonenemy.wav
sound/fi/scientist/sc_dangerfire.wav
sound/fi/scientist/sc_dangergas.wav
sound/fi/scientist/sc_dangerrad.wav
sound/fi/scientist/sc_device.wav
sound/fi/scientist/sc_displacer.wav
sound/fi/scientist/sc_getround.wav
sound/fi/scientist/sc_goodluck.wav
sound/fi/scientist/sc_keepgoing.wav
sound/fi/scientist/sc_lockedgates.wav
sound/fi/scientist/sc_military.wav
sound/fi/scientist/sc_satellite.wav
sound/fi/scientist/sc_situation.wav
sound/fi/scientist/sc_woken.wav
sound/fi/scientist/sc_worry.wav
sound/fi/wheelchair/wheelchair_jog.wav
sound/fi/wheelchair/wheelchair_run.wav
sound/fi/wheelchair/wheelchair_walk.wav
sound/fi/worker/wr_leavealone.wav
sound/fi/worker/wr_surface.wav
sound/fi/worker/wr_swarmed.wav
sound/squeek/sqk_startled.wav
sound/squeek/sqk_strugglefit1.wav
sound/squeek/sqk_strugglefit2.wav
sound/squeek/sqk_strugglefit3.wav
sound/squeek/sqk_strugglenip1.wav
sound/squeek/sqk_strugglenip2.wav
sound/weapons/357_close.wav
sound/weapons/357_hammerpull.wav
sound/weapons/357_open.wav
sound/weapons/357_reload.wav
sound/weapons/357_shellin.wav
sound/weapons/357_shellsdrop.wav
sound/weapons/alien_holster.wav
sound/weapons/crossbow_bolt.wav
sound/weapons/crossbow_draw.wav
sound/weapons/crossbow_fidget.wav
sound/weapons/crossbow_maghold.wav
sound/weapons/crossbow_magin.wav
sound/weapons/crossbow_magout.wav
sound/weapons/crossbow_magready.wav
sound/weapons/crossbow_pull.wav
sound/weapons/deagle_clipin.wav
sound/weapons/deagle_clipout.wav
sound/weapons/deagle_movement.wav
sound/weapons/deagle_slide.wav
sound/weapons/deagle_slideback.wav
sound/weapons/deagle_sliderelease.wav
sound/weapons/egon_handle1.wav
sound/weapons/egon_handle2.wav
sound/weapons/fidget_2.wav
sound/weapons/fidget_3.wav
sound/weapons/fidget_4.wav
sound/weapons/fidget_6.wav
sound/weapons/gauss_fidget.wav
sound/weapons/glock_clipin.wav
sound/weapons/glock_clipout.wav
sound/weapons/glock_empty.wav
sound/weapons/glock_slideback.wav
sound/weapons/glock_slideforward.wav
sound/weapons/glock_sliderelease.wav
sound/weapons/grenade_pinpull.wav
sound/weapons/grenade_throw.wav
sound/weapons/hks_clic1.wav
sound/weapons/m40a1_clipin.wav
sound/weapons/m40a1_clipout.wav
sound/weapons/m40a1_cliptap.wav
sound/weapons/M4_boltpull.wav
sound/weapons/M4_clipin.wav
sound/weapons/M4_clipmiddle.wav
sound/weapons/M4_clipout.wav
sound/weapons/M4_cliptap.wav
sound/weapons/medkit_click.wav
sound/weapons/medkit_closed.wav
sound/weapons/medkit_open.wav
sound/weapons/MP5_clipinsert1.wav
sound/weapons/MP5_cliprelease1.wav
sound/weapons/mp5_grenadelauncher_1.wav
sound/weapons/mp5_grenadelauncher_2.wav
sound/weapons/mp5_m203_grenade_insert.wav
sound/weapons/radio_fire.wav
sound/weapons/reload_done.wav
sound/weapons/RPG_fidget.wav
sound/weapons/rpg_getrocket.wav
sound/weapons/rpg_load.wav
sound/weapons/scock_back.wav
sound/weapons/scock_forward.wav
sound/weapons/spas12_foley.wav
sound/weapons/spas_idle4.wav
sound/weapons/splauncher_draw.wav
sound/weapons/splauncher_idle.wav
sound/weapons/start_reload.wav
sound/weapons/uzi_akimbo_pull1.wav
sound/weapons/uzi_akimbo_pull2.wav
sound/weapons/uzi_boltback.wav
sound/weapons/uzi_clip_connect.wav
sound/weapons/uzi_deploy1.wav
sound/weapons/uzi_reload1.wav
sound/weapons/uzi_reload2.wav
sound/weapons/uzi_reload_left1.wav
sound/weapons/uzi_reload_left2.wav
sound/weapons/uzi_reload_right1.wav
sound/weapons/uzi_reload_right2.wav
sound/weapons/weapon_catch.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
sprites/fi/weapon_knife.spr
sprites/fi/weapon_knife.txt
