// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/fi/sentry.mdl
models/fi/suv.mdl
models/fi/suv_glass.mdl
models/fi/truck.mdl
models/fi/v_displacer.mdl
models/fi/zombie.mdl
models/fi/zombie01.mdl
models/fi/zombie02.mdl
models/fi/zombie03.mdl
models/fi/zombie04.mdl
models/fi/zombie_barney.mdl
models/fi/zombie_soldier.mdl
sound/fi/materials.txt
sound/fi/panthereye/pa_idle1.wav
sound/fi/panthereye/pa_idle2.wav
sound/fi/panthereye/pa_idle3.wav
sound/fi/panthereye/pa_idle4.wav
sound/fi/wheelchair/wheelchair_jog.wav
sound/fi/wheelchair/wheelchair_run.wav
sound/fi/wheelchair/wheelchair_walk.wav
sound/squeek/sqk_startled.wav
sound/squeek/sqk_strugglefit1.wav
sound/squeek/sqk_strugglefit2.wav
sound/squeek/sqk_strugglefit3.wav
sound/squeek/sqk_strugglenip1.wav
sound/squeek/sqk_strugglenip2.wav
sound/weapons/357_close.wav
sound/weapons/357_hammerpull.wav
sound/weapons/357_open.wav
sound/weapons/357_reload.wav
sound/weapons/357_shellin.wav
sound/weapons/357_shellsdrop.wav
sound/weapons/alien_holster.wav
sound/weapons/crossbow_bolt.wav
sound/weapons/crossbow_draw.wav
sound/weapons/crossbow_fidget.wav
sound/weapons/crossbow_maghold.wav
sound/weapons/crossbow_magin.wav
sound/weapons/crossbow_magout.wav
sound/weapons/crossbow_magready.wav
sound/weapons/crossbow_pull.wav
sound/weapons/deagle_clipin.wav
sound/weapons/deagle_clipout.wav
sound/weapons/deagle_movement.wav
sound/weapons/deagle_slide.wav
sound/weapons/deagle_slideback.wav
sound/weapons/deagle_sliderelease.wav
sound/weapons/egon_handle1.wav
sound/weapons/egon_handle2.wav
sound/weapons/fidget_2.wav
sound/weapons/fidget_3.wav
sound/weapons/fidget_4.wav
sound/weapons/fidget_6.wav
sound/weapons/gauss_fidget.wav
sound/weapons/glock_clipin.wav
sound/weapons/glock_clipout.wav
sound/weapons/glock_empty.wav
sound/weapons/glock_slideback.wav
sound/weapons/glock_slideforward.wav
sound/weapons/glock_sliderelease.wav
sound/weapons/grenade_pinpull.wav
sound/weapons/grenade_throw.wav
sound/weapons/hks_clic1.wav
sound/weapons/m40a1_clipin.wav
sound/weapons/m40a1_clipout.wav
sound/weapons/m40a1_cliptap.wav
sound/weapons/M4_boltpull.wav
sound/weapons/M4_clipin.wav
sound/weapons/M4_clipmiddle.wav
sound/weapons/M4_clipout.wav
sound/weapons/M4_cliptap.wav
sound/weapons/medkit_click.wav
sound/weapons/medkit_closed.wav
sound/weapons/medkit_open.wav
sound/weapons/MP5_clipinsert1.wav
sound/weapons/MP5_cliprelease1.wav
sound/weapons/mp5_grenadelauncher_1.wav
sound/weapons/mp5_grenadelauncher_2.wav
sound/weapons/mp5_m203_grenade_insert.wav
sound/weapons/radio_fire.wav
sound/weapons/reload_done.wav
sound/weapons/RPG_fidget.wav
sound/weapons/rpg_getrocket.wav
sound/weapons/rpg_load.wav
sound/weapons/scock_back.wav
sound/weapons/scock_forward.wav
sound/weapons/spas12_foley.wav
sound/weapons/spas_idle4.wav
sound/weapons/splauncher_draw.wav
sound/weapons/splauncher_idle.wav
sound/weapons/start_reload.wav
sound/weapons/uzi_akimbo_pull1.wav
sound/weapons/uzi_akimbo_pull2.wav
sound/weapons/uzi_boltback.wav
sound/weapons/uzi_clip_connect.wav
sound/weapons/uzi_deploy1.wav
sound/weapons/uzi_reload1.wav
sound/weapons/uzi_reload2.wav
sound/weapons/uzi_reload_left1.wav
sound/weapons/uzi_reload_left2.wav
sound/weapons/uzi_reload_right1.wav
sound/weapons/uzi_reload_right2.wav
sound/weapons/weapon_catch.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
