// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/babygarg/evoluted_skeleton.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/snd/osprey_crash.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/crimsoncommando/crimson01.mdl
models/st_allies/crimsoncommando/crimson02.mdl
models/st_allies/crimsoncommando/crimson03.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/dead_hev2t.mdl
models/st_allies/sobrobo_upgraded.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/crystal_red.mdl
models/st_mission1/props/mex_background_building_1_dest2.mdl
models/st_mission1/props/mex_ruined_house01.mdl
models/st_mission1/props/mex_ruined_house02.mdl
models/st_mission1/props/mex_ruined_house03.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/evoskeleton/evo_alert1.wav
sound/custom_monsters/evoskeleton/evo_alert2.wav
sound/custom_monsters/evoskeleton/evo_alert3.wav
sound/custom_monsters/evoskeleton/evo_attack1.wav
sound/custom_monsters/evoskeleton/evo_attack2.wav
sound/custom_monsters/evoskeleton/evo_attack3.wav
sound/custom_monsters/evoskeleton/evo_pain1.wav
sound/custom_monsters/evoskeleton/evo_pain2.wav
sound/custom_monsters/ghost/con_alert1.wav
sound/custom_monsters/ghost/con_alert2.wav
sound/custom_monsters/ghost/con_alert3.wav
sound/custom_monsters/ghost/con_attack1.wav
sound/custom_monsters/ghost/con_attack2.wav
sound/custom_monsters/ghost/con_attack3.wav
sound/custom_monsters/ghost/con_die1.wav
sound/custom_monsters/ghost/con_die2.wav
sound/custom_monsters/ghost/con_idle1.wav
sound/custom_monsters/ghost/con_idle2.wav
sound/custom_monsters/ghost/con_idle3.wav
sound/custom_monsters/ghost/con_idle4.wav
sound/custom_monsters/ghost/con_idle5.wav
sound/custom_monsters/ghost/con_pain1.wav
sound/custom_monsters/ghost/con_pain2.wav
sound/custom_monsters/ghost/con_pain3.wav
sound/custom_monsters/plagueskull/ps_float.wav
sound/custom_monsters/titanskull/tsm_flareball_attack.wav
sound/custom_monsters/titanskull/tsm_flareball_float.wav
sound/custom_monsters/titanskull/tsm_laugh.wav
sound/custom_monsters/titanskull/tsm_scream.wav
sound/custom_monsters/titanskull/tsm_summon.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_allies/darkwing/dw_c6_air.wav
sound/st_allies/sobrobo/sr_hs_c6_titan.wav
sound/st_mission/events/hs_c4/hs_c6_jetpackboost.wav
sound/st_mission/events/hs_c4/hs_c6_sobrobo_firing.wav
sound/st_mission/events/hs_c4/titanskull_warp.wav
sound/st_mission/events/hs_c4/warp_out.wav
sound/st_mission/hellambient.wav
sound/st_mission/music/hs_c6_bossfight.wav
sound/st_mission/teleport_out.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sprites/kezaeiv/prtl/kz_exit1.spr
