// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/mil_crategibs.mdl
9.wad
aomreal.wad
BigCity2.wad
cars.wad
cs_747.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
hs.wad
hs2.wad
hs3.wad
hs4.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/babygarg/evoluted_skeleton.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/nimblezombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/cyrex_upgraded.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor2.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/props/bigbluetruck.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/phone_pay-us.mdl
models/st_mission1/props/trash2.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
siege_apc.wad
sound/custom_monsters/evoskeleton/evo_alert1.ogg
sound/custom_monsters/evoskeleton/evo_alert2.ogg
sound/custom_monsters/evoskeleton/evo_alert3.ogg
sound/custom_monsters/evoskeleton/evo_attack1.ogg
sound/custom_monsters/evoskeleton/evo_attack2.ogg
sound/custom_monsters/evoskeleton/evo_attack3.ogg
sound/custom_monsters/evoskeleton/evo_pain1.ogg
sound/custom_monsters/evoskeleton/evo_pain2.ogg
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/guns/shotgun/sbarrel1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/smg/hks3.ogg
sound/custom_monsters/plagueskull/ps_float.ogg
sound/custom_monsters/slasherghost/sg_alert1.ogg
sound/custom_monsters/slasherghost/sg_alert2.ogg
sound/custom_monsters/slasherghost/sg_alert3.ogg
sound/custom_monsters/slasherghost/sg_miss1.ogg
sound/custom_monsters/slasherghost/sg_miss2.ogg
sound/custom_monsters/slasherghost/sg_pain1.ogg
sound/custom_monsters/slasherghost/sg_pain2.ogg
sound/custom_monsters/slasherghost/sg_slash1.ogg
sound/custom_monsters/slasherghost/sg_slash2.ogg
sound/custom_monsters/slasherghost/sg_slash3.ogg
sound/custom_monsters/slasherghost/sg_voice1.ogg
sound/custom_monsters/slasherghost/sg_voice2.ogg
sound/custom_monsters/slasherghost/sg_voice3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle2.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_mission/22noice2.ogg
sound/st_mission/airdrop.ogg
sound/st_mission/airdropjet1.ogg
sound/st_mission/events/hs_c4/distant_angel_shadows.ogg
sound/st_mission/events/hs_c4/distant_angel_shoot.ogg
sound/st_mission/events/hs_c4/distant_angel_warp.ogg
sound/st_mission/events/hs_c4/distant_demon_attack.ogg
sound/st_mission/events/hs_c4/distant_demon_dash.ogg
sound/st_mission/events/hs_c4/distant_displace.ogg
sound/st_mission/events/hs_c4/distant_explosion.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/music/ambience04.ogg
sound/st_mission/outdoorbattle.ogg
sound/st_mission/outdoorbattle_inside.ogg
sound/st_mission/rain1.ogg
sound/st_mission/rain_window.ogg
sound/st_mission/thunder1.ogg
sound/st_mission/thunder2.ogg
sound/st_mission/thunder3.ogg
sound/st_mission/thunder4.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m4a1-fire.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/wa2000_shoot1.ogg
sprites/singularity/prtl/kz_exit1.spr
