// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
aomreal.wad
bigcity2.wad
cs_747.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
gfx/env/arcssbk.tga
gfx/env/arcssdn.tga
gfx/env/arcssft.tga
gfx/env/arcsslf.tga
gfx/env/arcssrt.tga
gfx/env/arcssup.tga
hle.wad
hs.wad
hs2.wad
hs3.wad
hs5.wad
models/custom_monsters/agrunt/agrunt_snow.mdl
models/custom_monsters/alienslave/islave_snow.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/gonome/mutant_runner.mdl
models/custom_monsters/hgrunt/haunted_arctic_sgrunt.mdl
models/custom_monsters/hgrunt/haunted_crimson.mdl
models/custom_monsters/hgrunt/haunted_crimson2.mdl
models/custom_monsters/hgrunt/haunted_crimson3.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_helmet.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/pitdrone/frost_slasher.mdl
models/custom_monsters/tor/poss_rodney.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/twitcher.mdl
models/st_allies/arctic_sgrunt.mdl
models/st_allies/dead_hev.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/security_ar.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/poss_rodney_cutscene.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/wall_computer3.mdl
models/st_mission1/props/wall_computer4.mdl
models/st_mission1/props/wall_computer5.mdl
models/st_mission1/props/wall_computer8.mdl
models/st_mission1/scientist.mdl
models/st_mission1/snowcat.mdl
models/st_mission1/snowflake.mdl
models/st_mission1/truck_snow.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/crimson/v_357.mdl
models/st_mission1/weapons_classic/crimson/v_9mmar.mdl
models/st_mission1/weapons_classic/crimson/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/crimson/v_crossbow.mdl
models/st_mission1/weapons_classic/crimson/v_crowbar.mdl
models/st_mission1/weapons_classic/crimson/v_displacer.mdl
models/st_mission1/weapons_classic/crimson/v_eagle.mdl
models/st_mission1/weapons_classic/crimson/v_egon.mdl
models/st_mission1/weapons_classic/crimson/v_gauss.mdl
models/st_mission1/weapons_classic/crimson/v_grenade.mdl
models/st_mission1/weapons_classic/crimson/v_m16a2.mdl
models/st_mission1/weapons_classic/crimson/v_m40a1.mdl
models/st_mission1/weapons_classic/crimson/v_medkit.mdl
models/st_mission1/weapons_classic/crimson/v_minigun.mdl
models/st_mission1/weapons_classic/crimson/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/crimson/v_rpg.mdl
models/st_mission1/weapons_classic/crimson/v_satchel.mdl
models/st_mission1/weapons_classic/crimson/v_satchel_radio.mdl
models/st_mission1/weapons_classic/crimson/v_saw.mdl
models/st_mission1/weapons_classic/crimson/v_shotgun.mdl
models/st_mission1/weapons_classic/crimson/v_spore_launcher.mdl
models/st_mission1/weapons_classic/crimson/v_squeak.mdl
models/st_mission1/weapons_classic/crimson/v_tripmine.mdl
models/st_mission1/weapons_classic/crimson/v_uzi.mdl
models/st_mission1/weapons_classic/p_bgrap.mdl
models/st_mission1/weapons_classic/p_displacer.mdl
models/st_mission1/weapons_classic/v_bgrap.mdl
models/st_mission1/weapons_classic/w_bgrap.mdl
models/st_mission1/weapons_classic/w_displacer.mdl
models/st_mission1/weapons_classic/w_gauss.mdl
sound/custom_monsters/glitchzombie/claw_miss1.ogg
sound/custom_monsters/glitchzombie/claw_miss2.ogg
sound/custom_monsters/glitchzombie/claw_strike1.ogg
sound/custom_monsters/glitchzombie/claw_strike2.ogg
sound/custom_monsters/glitchzombie/claw_strike3.ogg
sound/custom_monsters/glitchzombie/zo_alert10.ogg
sound/custom_monsters/glitchzombie/zo_alert20.ogg
sound/custom_monsters/glitchzombie/zo_alert30.ogg
sound/custom_monsters/glitchzombie/zo_attack1.ogg
sound/custom_monsters/glitchzombie/zo_attack2.ogg
sound/custom_monsters/glitchzombie/zo_idle1.ogg
sound/custom_monsters/glitchzombie/zo_idle2.ogg
sound/custom_monsters/glitchzombie/zo_idle3.ogg
sound/custom_monsters/glitchzombie/zo_idle4.ogg
sound/custom_monsters/glitchzombie/zo_pain1.ogg
sound/custom_monsters/glitchzombie/zo_pain2.ogg
sound/custom_monsters/mercs/alert.ogg
sound/custom_monsters/mercs/area.ogg
sound/custom_monsters/mercs/ass.ogg
sound/custom_monsters/mercs/babysitting.ogg
sound/custom_monsters/mercs/backup.ogg
sound/custom_monsters/mercs/bfeeling.ogg
sound/custom_monsters/mercs/bogies.ogg
sound/custom_monsters/mercs/charge.ogg
sound/custom_monsters/mercs/check.ogg
sound/custom_monsters/mercs/checkrecon.ogg
sound/custom_monsters/mercs/chicken.ogg
sound/custom_monsters/mercs/clear.ogg
sound/custom_monsters/mercs/corners.ogg
sound/custom_monsters/mercs/cover.ogg
sound/custom_monsters/mercs/covering.ogg
sound/custom_monsters/mercs/coverup.ogg
sound/custom_monsters/mercs/critical.ogg
sound/custom_monsters/mercs/current.ogg
sound/custom_monsters/mercs/death1.ogg
sound/custom_monsters/mercs/death2.ogg
sound/custom_monsters/mercs/death3.ogg
sound/custom_monsters/mercs/disney.ogg
sound/custom_monsters/mercs/dogs.ogg
sound/custom_monsters/mercs/down.ogg
sound/custom_monsters/mercs/flank.ogg
sound/custom_monsters/mercs/freaks.ogg
sound/custom_monsters/mercs/fubar.ogg
sound/custom_monsters/mercs/getsome.ogg
sound/custom_monsters/mercs/go.ogg
sound/custom_monsters/mercs/gr_pain1.ogg
sound/custom_monsters/mercs/gr_pain2.ogg
sound/custom_monsters/mercs/gr_pain3.ogg
sound/custom_monsters/mercs/gr_pain4.ogg
sound/custom_monsters/mercs/grenade.ogg
sound/custom_monsters/mercs/hear.ogg
sound/custom_monsters/mercs/hearsome.ogg
sound/custom_monsters/mercs/hellosir.ogg
sound/custom_monsters/mercs/hostiles.ogg
sound/custom_monsters/mercs/incoming.ogg
sound/custom_monsters/mercs/lost.ogg
sound/custom_monsters/mercs/makeit.ogg
sound/custom_monsters/mercs/marines.ogg
sound/custom_monsters/mercs/mission.ogg
sound/custom_monsters/mercs/mister.ogg
sound/custom_monsters/mercs/move.ogg
sound/custom_monsters/mercs/moveup.ogg
sound/custom_monsters/mercs/no.ogg
sound/custom_monsters/mercs/nothing.ogg
sound/custom_monsters/mercs/now.ogg
sound/custom_monsters/mercs/outof.ogg
sound/custom_monsters/mercs/pain1.ogg
sound/custom_monsters/mercs/pain2.ogg
sound/custom_monsters/mercs/pain3.ogg
sound/custom_monsters/mercs/pain4.ogg
sound/custom_monsters/mercs/quiet.ogg
sound/custom_monsters/mercs/rapidfire.ogg
sound/custom_monsters/mercs/recon.ogg
sound/custom_monsters/mercs/roger.ogg
sound/custom_monsters/mercs/seensquad.ogg
sound/custom_monsters/mercs/short.ogg
sound/custom_monsters/mercs/sniper.ogg
sound/custom_monsters/mercs/suppressing.ogg
sound/custom_monsters/mercs/sweep.ogg
sound/custom_monsters/mercs/tag.ogg
sound/custom_monsters/mercs/take.ogg
sound/custom_monsters/mercs/wantsome.ogg
sound/custom_monsters/mercs/zone.ogg
sound/custom_monsters/mutantrunner/mr_alert2.ogg
sound/custom_monsters/mutantrunner/mr_alert3.ogg
sound/custom_monsters/mutantrunner/mr_attack.ogg
sound/custom_monsters/mutantrunner/mr_die1.ogg
sound/custom_monsters/mutantrunner/mr_die2.ogg
sound/custom_monsters/mutantrunner/mr_hit1.ogg
sound/custom_monsters/mutantrunner/mr_hit2.ogg
sound/custom_monsters/mutantrunner/mr_idle1.ogg
sound/custom_monsters/mutantrunner/mr_idle2.ogg
sound/custom_monsters/mutantrunner/mr_pain1.ogg
sound/custom_monsters/mutantrunner/mr_pain2.ogg
sound/custom_monsters/rodney/ro_alert1.ogg
sound/custom_monsters/rodney/ro_alert2.ogg
sound/custom_monsters/rodney/ro_attack1.ogg
sound/custom_monsters/rodney/ro_attack2.ogg
sound/custom_monsters/rodney/ro_d6_l.ogg
sound/custom_monsters/rodney/ro_d6_us.ogg
sound/custom_monsters/rodney/ro_pain.ogg
sound/custom_monsters/rodney/ro_summon.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/voidfold_cannon_charge.ogg
sound/hs/weapons/voidfold_cannon_charge2.ogg
sound/hs/weapons/voidfold_cannon_fire.ogg
sound/hs/weapons/voidfold_cannon_impact.ogg
sound/hs/weapons/voidfold_cannon_playertp.ogg
sound/hs/weapons/voidfold_cannon_selftp.ogg
sound/hs/weapons/voidfold_cannon_start.ogg
sound/hs/weapons/voidfold_cannon_teleport.ogg
sound/oghs/misc/cp02_03.mp3
sound/player/pl_asf4xx.ogg
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/alert.ogg
sound/st_allies/crimson_commando/area.ogg
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/backup.ogg
sound/st_allies/crimson_commando/bfeeling.ogg
sound/st_allies/crimson_commando/bogies.ogg
sound/st_allies/crimson_commando/charge.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/checkrecon.ogg
sound/st_allies/crimson_commando/chicken.ogg
sound/st_allies/crimson_commando/clear.ogg
sound/st_allies/crimson_commando/command.ogg
sound/st_allies/crimson_commando/corners.ogg
sound/st_allies/crimson_commando/corporal.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/cover.ogg
sound/st_allies/crimson_commando/covering.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/current.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/disney.ogg
sound/st_allies/crimson_commando/dogs.ogg
sound/st_allies/crimson_commando/down.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/freaks.ogg
sound/st_allies/crimson_commando/friendly.ogg
sound/st_allies/crimson_commando/fubar.ogg
sound/st_allies/crimson_commando/getsome.ogg
sound/st_allies/crimson_commando/go.ogg
sound/st_allies/crimson_commando/gotit.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/grenade.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hellout.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/incoming.ogg
sound/st_allies/crimson_commando/lost.ogg
sound/st_allies/crimson_commando/marines.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/move.ogg
sound/st_allies/crimson_commando/moveup.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/no.ogg
sound/st_allies/crimson_commando/notfail.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/outof.ogg
sound/st_allies/crimson_commando/pain1.ogg
sound/st_allies/crimson_commando/pain2.ogg
sound/st_allies/crimson_commando/pain3.ogg
sound/st_allies/crimson_commando/pain4.ogg
sound/st_allies/crimson_commando/quiet.ogg
sound/st_allies/crimson_commando/rapidfire.ogg
sound/st_allies/crimson_commando/recon.ogg
sound/st_allies/crimson_commando/right.ogg
sound/st_allies/crimson_commando/roger.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/seensquad.ogg
sound/st_allies/crimson_commando/short.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/suppressing.ogg
sound/st_allies/crimson_commando/sweep.ogg
sound/st_allies/crimson_commando/tag.ogg
sound/st_allies/crimson_commando/take.ogg
sound/st_allies/crimson_commando/talking.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/watchfire.ogg
sound/st_allies/crimson_commando/watchit.ogg
sound/st_allies/crimson_commando/yes.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_mission/airdropjet1.ogg
sound/st_mission/blizzard.ogg
sound/st_mission/bunkersiren.ogg
sound/st_mission/events/hs_c4/warp_in.ogg
sound/st_mission/events/hs_c4/warp_out.ogg
sound/st_mission/helicopter13.ogg
sound/st_mission/largebeamstart1.ogg
sound/st_mission/music/background/c/c3_amb_facility01.ogg
sound/st_mission/music/background/c/c3_amb_facility02.ogg
sound/st_mission/music/background/c/c3_amb_facility03.ogg
sound/st_mission/music/background/c/c3_amb_facility04.ogg
sound/st_mission/music/background/c/c3_amb_facility05.ogg
sound/st_mission/music/background/c/c3_amb_facility06.ogg
sound/st_mission/teleport_in.ogg
sound/st_mission/teleport_out.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_fire1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/xm8-fire.ogg
sprites/arctic_incident/ws_snow_fx.spr
sprites/singularity/prtl/kz_exit1.spr
