// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomdc22.wad
aomreal.wad
bigcity2.wad
cs_747.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
fi.wad
hle.wad
hs.wad
hs2.wad
models/custom_monsters/agrunt/agrunt_snow.mdl
models/custom_monsters/alienslave/islave_snow.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/bullsquid/snowsquid.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/headcrab/baby_panther.mdl
models/custom_monsters/headcrab/crabgiant.mdl
models/custom_monsters/pitdrone/frost_slasher.mdl
models/custom_monsters/stukabat/lostsoul.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/darkzombie.mdl
models/custom_monsters/zombie/kisbabu.mdl
models/custom_monsters/zombie/nursezombie.mdl
models/custom_monsters/zombie/shryk.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie_crowbar.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/custom_monsters/zombie/zombika.mdl
models/st_allies/angel_giant_form.mdl
models/st_allies/arctic_sgrunt.mdl
models/st_allies/civilian.mdl
models/st_allies/dead_hev.mdl
models/st_allies/nimblegrunt/ngrunt_medic.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/scientist.mdl
models/st_allies/security_ar.mdl
models/st_allies/wilkins.mdl
models/st_allies/zngrunt.mdl
models/st_mission1/billboard01.mdl
models/st_mission1/props/big_bucket.mdl
models/st_mission1/props/delta_duct_fans.mdl
models/st_mission1/props/es_3pipes_corner.mdl
models/st_mission1/props/es_3pipes_corner2.mdl
models/st_mission1/props/es_pipes_up3.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/papers_detail.mdl
models/st_mission1/props/pipe_resgen1.mdl
models/st_mission1/props/security_camera_c.mdl
models/st_mission1/props/snowbush.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/truck_old.mdl
models/st_mission1/props/wall_ele_shield_double.mdl
models/st_mission1/scientist.mdl
models/st_mission1/snowcat.mdl
models/st_mission1/snowflake.mdl
models/st_mission1/truck_snow.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/crimson/v_357.mdl
models/st_mission1/weapons_classic/crimson/v_9mmar.mdl
models/st_mission1/weapons_classic/crimson/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/crimson/v_crossbow.mdl
models/st_mission1/weapons_classic/crimson/v_crowbar.mdl
models/st_mission1/weapons_classic/crimson/v_displacer.mdl
models/st_mission1/weapons_classic/crimson/v_eagle.mdl
models/st_mission1/weapons_classic/crimson/v_egon.mdl
models/st_mission1/weapons_classic/crimson/v_gauss.mdl
models/st_mission1/weapons_classic/crimson/v_grenade.mdl
models/st_mission1/weapons_classic/crimson/v_m16a2.mdl
models/st_mission1/weapons_classic/crimson/v_m40a1.mdl
models/st_mission1/weapons_classic/crimson/v_medkit.mdl
models/st_mission1/weapons_classic/crimson/v_minigun.mdl
models/st_mission1/weapons_classic/crimson/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/crimson/v_rpg.mdl
models/st_mission1/weapons_classic/crimson/v_satchel.mdl
models/st_mission1/weapons_classic/crimson/v_satchel_radio.mdl
models/st_mission1/weapons_classic/crimson/v_saw.mdl
models/st_mission1/weapons_classic/crimson/v_shotgun.mdl
models/st_mission1/weapons_classic/crimson/v_spore_launcher.mdl
models/st_mission1/weapons_classic/crimson/v_squeak.mdl
models/st_mission1/weapons_classic/crimson/v_tripmine.mdl
models/st_mission1/weapons_classic/crimson/v_uzi.mdl
models/st_mission1/weapons_classic/p_bgrap.mdl
models/st_mission1/weapons_classic/p_displacer.mdl
models/st_mission1/weapons_classic/v_bgrap.mdl
models/st_mission1/weapons_classic/w_bgrap.mdl
models/st_mission1/weapons_classic/w_displacer.mdl
models/st_mission1/weapons_classic/w_gauss.mdl
models/st_mission1/weapons_classic/w_suit.mdl
sound/custom_monsters/baby_panther/bp_alert1.ogg
sound/custom_monsters/baby_panther/bp_alert2.ogg
sound/custom_monsters/baby_panther/bp_attack1.ogg
sound/custom_monsters/baby_panther/bp_attack2.ogg
sound/custom_monsters/baby_panther/bp_attack3.ogg
sound/custom_monsters/baby_panther/bp_die1.ogg
sound/custom_monsters/baby_panther/bp_die2.ogg
sound/custom_monsters/baby_panther/bp_headbite.ogg
sound/custom_monsters/baby_panther/bp_idle1.ogg
sound/custom_monsters/baby_panther/bp_idle2.ogg
sound/custom_monsters/baby_panther/bp_idle3.ogg
sound/custom_monsters/baby_panther/bp_idle4.ogg
sound/custom_monsters/baby_panther/bp_idle5.ogg
sound/custom_monsters/baby_panther/bp_pain1.ogg
sound/custom_monsters/baby_panther/bp_pain2.ogg
sound/custom_monsters/baby_panther/bp_pain3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/voidfold_cannon_charge.ogg
sound/hs/weapons/voidfold_cannon_charge2.ogg
sound/hs/weapons/voidfold_cannon_fire.ogg
sound/hs/weapons/voidfold_cannon_impact.ogg
sound/hs/weapons/voidfold_cannon_playertp.ogg
sound/hs/weapons/voidfold_cannon_selftp.ogg
sound/hs/weapons/voidfold_cannon_start.ogg
sound/hs/weapons/voidfold_cannon_teleport.ogg
sound/oghs/misc/cp02_03.mp3
sound/player/pl_wood_scr1.ogg
sound/player/pl_wood_scr2.ogg
sound/player/pl_wood_scr3.ogg
sound/player/pl_wood_scr4.ogg
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/hs_d1_facility.ogg
sound/st_allies/sobrobo/sr_hs_d1_general.ogg
sound/st_mission/broken_fan.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/events/hs_d/hs_d1_cutscene.ogg
sound/st_mission/music/hs_d1_amb.ogg
sound/st_mission/outdoorbattle.ogg
sound/st_mission/outdoorbattle_inside.ogg
sound/st_mission/scary_wind2.ogg
sound/st_mission/teleport_out.ogg
sound/st_mission/tunnel_wind1.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/arctic_incident/ws_snow_fx.spr
sprites/singularity/prtl/kz_exit1.spr
