// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cars.wad
cs_office.wad
hs.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/gonome/heavy_zombie.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/hgrunt/possesed_survivor.mdl
models/custom_monsters/shocktrooper/bloodlurker.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/lpzombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/slasher_ghost01.mdl
models/custom_monsters/zombie/slasher_ghost02.mdl
models/custom_monsters/zombie/slasher_ghostt.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/szombiet.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie3.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/custom_monsters/zombie/zombie_sven01.mdl
models/custom_monsters/zombie/zombie_sven02.mdl
models/custom_monsters/zombie/zombie_sven03.mdl
models/custom_monsters/zombie/zombie_svent.mdl
models/st_allies/civilian.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hevt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/trash1.mdl
models/st_mission1/props/trash3.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/slasherghost/sg_alert1.wav
sound/custom_monsters/slasherghost/sg_alert2.wav
sound/custom_monsters/slasherghost/sg_alert3.wav
sound/custom_monsters/slasherghost/sg_attack1.wav
sound/custom_monsters/slasherghost/sg_attack2.wav
sound/custom_monsters/slasherghost/sg_miss1.wav
sound/custom_monsters/slasherghost/sg_miss2.wav
sound/custom_monsters/slasherghost/sg_pain1.wav
sound/custom_monsters/slasherghost/sg_pain2.wav
sound/custom_monsters/slasherghost/sg_slash1.wav
sound/custom_monsters/slasherghost/sg_slash2.wav
sound/custom_monsters/slasherghost/sg_slash3.wav
sound/custom_monsters/slasherghost/sg_voice1.wav
sound/custom_monsters/slasherghost/sg_voice2.wav
sound/custom_monsters/slasherghost/sg_voice3.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_mission/music/darkambient.ogg
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sprites/kezaeiv/prtl/kz_exit1.spr
