// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
hs.wad
hs2.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/hgrunt/haunted_ngrunt.mdl
models/custom_monsters/hgrunt/haunted_ngrunt2.mdl
models/custom_monsters/hgrunt/haunted_ngrunt3.mdl
models/custom_monsters/hgrunt/haunted_ngrunt4.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_helmet.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_shotgun.mdl
models/custom_monsters/hgrunt/infected_sgrunt.mdl
models/custom_monsters/hgrunt/security_infected.mdl
models/custom_monsters/shocktrooper/bloodlurker.mdl
models/custom_monsters/tor/overlord_wizard.mdl
models/snd/osprey_blade.mdl
models/snd/osprey_crash.mdl
models/snd/osprey_rotor.mdl
models/snd/osprey_wheel.mdl
models/snd/osprey_wing.mdl
models/st_allies/brad.mdl
models/st_allies/crimsoncommando/crimson2.mdl
models/st_allies/crimsoncommando/crimson3.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/cyrex_armed.mdl
models/st_allies/darkwing.mdl
models/st_allies/huey_apache.mdl
models/st_allies/lowell.mdl
models/st_allies/miles.mdl
models/st_allies/plinky_armed.mdl
models/st_allies/sgrunt.mdl
models/st_allies/sobrobo_armed.mdl
models/st_mission1/crystal_green.mdl
models/st_mission1/props/cc_building3.mdl
models/st_mission1/props/tracking_device.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/guns/aomshotgun/sbarrel1.ogg
sound/custom_monsters/guns/g3/g3_fire.ogg
sound/custom_monsters/guns/m3/m3-1.ogg
sound/custom_monsters/guns/msg90/sniper_fire.ogg
sound/custom_monsters/guns/p90/p90-1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/taurus/tau_fire.ogg
sound/custom_monsters/overlordwizard/ow_alert1.ogg
sound/custom_monsters/overlordwizard/ow_alert2.ogg
sound/custom_monsters/overlordwizard/ow_attack1.ogg
sound/custom_monsters/overlordwizard/ow_attack2.ogg
sound/custom_monsters/overlordwizard/ow_die1.ogg
sound/custom_monsters/overlordwizard/ow_die2.ogg
sound/custom_monsters/overlordwizard/ow_idle1.ogg
sound/custom_monsters/overlordwizard/ow_idle2.ogg
sound/custom_monsters/overlordwizard/ow_idle3.ogg
sound/custom_monsters/overlordwizard/ow_impact.ogg
sound/custom_monsters/overlordwizard/ow_pain.ogg
sound/custom_monsters/overlordwizard/ow_summon.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/alert.ogg
sound/st_allies/crimson_commando/area.ogg
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/backup.ogg
sound/st_allies/crimson_commando/bfeeling.ogg
sound/st_allies/crimson_commando/bogies.ogg
sound/st_allies/crimson_commando/charge.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/checkrecon.ogg
sound/st_allies/crimson_commando/chicken.ogg
sound/st_allies/crimson_commando/clear.ogg
sound/st_allies/crimson_commando/command.ogg
sound/st_allies/crimson_commando/corners.ogg
sound/st_allies/crimson_commando/corporal.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/cover.ogg
sound/st_allies/crimson_commando/covering.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/current.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/disney.ogg
sound/st_allies/crimson_commando/dogs.ogg
sound/st_allies/crimson_commando/down.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/freaks.ogg
sound/st_allies/crimson_commando/friendly.ogg
sound/st_allies/crimson_commando/fubar.ogg
sound/st_allies/crimson_commando/getsome.ogg
sound/st_allies/crimson_commando/go.ogg
sound/st_allies/crimson_commando/gotit.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/grenade.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hellout.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/incoming.ogg
sound/st_allies/crimson_commando/lost.ogg
sound/st_allies/crimson_commando/marines.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/move.ogg
sound/st_allies/crimson_commando/moveup.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/no.ogg
sound/st_allies/crimson_commando/notfail.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/outof.ogg
sound/st_allies/crimson_commando/pain1.ogg
sound/st_allies/crimson_commando/pain2.ogg
sound/st_allies/crimson_commando/pain3.ogg
sound/st_allies/crimson_commando/pain4.ogg
sound/st_allies/crimson_commando/quiet.ogg
sound/st_allies/crimson_commando/rapidfire.ogg
sound/st_allies/crimson_commando/recon.ogg
sound/st_allies/crimson_commando/right.ogg
sound/st_allies/crimson_commando/roger.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/seensquad.ogg
sound/st_allies/crimson_commando/short.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/suppressing.ogg
sound/st_allies/crimson_commando/sweep.ogg
sound/st_allies/crimson_commando/tag.ogg
sound/st_allies/crimson_commando/take.ogg
sound/st_allies/crimson_commando/talking.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/watchfire.ogg
sound/st_allies/crimson_commando/watchit.ogg
sound/st_allies/crimson_commando/yes.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/darkwing/alert0.ogg
sound/st_allies/darkwing/alert1.ogg
sound/st_allies/darkwing/alert2.ogg
sound/st_allies/darkwing/alert3.ogg
sound/st_allies/darkwing/answer0.ogg
sound/st_allies/darkwing/answer1.ogg
sound/st_allies/darkwing/answer2.ogg
sound/st_allies/darkwing/charge0.ogg
sound/st_allies/darkwing/charge1.ogg
sound/st_allies/darkwing/charge2.ogg
sound/st_allies/darkwing/check0.ogg
sound/st_allies/darkwing/check1.ogg
sound/st_allies/darkwing/clear0.ogg
sound/st_allies/darkwing/clear1.ogg
sound/st_allies/darkwing/cover0.ogg
sound/st_allies/darkwing/cover1.ogg
sound/st_allies/darkwing/cover2.ogg
sound/st_allies/darkwing/death1.ogg
sound/st_allies/darkwing/death2.ogg
sound/st_allies/darkwing/death3.ogg
sound/st_allies/darkwing/dw_b10_hit.ogg
sound/st_allies/darkwing/dw_b10_idk.ogg
sound/st_allies/darkwing/dw_b10_scream.ogg
sound/st_allies/darkwing/gren0.ogg
sound/st_allies/darkwing/gren1.ogg
sound/st_allies/darkwing/hello0.ogg
sound/st_allies/darkwing/hello1.ogg
sound/st_allies/darkwing/hello2.ogg
sound/st_allies/darkwing/idle0.ogg
sound/st_allies/darkwing/idle1.ogg
sound/st_allies/darkwing/idle10.ogg
sound/st_allies/darkwing/idle11.ogg
sound/st_allies/darkwing/idle12.ogg
sound/st_allies/darkwing/idle2.ogg
sound/st_allies/darkwing/idle3.ogg
sound/st_allies/darkwing/idle4.ogg
sound/st_allies/darkwing/idle5.ogg
sound/st_allies/darkwing/idle6.ogg
sound/st_allies/darkwing/idle7.ogg
sound/st_allies/darkwing/idle8.ogg
sound/st_allies/darkwing/idle9.ogg
sound/st_allies/darkwing/kill0.ogg
sound/st_allies/darkwing/kill1.ogg
sound/st_allies/darkwing/kill2.ogg
sound/st_allies/darkwing/kill3.ogg
sound/st_allies/darkwing/kill4.ogg
sound/st_allies/darkwing/kill5.ogg
sound/st_allies/darkwing/kill6.ogg
sound/st_allies/darkwing/kill7.ogg
sound/st_allies/darkwing/kill8.ogg
sound/st_allies/darkwing/kill9.ogg
sound/st_allies/darkwing/mad0.ogg
sound/st_allies/darkwing/mad1.ogg
sound/st_allies/darkwing/monster0.ogg
sound/st_allies/darkwing/monster1.ogg
sound/st_allies/darkwing/mortal0.ogg
sound/st_allies/darkwing/mortal1.ogg
sound/st_allies/darkwing/mortal2.ogg
sound/st_allies/darkwing/ok0.ogg
sound/st_allies/darkwing/ok1.ogg
sound/st_allies/darkwing/ok2.ogg
sound/st_allies/darkwing/ok3.ogg
sound/st_allies/darkwing/ok4.ogg
sound/st_allies/darkwing/ok5.ogg
sound/st_allies/darkwing/ok6.ogg
sound/st_allies/darkwing/ok7.ogg
sound/st_allies/darkwing/ok8.ogg
sound/st_allies/darkwing/ok9.ogg
sound/st_allies/darkwing/pain1.ogg
sound/st_allies/darkwing/pain2.ogg
sound/st_allies/darkwing/pain3.ogg
sound/st_allies/darkwing/pain4.ogg
sound/st_allies/darkwing/pok0.ogg
sound/st_allies/darkwing/pok1.ogg
sound/st_allies/darkwing/pok2.ogg
sound/st_allies/darkwing/pok3.ogg
sound/st_allies/darkwing/quest0.ogg
sound/st_allies/darkwing/quest00.ogg
sound/st_allies/darkwing/quest01.ogg
sound/st_allies/darkwing/quest1.ogg
sound/st_allies/darkwing/quest2.ogg
sound/st_allies/darkwing/quest3.ogg
sound/st_allies/darkwing/quest4.ogg
sound/st_allies/darkwing/quest5.ogg
sound/st_allies/darkwing/scared0.ogg
sound/st_allies/darkwing/scared1.ogg
sound/st_allies/darkwing/shot0.ogg
sound/st_allies/darkwing/shot1.ogg
sound/st_allies/darkwing/shot2.ogg
sound/st_allies/darkwing/shot3.ogg
sound/st_allies/darkwing/shot5.ogg
sound/st_allies/darkwing/taunt0.ogg
sound/st_allies/darkwing/taunt1.ogg
sound/st_allies/darkwing/taunt2.ogg
sound/st_allies/darkwing/taunt3.ogg
sound/st_allies/darkwing/taunt4.ogg
sound/st_allies/darkwing/taunt5.ogg
sound/st_allies/darkwing/wait0.ogg
sound/st_allies/darkwing/wait1.ogg
sound/st_allies/darkwing/wait2.ogg
sound/st_allies/darkwing/wait3.ogg
sound/st_allies/darkwing/wound0.ogg
sound/st_allies/darkwing/wound1.ogg
sound/st_allies/darkwing/wound2.ogg
sound/st_allies/lowell/lw_alert1.ogg
sound/st_allies/lowell/lw_alert2.ogg
sound/st_allies/lowell/lw_alert3.ogg
sound/st_allies/lowell/lw_b10_portal.ogg
sound/st_allies/lowell/lw_b10_second.ogg
sound/st_allies/lowell/lw_pain1.ogg
sound/st_allies/lowell/lw_pain2.ogg
sound/st_allies/lowell/lw_pain3.ogg
sound/st_allies/lowell/lw_portal_in.ogg
sound/st_allies/lowell/lw_portal_out.ogg
sound/st_allies/lowell/lw_seeker1.ogg
sound/st_allies/miles/death1.wav
sound/st_allies/miles/death2.wav
sound/st_allies/miles/death3.wav
sound/st_allies/miles/ml_answer1.wav
sound/st_allies/miles/ml_answer10.wav
sound/st_allies/miles/ml_answer11.wav
sound/st_allies/miles/ml_answer12.wav
sound/st_allies/miles/ml_answer13.wav
sound/st_allies/miles/ml_answer14.wav
sound/st_allies/miles/ml_answer15.wav
sound/st_allies/miles/ml_answer16.wav
sound/st_allies/miles/ml_answer17.wav
sound/st_allies/miles/ml_answer18.wav
sound/st_allies/miles/ml_answer19.wav
sound/st_allies/miles/ml_answer2.wav
sound/st_allies/miles/ml_answer20.wav
sound/st_allies/miles/ml_answer21.wav
sound/st_allies/miles/ml_answer22.wav
sound/st_allies/miles/ml_answer3.wav
sound/st_allies/miles/ml_answer4.wav
sound/st_allies/miles/ml_answer5.wav
sound/st_allies/miles/ml_answer6.wav
sound/st_allies/miles/ml_answer7.wav
sound/st_allies/miles/ml_answer8.wav
sound/st_allies/miles/ml_answer9.wav
sound/st_allies/miles/ml_attack1.wav
sound/st_allies/miles/ml_attack2.wav
sound/st_allies/miles/ml_attack3.wav
sound/st_allies/miles/ml_attack4.wav
sound/st_allies/miles/ml_attack5.wav
sound/st_allies/miles/ml_b10_crystals.ogg
sound/st_allies/miles/ml_b10_whats.ogg
sound/st_allies/miles/ml_cure-a.wav
sound/st_allies/miles/ml_cure-b.wav
sound/st_allies/miles/ml_cure-c.wav
sound/st_allies/miles/ml_hear1.wav
sound/st_allies/miles/ml_hear2.wav
sound/st_allies/miles/ml_hear3.wav
sound/st_allies/miles/ml_hello1.wav
sound/st_allies/miles/ml_hello2.wav
sound/st_allies/miles/ml_hello3.wav
sound/st_allies/miles/ml_hello4.wav
sound/st_allies/miles/ml_hello5.wav
sound/st_allies/miles/ml_hello6.wav
sound/st_allies/miles/ml_hello7.wav
sound/st_allies/miles/ml_idle1.wav
sound/st_allies/miles/ml_idle10.wav
sound/st_allies/miles/ml_idle11.wav
sound/st_allies/miles/ml_idle2.wav
sound/st_allies/miles/ml_idle3.wav
sound/st_allies/miles/ml_idle4.wav
sound/st_allies/miles/ml_idle5.wav
sound/st_allies/miles/ml_idle6.wav
sound/st_allies/miles/ml_idle7.wav
sound/st_allies/miles/ml_idle8.wav
sound/st_allies/miles/ml_idle9.wav
sound/st_allies/miles/ml_kill1.wav
sound/st_allies/miles/ml_kill2.wav
sound/st_allies/miles/ml_kill3.wav
sound/st_allies/miles/ml_kill4.wav
sound/st_allies/miles/ml_kill5.wav
sound/st_allies/miles/ml_kill6.wav
sound/st_allies/miles/ml_kill7.wav
sound/st_allies/miles/ml_mad1.wav
sound/st_allies/miles/ml_mad2.wav
sound/st_allies/miles/ml_mad3.wav
sound/st_allies/miles/ml_mad4.wav
sound/st_allies/miles/ml_mad5.wav
sound/st_allies/miles/ml_mad6.wav
sound/st_allies/miles/ml_mad7.wav
sound/st_allies/miles/ml_mortal.wav
sound/st_allies/miles/ml_ok1.wav
sound/st_allies/miles/ml_ok2.wav
sound/st_allies/miles/ml_ok3.wav
sound/st_allies/miles/ml_ok4.wav
sound/st_allies/miles/ml_ok5.wav
sound/st_allies/miles/ml_ok6.wav
sound/st_allies/miles/ml_pok1.wav
sound/st_allies/miles/ml_pok2.wav
sound/st_allies/miles/ml_pok3.wav
sound/st_allies/miles/ml_pok4.wav
sound/st_allies/miles/ml_quest1.wav
sound/st_allies/miles/ml_quest10.wav
sound/st_allies/miles/ml_quest11.wav
sound/st_allies/miles/ml_quest12.wav
sound/st_allies/miles/ml_quest13.wav
sound/st_allies/miles/ml_quest14.wav
sound/st_allies/miles/ml_quest15.wav
sound/st_allies/miles/ml_quest2.wav
sound/st_allies/miles/ml_quest3.wav
sound/st_allies/miles/ml_quest4.wav
sound/st_allies/miles/ml_quest5.wav
sound/st_allies/miles/ml_quest6.wav
sound/st_allies/miles/ml_quest7.wav
sound/st_allies/miles/ml_quest8.wav
sound/st_allies/miles/ml_quest9.wav
sound/st_allies/miles/ml_scared1.ogg
sound/st_allies/miles/ml_scared2.wav
sound/st_allies/miles/ml_shot1.wav
sound/st_allies/miles/ml_shot2.wav
sound/st_allies/miles/ml_shot3.wav
sound/st_allies/miles/ml_shot4.wav
sound/st_allies/miles/ml_shot5.wav
sound/st_allies/miles/ml_smell1.wav
sound/st_allies/miles/ml_smell2.wav
sound/st_allies/miles/ml_smell3.wav
sound/st_allies/miles/ml_stare1.wav
sound/st_allies/miles/ml_stare2.wav
sound/st_allies/miles/ml_stare3.wav
sound/st_allies/miles/ml_stare4.wav
sound/st_allies/miles/ml_wait1.wav
sound/st_allies/miles/ml_wait2.wav
sound/st_allies/miles/ml_wait3.wav
sound/st_allies/miles/ml_wait4.wav
sound/st_allies/miles/ml_wait5.wav
sound/st_allies/miles/ml_wait6.wav
sound/st_allies/miles/ml_wound.wav
sound/st_allies/miles/ml_wound2.wav
sound/st_allies/miles/pain1.wav
sound/st_allies/miles/pain2.wav
sound/st_allies/miles/pain3.wav
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/plinky/pl_idle5.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_idle1.ogg
sound/st_allies/sobrobo/sr_idle2.ogg
sound/st_allies/sobrobo/sr_idle3.ogg
sound/st_allies/sobrobo/sr_idle4.ogg
sound/st_allies/sobrobo/sr_idle5.ogg
sound/st_mission/music/hs_b10_final.ogg
sound/st_mission/music/hs_b10_osprey.ogg
sound/st_mission/radio/hs_b10_1min.ogg
sound/st_mission/radio/hs_b10_air.ogg
sound/st_mission/radio/hs_b10_applied.ogg
sound/st_mission/radio/hs_b10_brl.ogg
sound/st_mission/radio/hs_b10_crystal.ogg
sound/st_mission/radio/hs_b10_getit.ogg
sound/st_mission/radio/hs_b10_mortar.ogg
sound/st_mission/radio/hs_b10_secure.ogg
sound/st_mission/truck3.ogg
sound/st_mission/weapons/de_shot1.ogg
sound/st_mission/weapons/f2000.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m41a_hks1.ogg
sound/st_mission/weapons/m41a_hks2.ogg
sound/st_mission/weapons/m41a_hks3.ogg
sound/st_mission/weapons/m4a1-fire.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/scar-fire.ogg
sound/st_mission/weapons/sniper_fire.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/wa2000_shoot1.ogg
sound/st_mission/weapons/xm8-fire.ogg
sprites/singularity/prtl/kz_exit1.spr
