// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_747.wad
cs_assault.wad
cs_siege.wad
hs2.wad
hs4.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/babygarg/evoluted_skeleton.mdl
models/custom_monsters/bullsquid/demonsquid.mdl
models/custom_monsters/gonome/skull_hunter.mdl
models/custom_monsters/hgrunt/security_infected.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/corrupted_experiment_clone.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/slasher_ghost01.mdl
models/custom_monsters/zombie/slasher_ghost02.mdl
models/custom_monsters/zombie/slasher_ghostt.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/szombiet.mdl
models/custom_monsters/zombie/zombie3.mdl
models/snd/osprey_crash.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/crimsoncommando/crimson01.mdl
models/st_allies/crimsoncommando/crimson02.mdl
models/st_allies/crimsoncommando/crimson03.mdl
models/st_allies/darkwing.mdl
models/st_allies/darkwing01.mdl
models/st_allies/darkwing02.mdl
models/st_allies/darkwing03.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/dead_hev2t.mdl
models/st_allies/dead_hevt.mdl
models/st_allies/plinky_assasin.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_ar01.mdl
models/st_allies/security_ar02.mdl
models/st_allies/security_ar03.mdl
models/st_allies/security_art.mdl
models/st_mission1/backpack_bio.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/biohazard_container2.mdl
models/st_mission1/crystal_red.mdl
models/st_mission1/props/cheap_forklift.mdl
models/st_mission1/props/mex_background_building_1_dest2.mdl
models/st_mission1/props/mex_ruined_house01.mdl
models/st_mission1/props/mex_ruined_house02.mdl
models/st_mission1/props/mex_ruined_house03.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
silenthill.wad
sound/custom_monsters/cec/cec_alert10.wav
sound/custom_monsters/cec/cec_alert20.wav
sound/custom_monsters/cec/cec_alert30.wav
sound/custom_monsters/cec/cec_attack1.wav
sound/custom_monsters/cec/cec_attack2.wav
sound/custom_monsters/cec/cec_idle1.wav
sound/custom_monsters/cec/cec_idle2.wav
sound/custom_monsters/cec/cec_idle3.wav
sound/custom_monsters/cec/cec_pain1.wav
sound/custom_monsters/cec/cec_pain2.wav
sound/custom_monsters/evoskeleton/evo_alert1.wav
sound/custom_monsters/evoskeleton/evo_alert2.wav
sound/custom_monsters/evoskeleton/evo_alert3.wav
sound/custom_monsters/evoskeleton/evo_attack1.wav
sound/custom_monsters/evoskeleton/evo_attack2.wav
sound/custom_monsters/evoskeleton/evo_attack3.wav
sound/custom_monsters/evoskeleton/evo_pain1.wav
sound/custom_monsters/evoskeleton/evo_pain2.wav
sound/custom_monsters/ghost/con_alert1.wav
sound/custom_monsters/ghost/con_alert2.wav
sound/custom_monsters/ghost/con_alert3.wav
sound/custom_monsters/ghost/con_attack1.wav
sound/custom_monsters/ghost/con_attack2.wav
sound/custom_monsters/ghost/con_attack3.wav
sound/custom_monsters/ghost/con_die1.wav
sound/custom_monsters/ghost/con_die2.wav
sound/custom_monsters/ghost/con_idle1.wav
sound/custom_monsters/ghost/con_idle2.wav
sound/custom_monsters/ghost/con_idle3.wav
sound/custom_monsters/ghost/con_idle4.wav
sound/custom_monsters/ghost/con_idle5.wav
sound/custom_monsters/ghost/con_pain1.wav
sound/custom_monsters/ghost/con_pain2.wav
sound/custom_monsters/ghost/con_pain3.wav
sound/custom_monsters/plagueskull/ps_float.wav
sound/custom_monsters/slasherghost/sg_alert1.wav
sound/custom_monsters/slasherghost/sg_alert2.wav
sound/custom_monsters/slasherghost/sg_alert3.wav
sound/custom_monsters/slasherghost/sg_attack1.wav
sound/custom_monsters/slasherghost/sg_attack2.wav
sound/custom_monsters/slasherghost/sg_miss1.wav
sound/custom_monsters/slasherghost/sg_miss2.wav
sound/custom_monsters/slasherghost/sg_pain1.wav
sound/custom_monsters/slasherghost/sg_pain2.wav
sound/custom_monsters/slasherghost/sg_slash1.wav
sound/custom_monsters/slasherghost/sg_slash2.wav
sound/custom_monsters/slasherghost/sg_slash3.wav
sound/custom_monsters/slasherghost/sg_voice1.wav
sound/custom_monsters/slasherghost/sg_voice2.wav
sound/custom_monsters/slasherghost/sg_voice3.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_allies/darkwing/alert0.wav
sound/st_allies/darkwing/alert1.wav
sound/st_allies/darkwing/alert2.wav
sound/st_allies/darkwing/alert3.wav
sound/st_allies/darkwing/answer0.wav
sound/st_allies/darkwing/answer1.wav
sound/st_allies/darkwing/answer2.wav
sound/st_allies/darkwing/charge0.wav
sound/st_allies/darkwing/charge1.wav
sound/st_allies/darkwing/charge2.wav
sound/st_allies/darkwing/check0.wav
sound/st_allies/darkwing/check1.wav
sound/st_allies/darkwing/clear0.wav
sound/st_allies/darkwing/clear1.wav
sound/st_allies/darkwing/cover0.wav
sound/st_allies/darkwing/cover1.wav
sound/st_allies/darkwing/cover2.wav
sound/st_allies/darkwing/death1.wav
sound/st_allies/darkwing/death2.wav
sound/st_allies/darkwing/death3.wav
sound/st_allies/darkwing/dw_c6_happend.wav
sound/st_allies/darkwing/dw_c6_pit.wav
sound/st_allies/darkwing/dw_c6_wounded.wav
sound/st_allies/darkwing/gren0.wav
sound/st_allies/darkwing/gren1.wav
sound/st_allies/darkwing/hello0.wav
sound/st_allies/darkwing/hello1.wav
sound/st_allies/darkwing/hello2.wav
sound/st_allies/darkwing/idle0.wav
sound/st_allies/darkwing/idle1.wav
sound/st_allies/darkwing/idle10.wav
sound/st_allies/darkwing/idle11.wav
sound/st_allies/darkwing/idle12.wav
sound/st_allies/darkwing/idle2.wav
sound/st_allies/darkwing/idle3.wav
sound/st_allies/darkwing/idle4.wav
sound/st_allies/darkwing/idle5.wav
sound/st_allies/darkwing/idle6.wav
sound/st_allies/darkwing/idle7.wav
sound/st_allies/darkwing/idle8.wav
sound/st_allies/darkwing/idle9.wav
sound/st_allies/darkwing/kill0.wav
sound/st_allies/darkwing/kill1.wav
sound/st_allies/darkwing/kill2.wav
sound/st_allies/darkwing/kill3.wav
sound/st_allies/darkwing/kill4.wav
sound/st_allies/darkwing/kill5.wav
sound/st_allies/darkwing/kill6.wav
sound/st_allies/darkwing/kill7.wav
sound/st_allies/darkwing/kill8.wav
sound/st_allies/darkwing/kill9.wav
sound/st_allies/darkwing/mad0.wav
sound/st_allies/darkwing/mad1.wav
sound/st_allies/darkwing/monster0.wav
sound/st_allies/darkwing/monster1.wav
sound/st_allies/darkwing/mortal0.wav
sound/st_allies/darkwing/mortal1.wav
sound/st_allies/darkwing/mortal2.wav
sound/st_allies/darkwing/ok0.wav
sound/st_allies/darkwing/ok1.wav
sound/st_allies/darkwing/ok2.wav
sound/st_allies/darkwing/ok3.wav
sound/st_allies/darkwing/ok4.wav
sound/st_allies/darkwing/ok5.wav
sound/st_allies/darkwing/ok6.wav
sound/st_allies/darkwing/ok7.wav
sound/st_allies/darkwing/ok8.wav
sound/st_allies/darkwing/ok9.wav
sound/st_allies/darkwing/pain1.wav
sound/st_allies/darkwing/pain2.wav
sound/st_allies/darkwing/pain3.wav
sound/st_allies/darkwing/pain4.wav
sound/st_allies/darkwing/pok0.wav
sound/st_allies/darkwing/pok1.wav
sound/st_allies/darkwing/pok2.wav
sound/st_allies/darkwing/pok3.wav
sound/st_allies/darkwing/quest0.wav
sound/st_allies/darkwing/quest00.wav
sound/st_allies/darkwing/quest01.wav
sound/st_allies/darkwing/quest1.wav
sound/st_allies/darkwing/quest2.wav
sound/st_allies/darkwing/quest3.wav
sound/st_allies/darkwing/quest4.wav
sound/st_allies/darkwing/quest5.wav
sound/st_allies/darkwing/scared0.wav
sound/st_allies/darkwing/scared1.wav
sound/st_allies/darkwing/shot0.wav
sound/st_allies/darkwing/shot1.wav
sound/st_allies/darkwing/shot2.wav
sound/st_allies/darkwing/shot3.wav
sound/st_allies/darkwing/shot5.wav
sound/st_allies/darkwing/taunt0.wav
sound/st_allies/darkwing/taunt1.wav
sound/st_allies/darkwing/taunt2.wav
sound/st_allies/darkwing/taunt3.wav
sound/st_allies/darkwing/taunt4.wav
sound/st_allies/darkwing/taunt5.wav
sound/st_allies/darkwing/wait0.wav
sound/st_allies/darkwing/wait1.wav
sound/st_allies/darkwing/wait2.wav
sound/st_allies/darkwing/wait3.wav
sound/st_allies/darkwing/wound0.wav
sound/st_allies/darkwing/wound1.wav
sound/st_allies/darkwing/wound2.wav
sound/st_mission/distantfirefight.wav
sound/st_mission/events/hs_c4/security_die.wav
sound/st_mission/events/hs_c4/warp_out.wav
sound/st_mission/flareidle.wav
sound/st_mission/hellambient.wav
sound/st_mission/music/ambience06.ogg
sound/st_mission/night.wav
sound/st_mission/outdoorbattle.wav
sound/st_mission/teleport_in.wav
sound/st_mission/teleport_out.wav
sound/st_mission/truck_goes.wav
sound/st_mission/tunnel_wind1.wav
sound/st_mission/weapons/f2000.wav
sound/st_mission/weapons/fn_in1.wav
sound/st_mission/weapons/fn_out1.wav
sound/st_mission/weapons/g3_in.wav
sound/st_mission/weapons/g3_out.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sprites/kezaeiv/prtl/kz_exit1.spr
