// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
aomreal.wad
bigcity2.wad
cars.wad
cs_747.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
hs.wad
hs2.wad
hs3.wad
hs4.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/babygarg/evoluted_skeleton.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/nimblezombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/slasher_ghost01.mdl
models/custom_monsters/zombie/slasher_ghost02.mdl
models/custom_monsters/zombie/slasher_ghostt.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/szombiet.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/crimsoncommando/crimson01.mdl
models/st_allies/crimsoncommando/crimson02.mdl
models/st_allies/crimsoncommando/crimson03.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/cyrex_upgraded.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/dead_hev2t.mdl
models/st_allies/dead_hevt.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor01.mdl
models/st_allies/nimblegrunt/ngrunt_opfor02.mdl
models/st_allies/nimblegrunt/ngrunt_opfor03.mdl
models/st_allies/nimblegrunt/ngrunt_opfor2.mdl
models/st_allies/nimblegrunt/ngrunt_opfor201.mdl
models/st_allies/nimblegrunt/ngrunt_opfor202.mdl
models/st_allies/nimblegrunt/ngrunt_opfor203.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_ar01.mdl
models/st_allies/security_ar02.mdl
models/st_allies/security_ar03.mdl
models/st_allies/security_art.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/props/bigbluetruck.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/phone_pay-us.mdl
models/st_mission1/props/trash2.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
siege_apc.wad
sound/custom_monsters/evoskeleton/evo_alert1.wav
sound/custom_monsters/evoskeleton/evo_alert2.wav
sound/custom_monsters/evoskeleton/evo_alert3.wav
sound/custom_monsters/evoskeleton/evo_attack1.wav
sound/custom_monsters/evoskeleton/evo_attack2.wav
sound/custom_monsters/evoskeleton/evo_attack3.wav
sound/custom_monsters/evoskeleton/evo_pain1.wav
sound/custom_monsters/evoskeleton/evo_pain2.wav
sound/custom_monsters/ghost/con_alert1.wav
sound/custom_monsters/ghost/con_alert2.wav
sound/custom_monsters/ghost/con_alert3.wav
sound/custom_monsters/ghost/con_attack1.wav
sound/custom_monsters/ghost/con_attack2.wav
sound/custom_monsters/ghost/con_attack3.wav
sound/custom_monsters/ghost/con_die1.wav
sound/custom_monsters/ghost/con_die2.wav
sound/custom_monsters/ghost/con_idle1.wav
sound/custom_monsters/ghost/con_idle2.wav
sound/custom_monsters/ghost/con_idle3.wav
sound/custom_monsters/ghost/con_idle4.wav
sound/custom_monsters/ghost/con_idle5.wav
sound/custom_monsters/ghost/con_pain1.wav
sound/custom_monsters/ghost/con_pain2.wav
sound/custom_monsters/ghost/con_pain3.wav
sound/custom_monsters/guns/shotgun/sbarrel1.wav
sound/custom_monsters/guns/smg/hks1.wav
sound/custom_monsters/guns/smg/hks2.wav
sound/custom_monsters/guns/smg/hks3.wav
sound/custom_monsters/plagueskull/ps_float.wav
sound/custom_monsters/slasherghost/sg_alert1.wav
sound/custom_monsters/slasherghost/sg_alert2.wav
sound/custom_monsters/slasherghost/sg_alert3.wav
sound/custom_monsters/slasherghost/sg_attack1.wav
sound/custom_monsters/slasherghost/sg_attack2.wav
sound/custom_monsters/slasherghost/sg_miss1.wav
sound/custom_monsters/slasherghost/sg_miss2.wav
sound/custom_monsters/slasherghost/sg_pain1.wav
sound/custom_monsters/slasherghost/sg_pain2.wav
sound/custom_monsters/slasherghost/sg_slash1.wav
sound/custom_monsters/slasherghost/sg_slash2.wav
sound/custom_monsters/slasherghost/sg_slash3.wav
sound/custom_monsters/slasherghost/sg_voice1.wav
sound/custom_monsters/slasherghost/sg_voice2.wav
sound/custom_monsters/slasherghost/sg_voice3.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_allies/crimson_commando/ass.wav
sound/st_allies/crimson_commando/babysitting.wav
sound/st_allies/crimson_commando/check.wav
sound/st_allies/crimson_commando/corporal_01.wav
sound/st_allies/crimson_commando/coverup.wav
sound/st_allies/crimson_commando/damage.wav
sound/st_allies/crimson_commando/death1.wav
sound/st_allies/crimson_commando/death2.wav
sound/st_allies/crimson_commando/death3.wav
sound/st_allies/crimson_commando/flank.wav
sound/st_allies/crimson_commando/gr_pain1.wav
sound/st_allies/crimson_commando/gr_pain2.wav
sound/st_allies/crimson_commando/gr_pain3.wav
sound/st_allies/crimson_commando/gr_pain4.wav
sound/st_allies/crimson_commando/guard.wav
sound/st_allies/crimson_commando/guardduty.wav
sound/st_allies/crimson_commando/hellosir.wav
sound/st_allies/crimson_commando/hitbad.wav
sound/st_allies/crimson_commando/hostiles.wav
sound/st_allies/crimson_commando/imhit.wav
sound/st_allies/crimson_commando/mission.wav
sound/st_allies/crimson_commando/mister.wav
sound/st_allies/crimson_commando/moving.wav
sound/st_allies/crimson_commando/now.wav
sound/st_allies/crimson_commando/orders.wav
sound/st_allies/crimson_commando/scout.wav
sound/st_allies/crimson_commando/secure.wav
sound/st_allies/crimson_commando/six.wav
sound/st_allies/crimson_commando/sniper.wav
sound/st_allies/crimson_commando/wantsome.wav
sound/st_allies/crimson_commando/zone.wav
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle2.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/nimble_grunt/alert.wav
sound/st_allies/nimble_grunt/area.wav
sound/st_allies/nimble_grunt/ass.wav
sound/st_allies/nimble_grunt/babysitting.wav
sound/st_allies/nimble_grunt/backup.wav
sound/st_allies/nimble_grunt/bfeeling.wav
sound/st_allies/nimble_grunt/bogies.wav
sound/st_allies/nimble_grunt/charge.wav
sound/st_allies/nimble_grunt/check.wav
sound/st_allies/nimble_grunt/checkrecon.wav
sound/st_allies/nimble_grunt/chicken.wav
sound/st_allies/nimble_grunt/clear.wav
sound/st_allies/nimble_grunt/command.wav
sound/st_allies/nimble_grunt/corners.wav
sound/st_allies/nimble_grunt/corporal.wav
sound/st_allies/nimble_grunt/corporal_01.wav
sound/st_allies/nimble_grunt/cover.wav
sound/st_allies/nimble_grunt/covering.wav
sound/st_allies/nimble_grunt/coverup.wav
sound/st_allies/nimble_grunt/current.wav
sound/st_allies/nimble_grunt/damage.wav
sound/st_allies/nimble_grunt/death1.wav
sound/st_allies/nimble_grunt/death2.wav
sound/st_allies/nimble_grunt/death3.wav
sound/st_allies/nimble_grunt/disney.wav
sound/st_allies/nimble_grunt/dogs.wav
sound/st_allies/nimble_grunt/down.wav
sound/st_allies/nimble_grunt/flank.wav
sound/st_allies/nimble_grunt/freaks.wav
sound/st_allies/nimble_grunt/friendly.wav
sound/st_allies/nimble_grunt/fubar.wav
sound/st_allies/nimble_grunt/getsome.wav
sound/st_allies/nimble_grunt/go.wav
sound/st_allies/nimble_grunt/gotit.wav
sound/st_allies/nimble_grunt/gr_pain1.wav
sound/st_allies/nimble_grunt/gr_pain2.wav
sound/st_allies/nimble_grunt/gr_pain3.wav
sound/st_allies/nimble_grunt/gr_pain4.wav
sound/st_allies/nimble_grunt/grenade.wav
sound/st_allies/nimble_grunt/guard.wav
sound/st_allies/nimble_grunt/guardduty.wav
sound/st_allies/nimble_grunt/hellosir.wav
sound/st_allies/nimble_grunt/hellout.wav
sound/st_allies/nimble_grunt/hitbad.wav
sound/st_allies/nimble_grunt/hostiles.wav
sound/st_allies/nimble_grunt/imhit.wav
sound/st_allies/nimble_grunt/incoming.wav
sound/st_allies/nimble_grunt/lost.wav
sound/st_allies/nimble_grunt/marines.wav
sound/st_allies/nimble_grunt/mission.wav
sound/st_allies/nimble_grunt/mister.wav
sound/st_allies/nimble_grunt/move.wav
sound/st_allies/nimble_grunt/moveup.wav
sound/st_allies/nimble_grunt/moving.wav
sound/st_allies/nimble_grunt/no.wav
sound/st_allies/nimble_grunt/notfail.wav
sound/st_allies/nimble_grunt/nothing.wav
sound/st_allies/nimble_grunt/now.wav
sound/st_allies/nimble_grunt/oneshot.wav
sound/st_allies/nimble_grunt/orders.wav
sound/st_allies/nimble_grunt/outof.wav
sound/st_allies/nimble_grunt/pain1.wav
sound/st_allies/nimble_grunt/pain2.wav
sound/st_allies/nimble_grunt/pain3.wav
sound/st_allies/nimble_grunt/pain4.wav
sound/st_allies/nimble_grunt/quiet.wav
sound/st_allies/nimble_grunt/rapidfire.wav
sound/st_allies/nimble_grunt/recon.wav
sound/st_allies/nimble_grunt/right.wav
sound/st_allies/nimble_grunt/roger.wav
sound/st_allies/nimble_grunt/scout.wav
sound/st_allies/nimble_grunt/secure.wav
sound/st_allies/nimble_grunt/seensquad.wav
sound/st_allies/nimble_grunt/short.wav
sound/st_allies/nimble_grunt/six.wav
sound/st_allies/nimble_grunt/sniper.wav
sound/st_allies/nimble_grunt/suppressing.wav
sound/st_allies/nimble_grunt/sweep.wav
sound/st_allies/nimble_grunt/tag.wav
sound/st_allies/nimble_grunt/take.wav
sound/st_allies/nimble_grunt/talking.wav
sound/st_allies/nimble_grunt/wantsome.wav
sound/st_allies/nimble_grunt/watchfire.wav
sound/st_allies/nimble_grunt/watchit.wav
sound/st_allies/nimble_grunt/yes.wav
sound/st_allies/nimble_grunt/zone.wav
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_mission/22noice2.wav
sound/st_mission/airdrop.wav
sound/st_mission/airdropjet1.wav
sound/st_mission/events/hs_c4/distant_angel_shadows.wav
sound/st_mission/events/hs_c4/distant_angel_shoot.wav
sound/st_mission/events/hs_c4/distant_angel_warp.wav
sound/st_mission/events/hs_c4/distant_demon_attack.wav
sound/st_mission/events/hs_c4/distant_demon_dash.wav
sound/st_mission/events/hs_c4/distant_displace.wav
sound/st_mission/events/hs_c4/distant_explosion.wav
sound/st_mission/flareidle.wav
sound/st_mission/music/ambience04.wav
sound/st_mission/outdoorbattle.wav
sound/st_mission/outdoorbattle_inside.wav
sound/st_mission/rain1.wav
sound/st_mission/rain_window.wav
sound/st_mission/thunder1.wav
sound/st_mission/thunder2.wav
sound/st_mission/thunder3.wav
sound/st_mission/thunder4.wav
sound/st_mission/weapons/fn_in1.wav
sound/st_mission/weapons/fn_out1.wav
sound/st_mission/weapons/g36.wav
sound/st_mission/weapons/g3_in.wav
sound/st_mission/weapons/g3_out.wav
sound/st_mission/weapons/m4a1-fire.wav
sound/st_mission/weapons/m60-fire1.wav
sound/st_mission/weapons/sbarrel1.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sound/st_mission/weapons/wa2000_shoot1.wav
sprites/kezaeiv/prtl/kz_exit1.spr
