// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomdc22.wad
aomreal.wad
bigcity2.wad
cs_747.wad
cs_office.wad
cs_siege.wad
hle.wad
hs.wad
hs3.wad
hs5.wad
models/custom_monsters/agrunt/agrunt_snow.mdl
models/custom_monsters/bullsquid/snowsquid.mdl
models/custom_monsters/gonome/mutant_runner.mdl
models/custom_monsters/stukabat/lostsoul.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/twitcher.mdl
models/sp_portal/ginsengavenger/gins_bucket.mdl
models/st_allies/chef.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/dead_hev.mdl
models/st_allies/fat_scientist.mdl
models/st_allies/glitched_sci.mdl
models/st_allies/glitched_security_ar.mdl
models/st_allies/janitor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/scientist.mdl
models/st_allies/security_ar.mdl
models/st_mission1/props/big_bucket.mdl
models/st_mission1/props/food_tray.mdl
models/st_mission1/props/qmeal.mdl
models/st_mission1/props/secretdonutbox1.mdl
models/st_mission1/props/trash.mdl
models/st_mission1/props/wall_basement_computer1.mdl
models/st_mission1/props/wall_basement_computer3.mdl
models/st_mission1/props/wall_computer1.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/crimson/v_357.mdl
models/st_mission1/weapons_classic/crimson/v_9mmar.mdl
models/st_mission1/weapons_classic/crimson/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/crimson/v_crossbow.mdl
models/st_mission1/weapons_classic/crimson/v_crowbar.mdl
models/st_mission1/weapons_classic/crimson/v_displacer.mdl
models/st_mission1/weapons_classic/crimson/v_eagle.mdl
models/st_mission1/weapons_classic/crimson/v_egon.mdl
models/st_mission1/weapons_classic/crimson/v_gauss.mdl
models/st_mission1/weapons_classic/crimson/v_grenade.mdl
models/st_mission1/weapons_classic/crimson/v_m16a2.mdl
models/st_mission1/weapons_classic/crimson/v_m40a1.mdl
models/st_mission1/weapons_classic/crimson/v_medkit.mdl
models/st_mission1/weapons_classic/crimson/v_minigun.mdl
models/st_mission1/weapons_classic/crimson/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/crimson/v_rpg.mdl
models/st_mission1/weapons_classic/crimson/v_satchel.mdl
models/st_mission1/weapons_classic/crimson/v_satchel_radio.mdl
models/st_mission1/weapons_classic/crimson/v_saw.mdl
models/st_mission1/weapons_classic/crimson/v_shotgun.mdl
models/st_mission1/weapons_classic/crimson/v_spore_launcher.mdl
models/st_mission1/weapons_classic/crimson/v_squeak.mdl
models/st_mission1/weapons_classic/crimson/v_tripmine.mdl
models/st_mission1/weapons_classic/crimson/v_uzi.mdl
models/st_mission1/weapons_classic/p_bgrap.mdl
models/st_mission1/weapons_classic/p_displacer.mdl
models/st_mission1/weapons_classic/v_bgrap.mdl
models/st_mission1/weapons_classic/w_bgrap.mdl
models/st_mission1/weapons_classic/w_displacer.mdl
models/st_mission1/weapons_classic/w_gauss.mdl
sound/cleaner/spray1.wav
sound/cleaner/spray2.wav
sound/cleaner/sweep1.wav
sound/cleaner/sweep2.wav
sound/cleaner/sweep3.wav
sound/cleaner/wipe.wav
sound/custom_monsters/glitchzombie/claw_miss1.ogg
sound/custom_monsters/glitchzombie/claw_miss2.ogg
sound/custom_monsters/glitchzombie/claw_strike1.ogg
sound/custom_monsters/glitchzombie/claw_strike2.ogg
sound/custom_monsters/glitchzombie/claw_strike3.ogg
sound/custom_monsters/glitchzombie/zo_alert10.ogg
sound/custom_monsters/glitchzombie/zo_alert20.ogg
sound/custom_monsters/glitchzombie/zo_alert30.ogg
sound/custom_monsters/glitchzombie/zo_attack1.ogg
sound/custom_monsters/glitchzombie/zo_attack2.ogg
sound/custom_monsters/glitchzombie/zo_idle1.ogg
sound/custom_monsters/glitchzombie/zo_idle2.ogg
sound/custom_monsters/glitchzombie/zo_idle3.ogg
sound/custom_monsters/glitchzombie/zo_idle4.ogg
sound/custom_monsters/glitchzombie/zo_pain1.ogg
sound/custom_monsters/glitchzombie/zo_pain2.ogg
sound/custom_monsters/mutantrunner/mr_alert2.ogg
sound/custom_monsters/mutantrunner/mr_alert3.ogg
sound/custom_monsters/mutantrunner/mr_attack.ogg
sound/custom_monsters/mutantrunner/mr_die1.ogg
sound/custom_monsters/mutantrunner/mr_die2.ogg
sound/custom_monsters/mutantrunner/mr_hit1.ogg
sound/custom_monsters/mutantrunner/mr_hit2.ogg
sound/custom_monsters/mutantrunner/mr_idle1.ogg
sound/custom_monsters/mutantrunner/mr_idle2.ogg
sound/custom_monsters/mutantrunner/mr_pain1.ogg
sound/custom_monsters/mutantrunner/mr_pain2.ogg
sound/custom_monsters/necroscasm/claw_miss1.ogg
sound/custom_monsters/necroscasm/claw_miss2.ogg
sound/custom_monsters/necroscasm/claw_strike1.ogg
sound/custom_monsters/necroscasm/claw_strike2.ogg
sound/custom_monsters/necroscasm/claw_strike3.ogg
sound/custom_monsters/necroscasm/zo_alert10.ogg
sound/custom_monsters/necroscasm/zo_alert20.ogg
sound/custom_monsters/necroscasm/zo_alert30.ogg
sound/custom_monsters/necroscasm/zo_attack1.ogg
sound/custom_monsters/necroscasm/zo_attack2.ogg
sound/custom_monsters/necroscasm/zo_idle1.ogg
sound/custom_monsters/necroscasm/zo_idle2.ogg
sound/custom_monsters/necroscasm/zo_idle3.ogg
sound/custom_monsters/necroscasm/zo_idle4.ogg
sound/custom_monsters/necroscasm/zo_pain1.ogg
sound/custom_monsters/necroscasm/zo_pain2.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/voidfold_cannon_charge.ogg
sound/hs/weapons/voidfold_cannon_charge2.ogg
sound/hs/weapons/voidfold_cannon_fire.ogg
sound/hs/weapons/voidfold_cannon_impact.ogg
sound/hs/weapons/voidfold_cannon_playertp.ogg
sound/hs/weapons/voidfold_cannon_selftp.ogg
sound/hs/weapons/voidfold_cannon_start.ogg
sound/hs/weapons/voidfold_cannon_teleport.ogg
sound/oghs/misc/cp02_03.mp3
sound/scientist/AM_typing.wav
sound/singularity/misc/teleport.wav
sound/st_mission/22noice2.ogg
sound/st_mission/airraid.ogg
sound/st_mission/angelic_energy.ogg
sound/st_mission/helicopter13.ogg
sound/st_mission/jet_inside.ogg
sound/st_mission/music/background/c/c3_amb_facility01.ogg
sound/st_mission/music/background/c/c3_amb_facility02.ogg
sound/st_mission/music/background/c/c3_amb_facility03.ogg
sound/st_mission/music/background/c/c3_amb_facility04.ogg
sound/st_mission/music/background/c/c3_amb_facility05.ogg
sound/st_mission/music/background/c/c3_amb_facility06.ogg
sound/st_mission/radio/hs_d7_radio.ogg
sound/st_mission/static.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/arctic_incident/ws_snow_fx.spr
sprites/singularity/prtl/kz_exit1.spr
