// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/mil_crategibs.mdl
aomreal.wad
cs_747.wad
cs_assault.wad
gfx/env/sky_wasteland02bk.tga
gfx/env/sky_wasteland02dn.tga
gfx/env/sky_wasteland02ft.tga
gfx/env/sky_wasteland02lf.tga
gfx/env/sky_wasteland02rt.tga
gfx/env/sky_wasteland02up.tga
hs3.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/slavegrunt.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/darkgaunt.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/bullsquid/bullsquidgreen.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/gonome/friendlygonome2.mdl
models/custom_monsters/gonome/heavy_zombie.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/headcrab/baby_panther.mdl
models/custom_monsters/pitdrone/bluedrone.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/stukabat/lostsoul.mdl
models/custom_monsters/zombie/corrupted_experiment_clone.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/sci_poss.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_construct.mdl
models/custom_monsters/zombie/zombie_crowbar.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/st_allies/brad.mdl
models/st_allies/dead_hev.mdl
models/st_allies/miles.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/security_grunt.mdl
models/st_allies/security_torch_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/sobrobo_armed.mdl
models/st_mission1/c4.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/trash.mdl
models/st_mission1/props/trash3.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/baby_panther/bp_alert1.ogg
sound/custom_monsters/baby_panther/bp_alert2.ogg
sound/custom_monsters/baby_panther/bp_attack1.ogg
sound/custom_monsters/baby_panther/bp_attack2.ogg
sound/custom_monsters/baby_panther/bp_attack3.ogg
sound/custom_monsters/baby_panther/bp_die1.ogg
sound/custom_monsters/baby_panther/bp_die2.ogg
sound/custom_monsters/baby_panther/bp_headbite.ogg
sound/custom_monsters/baby_panther/bp_idle1.ogg
sound/custom_monsters/baby_panther/bp_idle2.ogg
sound/custom_monsters/baby_panther/bp_idle3.ogg
sound/custom_monsters/baby_panther/bp_idle4.ogg
sound/custom_monsters/baby_panther/bp_idle5.ogg
sound/custom_monsters/baby_panther/bp_pain1.ogg
sound/custom_monsters/baby_panther/bp_pain2.ogg
sound/custom_monsters/baby_panther/bp_pain3.ogg
sound/custom_monsters/cec/cec_alert10.ogg
sound/custom_monsters/cec/cec_alert20.ogg
sound/custom_monsters/cec/cec_alert30.ogg
sound/custom_monsters/cec/cec_attack1.ogg
sound/custom_monsters/cec/cec_attack2.ogg
sound/custom_monsters/cec/cec_idle1.ogg
sound/custom_monsters/cec/cec_idle2.ogg
sound/custom_monsters/cec/cec_idle3.ogg
sound/custom_monsters/cec/cec_pain1.ogg
sound/custom_monsters/cec/cec_pain2.ogg
sound/custom_monsters/friendly/fr_alert1.ogg
sound/custom_monsters/friendly/fr_alert2.ogg
sound/custom_monsters/friendly/fr_alert3.ogg
sound/custom_monsters/friendly/fr_attack1.ogg
sound/custom_monsters/friendly/fr_attack2.ogg
sound/custom_monsters/friendly/fr_die1.ogg
sound/custom_monsters/friendly/fr_fire1.ogg
sound/custom_monsters/friendly/fr_idle1.ogg
sound/custom_monsters/friendly/fr_idle2.ogg
sound/custom_monsters/friendly/fr_impact1.ogg
sound/custom_monsters/friendly/fr_pain1.ogg
sound/custom_monsters/friendly/fr_pain2.ogg
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/guns/aomshotgun/sbarrel1.ogg
sound/custom_monsters/guns/g3/g3_fire.ogg
sound/custom_monsters/guns/p90/p90-1.ogg
sound/custom_monsters/guns/taurus/tau_fire.ogg
sound/custom_monsters/sgrunt/ag_alert1.ogg
sound/custom_monsters/sgrunt/ag_alert2.ogg
sound/custom_monsters/sgrunt/ag_alert3.ogg
sound/custom_monsters/sgrunt/ag_alert4.ogg
sound/custom_monsters/sgrunt/ag_alert5.ogg
sound/custom_monsters/sgrunt/ag_attack1.ogg
sound/custom_monsters/sgrunt/ag_attack2.ogg
sound/custom_monsters/sgrunt/ag_attack3.ogg
sound/custom_monsters/sgrunt/ag_die1.ogg
sound/custom_monsters/sgrunt/ag_die2.ogg
sound/custom_monsters/sgrunt/ag_die3.ogg
sound/custom_monsters/sgrunt/ag_die4.ogg
sound/custom_monsters/sgrunt/ag_die5.ogg
sound/custom_monsters/sgrunt/ag_idle1.ogg
sound/custom_monsters/sgrunt/ag_idle2.ogg
sound/custom_monsters/sgrunt/ag_idle3.ogg
sound/custom_monsters/sgrunt/ag_idle4.ogg
sound/custom_monsters/sgrunt/ag_idle5.ogg
sound/custom_monsters/sgrunt/ag_pain1.ogg
sound/custom_monsters/sgrunt/ag_pain2.ogg
sound/custom_monsters/sgrunt/ag_pain3.ogg
sound/custom_monsters/sgrunt/ag_pain4.ogg
sound/custom_monsters/sgrunt/ag_pain5.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/miles/death1.wav
sound/st_allies/miles/death2.wav
sound/st_allies/miles/death3.wav
sound/st_allies/miles/ml_answer1.wav
sound/st_allies/miles/ml_answer10.wav
sound/st_allies/miles/ml_answer11.wav
sound/st_allies/miles/ml_answer12.wav
sound/st_allies/miles/ml_answer13.wav
sound/st_allies/miles/ml_answer14.wav
sound/st_allies/miles/ml_answer15.wav
sound/st_allies/miles/ml_answer16.wav
sound/st_allies/miles/ml_answer17.wav
sound/st_allies/miles/ml_answer18.wav
sound/st_allies/miles/ml_answer19.wav
sound/st_allies/miles/ml_answer2.wav
sound/st_allies/miles/ml_answer20.wav
sound/st_allies/miles/ml_answer21.wav
sound/st_allies/miles/ml_answer22.wav
sound/st_allies/miles/ml_answer3.wav
sound/st_allies/miles/ml_answer4.wav
sound/st_allies/miles/ml_answer5.wav
sound/st_allies/miles/ml_answer6.wav
sound/st_allies/miles/ml_answer7.wav
sound/st_allies/miles/ml_answer8.wav
sound/st_allies/miles/ml_answer9.wav
sound/st_allies/miles/ml_attack1.wav
sound/st_allies/miles/ml_attack2.wav
sound/st_allies/miles/ml_attack3.wav
sound/st_allies/miles/ml_attack4.wav
sound/st_allies/miles/ml_attack5.wav
sound/st_allies/miles/ml_b4_behindthedoor.ogg
sound/st_allies/miles/ml_b4_goodtoseeyou.ogg
sound/st_allies/miles/ml_b4_move.ogg
sound/st_allies/miles/ml_b4_thing.ogg
sound/st_allies/miles/ml_cure-a.wav
sound/st_allies/miles/ml_cure-b.wav
sound/st_allies/miles/ml_cure-c.wav
sound/st_allies/miles/ml_hear1.wav
sound/st_allies/miles/ml_hear2.wav
sound/st_allies/miles/ml_hear3.wav
sound/st_allies/miles/ml_hello1.wav
sound/st_allies/miles/ml_hello2.wav
sound/st_allies/miles/ml_hello3.wav
sound/st_allies/miles/ml_hello4.wav
sound/st_allies/miles/ml_hello5.wav
sound/st_allies/miles/ml_hello6.wav
sound/st_allies/miles/ml_hello7.wav
sound/st_allies/miles/ml_idle1.wav
sound/st_allies/miles/ml_idle10.wav
sound/st_allies/miles/ml_idle11.wav
sound/st_allies/miles/ml_idle2.wav
sound/st_allies/miles/ml_idle3.wav
sound/st_allies/miles/ml_idle4.wav
sound/st_allies/miles/ml_idle5.wav
sound/st_allies/miles/ml_idle6.wav
sound/st_allies/miles/ml_idle7.wav
sound/st_allies/miles/ml_idle8.wav
sound/st_allies/miles/ml_idle9.wav
sound/st_allies/miles/ml_kill1.wav
sound/st_allies/miles/ml_kill2.wav
sound/st_allies/miles/ml_kill3.wav
sound/st_allies/miles/ml_kill4.wav
sound/st_allies/miles/ml_kill5.wav
sound/st_allies/miles/ml_kill6.wav
sound/st_allies/miles/ml_kill7.wav
sound/st_allies/miles/ml_mad1.wav
sound/st_allies/miles/ml_mad2.wav
sound/st_allies/miles/ml_mad3.wav
sound/st_allies/miles/ml_mad4.wav
sound/st_allies/miles/ml_mad5.wav
sound/st_allies/miles/ml_mad6.wav
sound/st_allies/miles/ml_mad7.wav
sound/st_allies/miles/ml_mortal.wav
sound/st_allies/miles/ml_ok1.wav
sound/st_allies/miles/ml_ok2.wav
sound/st_allies/miles/ml_ok3.wav
sound/st_allies/miles/ml_ok4.wav
sound/st_allies/miles/ml_ok5.wav
sound/st_allies/miles/ml_ok6.wav
sound/st_allies/miles/ml_pok1.wav
sound/st_allies/miles/ml_pok2.wav
sound/st_allies/miles/ml_pok3.wav
sound/st_allies/miles/ml_pok4.wav
sound/st_allies/miles/ml_quest1.wav
sound/st_allies/miles/ml_quest10.wav
sound/st_allies/miles/ml_quest11.wav
sound/st_allies/miles/ml_quest12.wav
sound/st_allies/miles/ml_quest13.wav
sound/st_allies/miles/ml_quest14.wav
sound/st_allies/miles/ml_quest15.wav
sound/st_allies/miles/ml_quest2.wav
sound/st_allies/miles/ml_quest3.wav
sound/st_allies/miles/ml_quest4.wav
sound/st_allies/miles/ml_quest5.wav
sound/st_allies/miles/ml_quest6.wav
sound/st_allies/miles/ml_quest7.wav
sound/st_allies/miles/ml_quest8.wav
sound/st_allies/miles/ml_quest9.wav
sound/st_allies/miles/ml_scared1.ogg
sound/st_allies/miles/ml_scared2.wav
sound/st_allies/miles/ml_shot1.wav
sound/st_allies/miles/ml_shot2.wav
sound/st_allies/miles/ml_shot3.wav
sound/st_allies/miles/ml_shot4.wav
sound/st_allies/miles/ml_shot5.wav
sound/st_allies/miles/ml_smell1.wav
sound/st_allies/miles/ml_smell2.wav
sound/st_allies/miles/ml_smell3.wav
sound/st_allies/miles/ml_stare1.wav
sound/st_allies/miles/ml_stare2.wav
sound/st_allies/miles/ml_stare3.wav
sound/st_allies/miles/ml_stare4.wav
sound/st_allies/miles/ml_wait1.wav
sound/st_allies/miles/ml_wait2.wav
sound/st_allies/miles/ml_wait3.wav
sound/st_allies/miles/ml_wait4.wav
sound/st_allies/miles/ml_wait5.wav
sound/st_allies/miles/ml_wait6.wav
sound/st_allies/miles/ml_wound.wav
sound/st_allies/miles/ml_wound2.wav
sound/st_allies/miles/pain1.wav
sound/st_allies/miles/pain2.wav
sound/st_allies/miles/pain3.wav
sound/st_allies/sobrobo/sr_b4_doorclosed.ogg
sound/st_allies/sobrobo/sr_b4_elevator.ogg
sound/st_allies/sobrobo/sr_b4_hello.ogg
sound/st_allies/sobrobo/sr_b4_sorry.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_idle1.ogg
sound/st_allies/sobrobo/sr_idle2.ogg
sound/st_allies/sobrobo/sr_idle3.ogg
sound/st_allies/sobrobo/sr_idle4.ogg
sound/st_allies/sobrobo/sr_idle5.ogg
sound/st_mission/22noice2.ogg
sound/st_mission/hs_b4_dialog1.ogg
sound/st_mission/music/ambience01.ogg
sound/st_mission/tunnel_wind1.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/singularity/prtl/kz_exit1.spr
