// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomdc22.wad
aomreal.wad
bigcity2.wad
cs_office.wad
cs_siege.wad
fi.wad
gfx/env/arcdbk.tga
gfx/env/arcddn.tga
gfx/env/arcdft.tga
gfx/env/arcdlf.tga
gfx/env/arcdrt.tga
gfx/env/arcdup.tga
hle.wad
hospital.wad
hs.wad
hs2.wad
hs3.wad
hs4.wad
hs5.wad
models/custom_monsters/agrunt/agrunt_snow.mdl
models/custom_monsters/agrunt/paralyzed_subject.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/headcrab/crabgiant.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/tor/poss_rodney.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/lpzombie.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/cyrex_upgraded.mdl
models/st_allies/janitor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor3.mdl
models/st_allies/nimblegrunt/ngrunt_opfor4.mdl
models/st_allies/plinky_assasin.mdl
models/st_allies/scientist.mdl
models/st_allies/security_ar.mdl
models/st_allies/sobrobo_upgraded.mdl
models/st_allies/zngrunt.mdl
models/st_mission1/atm.mdl
models/st_mission1/crystal_orange.mdl
models/st_mission1/eatencorpse.mdl
models/st_mission1/flag_empire_small.mdl
models/st_mission1/fuse.mdl
models/st_mission1/heli_cutscene.mdl
models/st_mission1/mgrunt_cutscene.mdl
models/st_mission1/phone_pay-us.mdl
models/st_mission1/poss_rodney_cutscene.mdl
models/st_mission1/props/agonizand/ag_limb_small.mdl
models/st_mission1/props/car_truck01.mdl
models/st_mission1/props/es_3pipes_corner.mdl
models/st_mission1/props/lamp_portable_standup.mdl
models/st_mission1/props/s_cables_ceiling.mdl
models/st_mission1/props/scaffold.mdl
models/st_mission1/props/tree3.mdl
models/st_mission1/props/wall_computer5.mdl
models/st_mission1/props/wall_computer6.mdl
models/st_mission1/props/wall_computer7.mdl
models/st_mission1/props/wall_computer8.mdl
models/st_mission1/rodney_cutscene.mdl
models/st_mission1/snowflake.mdl
models/st_mission1/sobrobo_cutscene.mdl
models/st_mission1/teleporter.mdl
models/st_mission1/truck_snow.mdl
models/st_mission1/trup1.mdl
models/st_mission1/trup2.mdl
models/st_mission1/trup3.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/crimson/v_357.mdl
models/st_mission1/weapons_classic/crimson/v_9mmar.mdl
models/st_mission1/weapons_classic/crimson/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/crimson/v_crossbow.mdl
models/st_mission1/weapons_classic/crimson/v_crowbar.mdl
models/st_mission1/weapons_classic/crimson/v_displacer.mdl
models/st_mission1/weapons_classic/crimson/v_eagle.mdl
models/st_mission1/weapons_classic/crimson/v_egon.mdl
models/st_mission1/weapons_classic/crimson/v_gauss.mdl
models/st_mission1/weapons_classic/crimson/v_grenade.mdl
models/st_mission1/weapons_classic/crimson/v_m16a2.mdl
models/st_mission1/weapons_classic/crimson/v_m40a1.mdl
models/st_mission1/weapons_classic/crimson/v_medkit.mdl
models/st_mission1/weapons_classic/crimson/v_minigun.mdl
models/st_mission1/weapons_classic/crimson/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/crimson/v_rpg.mdl
models/st_mission1/weapons_classic/crimson/v_satchel.mdl
models/st_mission1/weapons_classic/crimson/v_satchel_radio.mdl
models/st_mission1/weapons_classic/crimson/v_saw.mdl
models/st_mission1/weapons_classic/crimson/v_shotgun.mdl
models/st_mission1/weapons_classic/crimson/v_spore_launcher.mdl
models/st_mission1/weapons_classic/crimson/v_squeak.mdl
models/st_mission1/weapons_classic/crimson/v_tripmine.mdl
models/st_mission1/weapons_classic/crimson/v_uzi.mdl
models/st_mission1/weapons_classic/p_bgrap.mdl
models/st_mission1/weapons_classic/p_displacer.mdl
models/st_mission1/weapons_classic/v_bgrap.mdl
models/st_mission1/weapons_classic/w_bgrap.mdl
models/st_mission1/weapons_classic/w_displacer.mdl
models/st_mission1/weapons_classic/w_gauss.mdl
silenthill.wad
sound/cleaner/spray1.wav
sound/cleaner/spray2.wav
sound/cleaner/sweep1.wav
sound/cleaner/sweep2.wav
sound/cleaner/sweep3.wav
sound/cleaner/wipe.wav
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/mercs/alert.ogg
sound/custom_monsters/mercs/area.ogg
sound/custom_monsters/mercs/ass.ogg
sound/custom_monsters/mercs/babysitting.ogg
sound/custom_monsters/mercs/backup.ogg
sound/custom_monsters/mercs/bfeeling.ogg
sound/custom_monsters/mercs/bogies.ogg
sound/custom_monsters/mercs/charge.ogg
sound/custom_monsters/mercs/check.ogg
sound/custom_monsters/mercs/checkrecon.ogg
sound/custom_monsters/mercs/chicken.ogg
sound/custom_monsters/mercs/clear.ogg
sound/custom_monsters/mercs/corners.ogg
sound/custom_monsters/mercs/cover.ogg
sound/custom_monsters/mercs/covering.ogg
sound/custom_monsters/mercs/coverup.ogg
sound/custom_monsters/mercs/critical.ogg
sound/custom_monsters/mercs/current.ogg
sound/custom_monsters/mercs/death1.ogg
sound/custom_monsters/mercs/death2.ogg
sound/custom_monsters/mercs/death3.ogg
sound/custom_monsters/mercs/disney.ogg
sound/custom_monsters/mercs/dogs.ogg
sound/custom_monsters/mercs/down.ogg
sound/custom_monsters/mercs/flank.ogg
sound/custom_monsters/mercs/freaks.ogg
sound/custom_monsters/mercs/fubar.ogg
sound/custom_monsters/mercs/getsome.ogg
sound/custom_monsters/mercs/go.ogg
sound/custom_monsters/mercs/gr_pain1.ogg
sound/custom_monsters/mercs/gr_pain2.ogg
sound/custom_monsters/mercs/gr_pain3.ogg
sound/custom_monsters/mercs/gr_pain4.ogg
sound/custom_monsters/mercs/grenade.ogg
sound/custom_monsters/mercs/hear.ogg
sound/custom_monsters/mercs/hearsome.ogg
sound/custom_monsters/mercs/hellosir.ogg
sound/custom_monsters/mercs/hostiles.ogg
sound/custom_monsters/mercs/incoming.ogg
sound/custom_monsters/mercs/lost.ogg
sound/custom_monsters/mercs/makeit.ogg
sound/custom_monsters/mercs/marines.ogg
sound/custom_monsters/mercs/mission.ogg
sound/custom_monsters/mercs/mister.ogg
sound/custom_monsters/mercs/move.ogg
sound/custom_monsters/mercs/moveup.ogg
sound/custom_monsters/mercs/no.ogg
sound/custom_monsters/mercs/nothing.ogg
sound/custom_monsters/mercs/now.ogg
sound/custom_monsters/mercs/outof.ogg
sound/custom_monsters/mercs/pain1.ogg
sound/custom_monsters/mercs/pain2.ogg
sound/custom_monsters/mercs/pain3.ogg
sound/custom_monsters/mercs/pain4.ogg
sound/custom_monsters/mercs/quiet.ogg
sound/custom_monsters/mercs/rapidfire.ogg
sound/custom_monsters/mercs/recon.ogg
sound/custom_monsters/mercs/roger.ogg
sound/custom_monsters/mercs/seensquad.ogg
sound/custom_monsters/mercs/short.ogg
sound/custom_monsters/mercs/sniper.ogg
sound/custom_monsters/mercs/suppressing.ogg
sound/custom_monsters/mercs/sweep.ogg
sound/custom_monsters/mercs/tag.ogg
sound/custom_monsters/mercs/take.ogg
sound/custom_monsters/mercs/wantsome.ogg
sound/custom_monsters/mercs/zone.ogg
sound/custom_monsters/necroscasm/claw_miss1.ogg
sound/custom_monsters/necroscasm/claw_miss2.ogg
sound/custom_monsters/necroscasm/claw_strike1.ogg
sound/custom_monsters/necroscasm/claw_strike2.ogg
sound/custom_monsters/necroscasm/claw_strike3.ogg
sound/custom_monsters/necroscasm/zo_alert10.ogg
sound/custom_monsters/necroscasm/zo_alert20.ogg
sound/custom_monsters/necroscasm/zo_alert30.ogg
sound/custom_monsters/necroscasm/zo_attack1.ogg
sound/custom_monsters/necroscasm/zo_attack2.ogg
sound/custom_monsters/necroscasm/zo_idle1.ogg
sound/custom_monsters/necroscasm/zo_idle2.ogg
sound/custom_monsters/necroscasm/zo_idle3.ogg
sound/custom_monsters/necroscasm/zo_idle4.ogg
sound/custom_monsters/necroscasm/zo_pain1.ogg
sound/custom_monsters/necroscasm/zo_pain2.ogg
sound/custom_monsters/paralyzed_subject/ps_alert1.ogg
sound/custom_monsters/paralyzed_subject/ps_alert3.ogg
sound/custom_monsters/paralyzed_subject/ps_alert4.ogg
sound/custom_monsters/paralyzed_subject/ps_attack1.ogg
sound/custom_monsters/paralyzed_subject/ps_attack2.ogg
sound/custom_monsters/paralyzed_subject/ps_attack3.ogg
sound/custom_monsters/paralyzed_subject/ps_die1.ogg
sound/custom_monsters/paralyzed_subject/ps_die4.ogg
sound/custom_monsters/paralyzed_subject/ps_die5.ogg
sound/custom_monsters/paralyzed_subject/ps_idle1.ogg
sound/custom_monsters/paralyzed_subject/ps_idle2.ogg
sound/custom_monsters/paralyzed_subject/ps_idle3.ogg
sound/custom_monsters/paralyzed_subject/ps_idle4.ogg
sound/custom_monsters/paralyzed_subject/ps_pain1.ogg
sound/custom_monsters/paralyzed_subject/ps_pain2.ogg
sound/custom_monsters/paralyzed_subject/ps_pain3.ogg
sound/custom_monsters/paralyzed_subject/ps_pain4.ogg
sound/custom_monsters/paralyzed_subject/ps_pain5.ogg
sound/custom_monsters/plagueskull/ps_float.ogg
sound/custom_monsters/portal.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/voidfold_cannon_charge.ogg
sound/hs/weapons/voidfold_cannon_charge2.ogg
sound/hs/weapons/voidfold_cannon_fire.ogg
sound/hs/weapons/voidfold_cannon_impact.ogg
sound/hs/weapons/voidfold_cannon_playertp.ogg
sound/hs/weapons/voidfold_cannon_selftp.ogg
sound/hs/weapons/voidfold_cannon_start.ogg
sound/hs/weapons/voidfold_cannon_teleport.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_allies/cyrex/cy_d12_idts.ogg
sound/st_allies/cyrex/cy_d12_sacrificed.ogg
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle2.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_hs_d12_darkwing.ogg
sound/st_allies/sobrobo/sr_hs_d12_dead.ogg
sound/st_allies/sobrobo/sr_hs_d12_gates.ogg
sound/st_mission/bigshadowsounds.ogg
sound/st_mission/demoinc_portal_idle.ogg
sound/st_mission/demonic_teleport_in.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/events/hs_d/hs_d11_goddess.ogg
sound/st_mission/events/hs_d/hs_d13_final_sfx.ogg
sound/st_mission/events/hs_d/notification.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/helicopter13.ogg
sound/st_mission/hellambient.ogg
sound/st_mission/jet_inside.ogg
sound/st_mission/largebeamstart1.ogg
sound/st_mission/music/background/d/d11_amb_tunnels01.ogg
sound/st_mission/music/background/d/d11_amb_tunnels02.ogg
sound/st_mission/music/background/d/d11_amb_tunnels03.ogg
sound/st_mission/music/background/d/d11_amb_tunnels04.ogg
sound/st_mission/outdoorbattle.ogg
sound/st_mission/outdoorbattle_inside.ogg
sound/st_mission/scary_wind2.ogg
sound/st_mission/teleport_out.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g3_fire1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m4a1-fire.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/scar-fire.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/wa2000_shoot1.ogg
sound/st_mission/weapons/xm8-fire.ogg
sprites/arctic_incident/ws_snow_fx.spr
sprites/singularity/prtl/kz_exit1.spr
