// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/mil_crategibs.mdl
9.wad
aomreal.wad
BigCity2.wad
cars.wad
cs_747.wad
cs_assault.wad
cs_office.wad
cs_siege.wad
hs2.wad
hs4.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/aliencontroller/skull.mdl
models/custom_monsters/alienslave/blueslave.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/babygarg/evoluted_skeleton.mdl
models/custom_monsters/bullsquid/demonsquid.mdl
models/custom_monsters/gonome/skull_hunter.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/hgrunt/possesed_survivor.mdl
models/custom_monsters/hgrunt/security_infected.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/corrupted_experiment_clone.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie3.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/snd/osprey_crash.mdl
models/st_allies/civilian.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/crimsoncommando/crimson2.mdl
models/st_allies/crimsoncommando/crimson4.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/darkwing.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/nimblegrunt/ngrunt_opfor3.mdl
models/st_allies/plinky_assasin.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_bio.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/biohazard_container2.mdl
models/st_mission1/crystal_red.mdl
models/st_mission1/props/2_wrecked_hatchback_grey.mdl
models/st_mission1/props/cheap_forklift.mdl
models/st_mission1/props/mex_background_building_1_dest2.mdl
models/st_mission1/props/mex_ruined_house01.mdl
models/st_mission1/props/mex_ruined_house02.mdl
models/st_mission1/props/mex_ruined_house03.mdl
models/st_mission1/props/muscle_car_grey.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
siege_apc.wad
silenthill.wad
sound/custom_monsters/cec/cec_alert10.ogg
sound/custom_monsters/cec/cec_alert20.ogg
sound/custom_monsters/cec/cec_alert30.ogg
sound/custom_monsters/cec/cec_attack1.ogg
sound/custom_monsters/cec/cec_attack2.ogg
sound/custom_monsters/cec/cec_idle1.ogg
sound/custom_monsters/cec/cec_idle2.ogg
sound/custom_monsters/cec/cec_idle3.ogg
sound/custom_monsters/cec/cec_pain1.ogg
sound/custom_monsters/cec/cec_pain2.ogg
sound/custom_monsters/evoskeleton/evo_alert1.ogg
sound/custom_monsters/evoskeleton/evo_alert2.ogg
sound/custom_monsters/evoskeleton/evo_alert3.ogg
sound/custom_monsters/evoskeleton/evo_attack1.ogg
sound/custom_monsters/evoskeleton/evo_attack2.ogg
sound/custom_monsters/evoskeleton/evo_attack3.ogg
sound/custom_monsters/evoskeleton/evo_pain1.ogg
sound/custom_monsters/evoskeleton/evo_pain2.ogg
sound/custom_monsters/ghost/con_alert1.ogg
sound/custom_monsters/ghost/con_alert2.ogg
sound/custom_monsters/ghost/con_alert3.ogg
sound/custom_monsters/ghost/con_attack1.ogg
sound/custom_monsters/ghost/con_attack2.ogg
sound/custom_monsters/ghost/con_attack3.ogg
sound/custom_monsters/ghost/con_die1.ogg
sound/custom_monsters/ghost/con_die2.ogg
sound/custom_monsters/ghost/con_idle1.ogg
sound/custom_monsters/ghost/con_idle2.ogg
sound/custom_monsters/ghost/con_idle3.ogg
sound/custom_monsters/ghost/con_idle4.ogg
sound/custom_monsters/ghost/con_idle5.ogg
sound/custom_monsters/ghost/con_pain1.ogg
sound/custom_monsters/ghost/con_pain2.ogg
sound/custom_monsters/ghost/con_pain3.ogg
sound/custom_monsters/guns/shotgun/sbarrel1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/smg/hks3.ogg
sound/custom_monsters/mercs/alert.ogg
sound/custom_monsters/mercs/area.ogg
sound/custom_monsters/mercs/ass.ogg
sound/custom_monsters/mercs/babysitting.ogg
sound/custom_monsters/mercs/backup.ogg
sound/custom_monsters/mercs/bfeeling.ogg
sound/custom_monsters/mercs/bogies.ogg
sound/custom_monsters/mercs/charge.ogg
sound/custom_monsters/mercs/check.ogg
sound/custom_monsters/mercs/checkrecon.ogg
sound/custom_monsters/mercs/chicken.ogg
sound/custom_monsters/mercs/clear.ogg
sound/custom_monsters/mercs/corners.ogg
sound/custom_monsters/mercs/cover.ogg
sound/custom_monsters/mercs/covering.ogg
sound/custom_monsters/mercs/coverup.ogg
sound/custom_monsters/mercs/critical.ogg
sound/custom_monsters/mercs/current.ogg
sound/custom_monsters/mercs/death1.ogg
sound/custom_monsters/mercs/death2.ogg
sound/custom_monsters/mercs/death3.ogg
sound/custom_monsters/mercs/disney.ogg
sound/custom_monsters/mercs/dogs.ogg
sound/custom_monsters/mercs/down.ogg
sound/custom_monsters/mercs/flank.ogg
sound/custom_monsters/mercs/freaks.ogg
sound/custom_monsters/mercs/fubar.ogg
sound/custom_monsters/mercs/getsome.ogg
sound/custom_monsters/mercs/go.ogg
sound/custom_monsters/mercs/gr_pain1.ogg
sound/custom_monsters/mercs/gr_pain2.ogg
sound/custom_monsters/mercs/gr_pain3.ogg
sound/custom_monsters/mercs/gr_pain4.ogg
sound/custom_monsters/mercs/grenade.ogg
sound/custom_monsters/mercs/hear.ogg
sound/custom_monsters/mercs/hearsome.ogg
sound/custom_monsters/mercs/hellosir.ogg
sound/custom_monsters/mercs/hostiles.ogg
sound/custom_monsters/mercs/incoming.ogg
sound/custom_monsters/mercs/lost.ogg
sound/custom_monsters/mercs/makeit.ogg
sound/custom_monsters/mercs/marines.ogg
sound/custom_monsters/mercs/mission.ogg
sound/custom_monsters/mercs/mister.ogg
sound/custom_monsters/mercs/move.ogg
sound/custom_monsters/mercs/moveup.ogg
sound/custom_monsters/mercs/no.ogg
sound/custom_monsters/mercs/nothing.ogg
sound/custom_monsters/mercs/now.ogg
sound/custom_monsters/mercs/outof.ogg
sound/custom_monsters/mercs/pain1.ogg
sound/custom_monsters/mercs/pain2.ogg
sound/custom_monsters/mercs/pain3.ogg
sound/custom_monsters/mercs/pain4.ogg
sound/custom_monsters/mercs/quiet.ogg
sound/custom_monsters/mercs/rapidfire.ogg
sound/custom_monsters/mercs/recon.ogg
sound/custom_monsters/mercs/roger.ogg
sound/custom_monsters/mercs/seensquad.ogg
sound/custom_monsters/mercs/short.ogg
sound/custom_monsters/mercs/sniper.ogg
sound/custom_monsters/mercs/suppressing.ogg
sound/custom_monsters/mercs/sweep.ogg
sound/custom_monsters/mercs/tag.ogg
sound/custom_monsters/mercs/take.ogg
sound/custom_monsters/mercs/wantsome.ogg
sound/custom_monsters/mercs/zone.ogg
sound/custom_monsters/plagueskull/ps_float.ogg
sound/custom_monsters/slasherghost/sg_alert1.ogg
sound/custom_monsters/slasherghost/sg_alert2.ogg
sound/custom_monsters/slasherghost/sg_alert3.ogg
sound/custom_monsters/slasherghost/sg_miss1.ogg
sound/custom_monsters/slasherghost/sg_miss2.ogg
sound/custom_monsters/slasherghost/sg_pain1.ogg
sound/custom_monsters/slasherghost/sg_pain2.ogg
sound/custom_monsters/slasherghost/sg_slash1.ogg
sound/custom_monsters/slasherghost/sg_slash2.ogg
sound/custom_monsters/slasherghost/sg_slash3.ogg
sound/custom_monsters/slasherghost/sg_voice1.ogg
sound/custom_monsters/slasherghost/sg_voice2.ogg
sound/custom_monsters/slasherghost/sg_voice3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/alert.ogg
sound/st_allies/crimson_commando/area.ogg
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/backup.ogg
sound/st_allies/crimson_commando/bfeeling.ogg
sound/st_allies/crimson_commando/bogies.ogg
sound/st_allies/crimson_commando/charge.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/checkrecon.ogg
sound/st_allies/crimson_commando/chicken.ogg
sound/st_allies/crimson_commando/clear.ogg
sound/st_allies/crimson_commando/command.ogg
sound/st_allies/crimson_commando/corners.ogg
sound/st_allies/crimson_commando/corporal.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/cover.ogg
sound/st_allies/crimson_commando/covering.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/current.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/disney.ogg
sound/st_allies/crimson_commando/dogs.ogg
sound/st_allies/crimson_commando/down.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/freaks.ogg
sound/st_allies/crimson_commando/friendly.ogg
sound/st_allies/crimson_commando/fubar.ogg
sound/st_allies/crimson_commando/getsome.ogg
sound/st_allies/crimson_commando/go.ogg
sound/st_allies/crimson_commando/gotit.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/grenade.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hellout.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/incoming.ogg
sound/st_allies/crimson_commando/lost.ogg
sound/st_allies/crimson_commando/marines.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/move.ogg
sound/st_allies/crimson_commando/moveup.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/no.ogg
sound/st_allies/crimson_commando/notfail.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/outof.ogg
sound/st_allies/crimson_commando/pain1.ogg
sound/st_allies/crimson_commando/pain2.ogg
sound/st_allies/crimson_commando/pain3.ogg
sound/st_allies/crimson_commando/pain4.ogg
sound/st_allies/crimson_commando/quiet.ogg
sound/st_allies/crimson_commando/rapidfire.ogg
sound/st_allies/crimson_commando/recon.ogg
sound/st_allies/crimson_commando/right.ogg
sound/st_allies/crimson_commando/roger.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/seensquad.ogg
sound/st_allies/crimson_commando/short.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/suppressing.ogg
sound/st_allies/crimson_commando/sweep.ogg
sound/st_allies/crimson_commando/tag.ogg
sound/st_allies/crimson_commando/take.ogg
sound/st_allies/crimson_commando/talking.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/watchfire.ogg
sound/st_allies/crimson_commando/watchit.ogg
sound/st_allies/crimson_commando/yes.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_allies/darkwing/alert0.ogg
sound/st_allies/darkwing/alert1.ogg
sound/st_allies/darkwing/alert2.ogg
sound/st_allies/darkwing/alert3.ogg
sound/st_allies/darkwing/answer0.ogg
sound/st_allies/darkwing/answer1.ogg
sound/st_allies/darkwing/answer2.ogg
sound/st_allies/darkwing/charge0.ogg
sound/st_allies/darkwing/charge1.ogg
sound/st_allies/darkwing/charge2.ogg
sound/st_allies/darkwing/check0.ogg
sound/st_allies/darkwing/check1.ogg
sound/st_allies/darkwing/clear0.ogg
sound/st_allies/darkwing/clear1.ogg
sound/st_allies/darkwing/cover0.ogg
sound/st_allies/darkwing/cover1.ogg
sound/st_allies/darkwing/cover2.ogg
sound/st_allies/darkwing/death1.ogg
sound/st_allies/darkwing/death2.ogg
sound/st_allies/darkwing/death3.ogg
sound/st_allies/darkwing/dw_c5_checkout.ogg
sound/st_allies/darkwing/dw_c5_door.ogg
sound/st_allies/darkwing/dw_c5_hello.ogg
sound/st_allies/darkwing/dw_c5_outside.ogg
sound/st_allies/darkwing/dw_c5_shit.ogg
sound/st_allies/darkwing/dw_c5_stupid.ogg
sound/st_allies/darkwing/dw_c6_happend.ogg
sound/st_allies/darkwing/dw_c6_pit.ogg
sound/st_allies/darkwing/dw_c6_wounded.ogg
sound/st_allies/darkwing/gren0.ogg
sound/st_allies/darkwing/gren1.ogg
sound/st_allies/darkwing/hello0.ogg
sound/st_allies/darkwing/hello1.ogg
sound/st_allies/darkwing/hello2.ogg
sound/st_allies/darkwing/idle0.ogg
sound/st_allies/darkwing/idle1.ogg
sound/st_allies/darkwing/idle10.ogg
sound/st_allies/darkwing/idle11.ogg
sound/st_allies/darkwing/idle12.ogg
sound/st_allies/darkwing/idle2.ogg
sound/st_allies/darkwing/idle3.ogg
sound/st_allies/darkwing/idle4.ogg
sound/st_allies/darkwing/idle5.ogg
sound/st_allies/darkwing/idle6.ogg
sound/st_allies/darkwing/idle7.ogg
sound/st_allies/darkwing/idle8.ogg
sound/st_allies/darkwing/idle9.ogg
sound/st_allies/darkwing/kill0.ogg
sound/st_allies/darkwing/kill1.ogg
sound/st_allies/darkwing/kill2.ogg
sound/st_allies/darkwing/kill3.ogg
sound/st_allies/darkwing/kill4.ogg
sound/st_allies/darkwing/kill5.ogg
sound/st_allies/darkwing/kill6.ogg
sound/st_allies/darkwing/kill7.ogg
sound/st_allies/darkwing/kill8.ogg
sound/st_allies/darkwing/kill9.ogg
sound/st_allies/darkwing/mad0.ogg
sound/st_allies/darkwing/mad1.ogg
sound/st_allies/darkwing/monster0.ogg
sound/st_allies/darkwing/monster1.ogg
sound/st_allies/darkwing/mortal0.ogg
sound/st_allies/darkwing/mortal1.ogg
sound/st_allies/darkwing/mortal2.ogg
sound/st_allies/darkwing/ok0.ogg
sound/st_allies/darkwing/ok1.ogg
sound/st_allies/darkwing/ok2.ogg
sound/st_allies/darkwing/ok3.ogg
sound/st_allies/darkwing/ok4.ogg
sound/st_allies/darkwing/ok5.ogg
sound/st_allies/darkwing/ok6.ogg
sound/st_allies/darkwing/ok7.ogg
sound/st_allies/darkwing/ok8.ogg
sound/st_allies/darkwing/ok9.ogg
sound/st_allies/darkwing/pain1.ogg
sound/st_allies/darkwing/pain2.ogg
sound/st_allies/darkwing/pain3.ogg
sound/st_allies/darkwing/pain4.ogg
sound/st_allies/darkwing/pok0.ogg
sound/st_allies/darkwing/pok1.ogg
sound/st_allies/darkwing/pok2.ogg
sound/st_allies/darkwing/pok3.ogg
sound/st_allies/darkwing/quest0.ogg
sound/st_allies/darkwing/quest00.ogg
sound/st_allies/darkwing/quest01.ogg
sound/st_allies/darkwing/quest1.ogg
sound/st_allies/darkwing/quest2.ogg
sound/st_allies/darkwing/quest3.ogg
sound/st_allies/darkwing/quest4.ogg
sound/st_allies/darkwing/quest5.ogg
sound/st_allies/darkwing/scared0.ogg
sound/st_allies/darkwing/scared1.ogg
sound/st_allies/darkwing/shot0.ogg
sound/st_allies/darkwing/shot1.ogg
sound/st_allies/darkwing/shot2.ogg
sound/st_allies/darkwing/shot3.ogg
sound/st_allies/darkwing/shot5.ogg
sound/st_allies/darkwing/taunt0.ogg
sound/st_allies/darkwing/taunt1.ogg
sound/st_allies/darkwing/taunt2.ogg
sound/st_allies/darkwing/taunt3.ogg
sound/st_allies/darkwing/taunt4.ogg
sound/st_allies/darkwing/taunt5.ogg
sound/st_allies/darkwing/wait0.ogg
sound/st_allies/darkwing/wait1.ogg
sound/st_allies/darkwing/wait2.ogg
sound/st_allies/darkwing/wait3.ogg
sound/st_allies/darkwing/wound0.ogg
sound/st_allies/darkwing/wound1.ogg
sound/st_allies/darkwing/wound2.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_hs_c5_brad.ogg
sound/st_allies/sobrobo/sr_hs_c5_correct.ogg
sound/st_mission/bunkersiren.ogg
sound/st_mission/caralarm.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/events/hs_c4/hs_c5_background.ogg
sound/st_mission/events/hs_c4/hs_c5_battle.ogg
sound/st_mission/events/hs_c4/security_die.wav
sound/st_mission/events/hs_c4/stabbing.ogg
sound/st_mission/events/hs_c4/warp_out.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/hellambient.ogg
sound/st_mission/music/ambience06.ogg
sound/st_mission/music/hs_c5_music02.ogg
sound/st_mission/night.ogg
sound/st_mission/outdoorbattle.ogg
sound/st_mission/radio/hs_c5_backup.ogg
sound/st_mission/radio/hs_c5_civies.ogg
sound/st_mission/radio/hs_c5_copy.ogg
sound/st_mission/radio/hs_c5_evacuating.ogg
sound/st_mission/radio/hs_c5_oscar.ogg
sound/st_mission/teleport_in.ogg
sound/st_mission/teleport_out.ogg
sound/st_mission/truck3.ogg
sound/st_mission/truck_goes.ogg
sound/st_mission/tunnel_wind1.ogg
sound/st_mission/weapons/f2000.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_fire1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m4a1-fire.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/scar-fire.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/wa2000_shoot1.ogg
sound/st_mission/weapons/xm8-fire.ogg
sprites/c-tele1_red.spr
sprites/singularity/prtl/kz_exit1.spr
