// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
aomreal.wad
cars.wad
cs_office.wad
cs_siege.wad
hs.wad
hs2.wad
hs4.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/gonome/gonome_tyrant.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/hgrunt/mgrunt01.mdl
models/custom_monsters/hgrunt/mgrunt02.mdl
models/custom_monsters/hgrunt/mgrunt03.mdl
models/custom_monsters/pitdrone/smokedrone.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/tor/poss_rodney.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_doctor2.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/dead_hev2t.mdl
models/st_allies/dead_hevt.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor01.mdl
models/st_allies/nimblegrunt/ngrunt_opfor02.mdl
models/st_allies/nimblegrunt/ngrunt_opfor03.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_bio.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/biohazard_container.mdl
models/st_mission1/biohazard_container2.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/mex_ruined_house02.mdl
models/st_mission1/props/trash1.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/wrecked_car_brown.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/w_nyctophilia_dagger1.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/mercs/alert.wav
sound/custom_monsters/mercs/area.wav
sound/custom_monsters/mercs/ass.wav
sound/custom_monsters/mercs/babysitting.wav
sound/custom_monsters/mercs/backup.wav
sound/custom_monsters/mercs/bfeeling.wav
sound/custom_monsters/mercs/bogies.wav
sound/custom_monsters/mercs/charge.wav
sound/custom_monsters/mercs/check.wav
sound/custom_monsters/mercs/checkrecon.wav
sound/custom_monsters/mercs/chicken.wav
sound/custom_monsters/mercs/clear.wav
sound/custom_monsters/mercs/corners.wav
sound/custom_monsters/mercs/cover.wav
sound/custom_monsters/mercs/covering.wav
sound/custom_monsters/mercs/coverup.wav
sound/custom_monsters/mercs/critical.wav
sound/custom_monsters/mercs/current.wav
sound/custom_monsters/mercs/death1.wav
sound/custom_monsters/mercs/death2.wav
sound/custom_monsters/mercs/death3.wav
sound/custom_monsters/mercs/disney.wav
sound/custom_monsters/mercs/dogs.wav
sound/custom_monsters/mercs/down.wav
sound/custom_monsters/mercs/flank.wav
sound/custom_monsters/mercs/freaks.wav
sound/custom_monsters/mercs/fubar.wav
sound/custom_monsters/mercs/getsome.wav
sound/custom_monsters/mercs/go.wav
sound/custom_monsters/mercs/gr_pain1.wav
sound/custom_monsters/mercs/gr_pain2.wav
sound/custom_monsters/mercs/gr_pain3.wav
sound/custom_monsters/mercs/gr_pain4.wav
sound/custom_monsters/mercs/grenade.wav
sound/custom_monsters/mercs/hear.wav
sound/custom_monsters/mercs/hearsome.wav
sound/custom_monsters/mercs/hellosir.wav
sound/custom_monsters/mercs/hostiles.wav
sound/custom_monsters/mercs/incoming.wav
sound/custom_monsters/mercs/lost.wav
sound/custom_monsters/mercs/makeit.wav
sound/custom_monsters/mercs/marines.wav
sound/custom_monsters/mercs/mission.wav
sound/custom_monsters/mercs/mister.wav
sound/custom_monsters/mercs/move.wav
sound/custom_monsters/mercs/moveup.wav
sound/custom_monsters/mercs/no.wav
sound/custom_monsters/mercs/nothing.wav
sound/custom_monsters/mercs/now.wav
sound/custom_monsters/mercs/outof.wav
sound/custom_monsters/mercs/pain1.wav
sound/custom_monsters/mercs/pain2.wav
sound/custom_monsters/mercs/pain3.wav
sound/custom_monsters/mercs/pain4.wav
sound/custom_monsters/mercs/quiet.wav
sound/custom_monsters/mercs/rapidfire.wav
sound/custom_monsters/mercs/recon.wav
sound/custom_monsters/mercs/roger.wav
sound/custom_monsters/mercs/seensquad.wav
sound/custom_monsters/mercs/short.wav
sound/custom_monsters/mercs/sniper.wav
sound/custom_monsters/mercs/suppressing.wav
sound/custom_monsters/mercs/sweep.wav
sound/custom_monsters/mercs/tag.wav
sound/custom_monsters/mercs/take.wav
sound/custom_monsters/mercs/wantsome.wav
sound/custom_monsters/mercs/zone.wav
sound/custom_monsters/necroscasm/claw_miss1.wav
sound/custom_monsters/necroscasm/claw_miss2.wav
sound/custom_monsters/necroscasm/claw_strike1.wav
sound/custom_monsters/necroscasm/claw_strike2.wav
sound/custom_monsters/necroscasm/claw_strike3.wav
sound/custom_monsters/necroscasm/zo_alert10.wav
sound/custom_monsters/necroscasm/zo_alert20.wav
sound/custom_monsters/necroscasm/zo_alert30.wav
sound/custom_monsters/necroscasm/zo_attack1.wav
sound/custom_monsters/necroscasm/zo_attack2.wav
sound/custom_monsters/necroscasm/zo_idle1.wav
sound/custom_monsters/necroscasm/zo_idle2.wav
sound/custom_monsters/necroscasm/zo_idle3.wav
sound/custom_monsters/necroscasm/zo_idle4.wav
sound/custom_monsters/necroscasm/zo_pain1.wav
sound/custom_monsters/necroscasm/zo_pain2.wav
sound/custom_monsters/plagueskull/ps_float.wav
sound/custom_monsters/portal.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_mission/ambience1.wav
sound/st_mission/angelic_energy.wav
sound/st_mission/doors/bookshelf.wav
sound/st_mission/events/hs_c4/broadcast.wav
sound/st_mission/events/hs_c4/darkness_humming01.wav
sound/st_mission/events/hs_c4/darkness_humming02.wav
sound/st_mission/events/hs_c4/darkness_humming03.wav
sound/st_mission/events/hs_c4/darkness_humming04.wav
sound/st_mission/events/hs_c4/darkness_humming05.wav
sound/st_mission/events/hs_c4/distant_angel_shadows.wav
sound/st_mission/events/hs_c4/distant_angel_shoot.wav
sound/st_mission/events/hs_c4/distant_angel_warp.wav
sound/st_mission/events/hs_c4/distant_demon_attack.wav
sound/st_mission/events/hs_c4/distant_demon_dash.wav
sound/st_mission/events/hs_c4/distant_displace.wav
sound/st_mission/events/hs_c4/distant_explosion.wav
sound/st_mission/flareidle.wav
sound/st_mission/holyeffect.wav
sound/st_mission/largebeamstart1.wav
sound/st_mission/music/hs_c4_ambient.ogg
sound/st_mission/outdoorbattle_inside.wav
sound/st_mission/portal_charge.wav
sound/st_mission/radio/hs_c4_adinnah.wav
sound/st_mission/radio/hs_c4_angels.wav
sound/st_mission/radio/hs_c4_dagger.wav
sound/st_mission/radio/hs_c4_hearme.wav
sound/st_mission/radio/hs_c4_roger.wav
sound/st_mission/radio/hs_c4_stfu.wav
sound/st_mission/radio/hs_c4_wtf.wav
sound/st_mission/radio/hs_c4_yessir.wav
sound/st_mission/rain1.wav
sound/st_mission/rain2.wav
sound/st_mission/rain_inside.wav
sound/st_mission/rain_window.wav
sound/st_mission/thunder1.wav
sound/st_mission/thunder2.wav
sound/st_mission/thunder3.wav
sound/st_mission/thunder4.wav
sound/st_mission/weapons/g3_fire1.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sprites/c-tele1_blu.spr
sprites/kezaeiv/prtl/kz_exit1.spr
