// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
bigcity2.wad
cs_assault.wad
cs_assault_halloween.wad
cs_office.wad
cs_siege.wad
fi.wad
hle.wad
hospital.wad
hs2.wad
models/custom_monsters/agrunt/agrunt_snow.mdl
models/custom_monsters/agrunt/paralyzed_subject.mdl
models/custom_monsters/alienslave/mage.mdl
models/custom_monsters/bullsquid/snowsquid.mdl
models/custom_monsters/bullsquid/twitchersquid.mdl
models/custom_monsters/gonome/mutant_runner.mdl
models/custom_monsters/hgrunt/haunted_arctic_sgrunt.mdl
models/custom_monsters/hgrunt/haunted_ngrunt.mdl
models/custom_monsters/hgrunt/haunted_security_ar.mdl
models/custom_monsters/pitdrone/frost_slasher.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/sci_poss.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/twitcher.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_construct.mdl
models/custom_monsters/zombie/zombie_crowbar.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/st_allies/arctic_sgrunt.mdl
models/st_allies/construction.mdl
models/st_allies/dead_hev.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/scientist.mdl
models/st_allies/scientist_female.mdl
models/st_allies/security_ar.mdl
models/st_mission1/flag_empire.mdl
models/st_mission1/props/af_s_nec_wires_sm_thinwire13.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/pipe1_es.mdl
models/st_mission1/props/wall_ele_shield_double.mdl
models/st_mission1/scientist.mdl
models/st_mission1/snowflake.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/crimson/v_357.mdl
models/st_mission1/weapons_classic/crimson/v_9mmar.mdl
models/st_mission1/weapons_classic/crimson/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/crimson/v_crossbow.mdl
models/st_mission1/weapons_classic/crimson/v_crowbar.mdl
models/st_mission1/weapons_classic/crimson/v_displacer.mdl
models/st_mission1/weapons_classic/crimson/v_eagle.mdl
models/st_mission1/weapons_classic/crimson/v_egon.mdl
models/st_mission1/weapons_classic/crimson/v_gauss.mdl
models/st_mission1/weapons_classic/crimson/v_grenade.mdl
models/st_mission1/weapons_classic/crimson/v_m16a2.mdl
models/st_mission1/weapons_classic/crimson/v_m40a1.mdl
models/st_mission1/weapons_classic/crimson/v_medkit.mdl
models/st_mission1/weapons_classic/crimson/v_minigun.mdl
models/st_mission1/weapons_classic/crimson/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/crimson/v_rpg.mdl
models/st_mission1/weapons_classic/crimson/v_satchel.mdl
models/st_mission1/weapons_classic/crimson/v_satchel_radio.mdl
models/st_mission1/weapons_classic/crimson/v_saw.mdl
models/st_mission1/weapons_classic/crimson/v_shotgun.mdl
models/st_mission1/weapons_classic/crimson/v_spore_launcher.mdl
models/st_mission1/weapons_classic/crimson/v_squeak.mdl
models/st_mission1/weapons_classic/crimson/v_tripmine.mdl
models/st_mission1/weapons_classic/crimson/v_uzi.mdl
models/st_mission1/weapons_classic/p_bgrap.mdl
models/st_mission1/weapons_classic/p_displacer.mdl
models/st_mission1/weapons_classic/v_bgrap.mdl
models/st_mission1/weapons_classic/w_bgrap.mdl
models/st_mission1/weapons_classic/w_displacer.mdl
models/st_mission1/weapons_classic/w_gauss.mdl
silenthill.wad
sound/custom_monsters/glitchzombie/claw_miss1.ogg
sound/custom_monsters/glitchzombie/claw_miss2.ogg
sound/custom_monsters/glitchzombie/claw_strike1.ogg
sound/custom_monsters/glitchzombie/claw_strike2.ogg
sound/custom_monsters/glitchzombie/claw_strike3.ogg
sound/custom_monsters/glitchzombie/zo_alert10.ogg
sound/custom_monsters/glitchzombie/zo_alert20.ogg
sound/custom_monsters/glitchzombie/zo_alert30.ogg
sound/custom_monsters/glitchzombie/zo_attack1.ogg
sound/custom_monsters/glitchzombie/zo_attack2.ogg
sound/custom_monsters/glitchzombie/zo_idle1.ogg
sound/custom_monsters/glitchzombie/zo_idle2.ogg
sound/custom_monsters/glitchzombie/zo_idle3.ogg
sound/custom_monsters/glitchzombie/zo_idle4.ogg
sound/custom_monsters/glitchzombie/zo_pain1.ogg
sound/custom_monsters/glitchzombie/zo_pain2.ogg
sound/custom_monsters/mutantrunner/mr_alert2.ogg
sound/custom_monsters/mutantrunner/mr_alert3.ogg
sound/custom_monsters/mutantrunner/mr_attack.ogg
sound/custom_monsters/mutantrunner/mr_die1.ogg
sound/custom_monsters/mutantrunner/mr_die2.ogg
sound/custom_monsters/mutantrunner/mr_hit1.ogg
sound/custom_monsters/mutantrunner/mr_hit2.ogg
sound/custom_monsters/mutantrunner/mr_idle1.ogg
sound/custom_monsters/mutantrunner/mr_idle2.ogg
sound/custom_monsters/mutantrunner/mr_pain1.ogg
sound/custom_monsters/mutantrunner/mr_pain2.ogg
sound/custom_monsters/paralyzed_subject/ps_alert1.ogg
sound/custom_monsters/paralyzed_subject/ps_alert3.ogg
sound/custom_monsters/paralyzed_subject/ps_alert4.ogg
sound/custom_monsters/paralyzed_subject/ps_attack1.ogg
sound/custom_monsters/paralyzed_subject/ps_attack2.ogg
sound/custom_monsters/paralyzed_subject/ps_attack3.ogg
sound/custom_monsters/paralyzed_subject/ps_die1.ogg
sound/custom_monsters/paralyzed_subject/ps_die4.ogg
sound/custom_monsters/paralyzed_subject/ps_die5.ogg
sound/custom_monsters/paralyzed_subject/ps_idle1.ogg
sound/custom_monsters/paralyzed_subject/ps_idle2.ogg
sound/custom_monsters/paralyzed_subject/ps_idle3.ogg
sound/custom_monsters/paralyzed_subject/ps_idle4.ogg
sound/custom_monsters/paralyzed_subject/ps_pain1.ogg
sound/custom_monsters/paralyzed_subject/ps_pain2.ogg
sound/custom_monsters/paralyzed_subject/ps_pain3.ogg
sound/custom_monsters/paralyzed_subject/ps_pain4.ogg
sound/custom_monsters/paralyzed_subject/ps_pain5.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/voidfold_cannon_charge.ogg
sound/hs/weapons/voidfold_cannon_charge2.ogg
sound/hs/weapons/voidfold_cannon_fire.ogg
sound/hs/weapons/voidfold_cannon_impact.ogg
sound/hs/weapons/voidfold_cannon_playertp.ogg
sound/hs/weapons/voidfold_cannon_selftp.ogg
sound/hs/weapons/voidfold_cannon_start.ogg
sound/hs/weapons/voidfold_cannon_teleport.ogg
sound/oghs/misc/cp02_03.mp3
sound/scientist/am_typing.wav
sound/singularity/misc/teleport.wav
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/sobrobo/sr_hs_d3_airstrike.ogg
sound/st_mission/22noice2.ogg
sound/st_mission/airdropjet1.ogg
sound/st_mission/airraid.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/helicopter13.ogg
sound/st_mission/music/background/c/c3_amb_facility01.ogg
sound/st_mission/music/background/c/c3_amb_facility02.ogg
sound/st_mission/music/background/c/c3_amb_facility03.ogg
sound/st_mission/music/background/c/c3_amb_facility04.ogg
sound/st_mission/music/background/c/c3_amb_facility05.ogg
sound/st_mission/music/background/c/c3_amb_facility06.ogg
sound/st_mission/outdoorbattle.ogg
sound/st_mission/outdoorbattle_inside.ogg
sound/st_mission/scary_wind1.ogg
sound/st_mission/teleport_out.ogg
sound/st_mission/tunnel_wind1.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/arctic_incident/ws_snow_fx.spr
sprites/singularity/prtl/kz_exit1.spr
