// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/mil_crategibs.mdl
9.wad
aomreal.wad
cars.wad
cs_office.wad
cs_siege.wad
hs.wad
hs2.wad
hs4.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/gonome/gonome_tyrant.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/pitdrone/smokedrone.mdl
models/custom_monsters/stukabat/plague_skull.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/tor/poss_rodney.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_doctor2.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_bio.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/biohazard_container.mdl
models/st_mission1/biohazard_container2.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/mex_ruined_house02.mdl
models/st_mission1/props/trash1.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/wrecked_car_brown.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/w_nyctophilia_dagger1.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/mercs/alert.ogg
sound/custom_monsters/mercs/area.ogg
sound/custom_monsters/mercs/ass.ogg
sound/custom_monsters/mercs/babysitting.ogg
sound/custom_monsters/mercs/backup.ogg
sound/custom_monsters/mercs/bfeeling.ogg
sound/custom_monsters/mercs/bogies.ogg
sound/custom_monsters/mercs/charge.ogg
sound/custom_monsters/mercs/check.ogg
sound/custom_monsters/mercs/checkrecon.ogg
sound/custom_monsters/mercs/chicken.ogg
sound/custom_monsters/mercs/clear.ogg
sound/custom_monsters/mercs/corners.ogg
sound/custom_monsters/mercs/cover.ogg
sound/custom_monsters/mercs/covering.ogg
sound/custom_monsters/mercs/coverup.ogg
sound/custom_monsters/mercs/critical.ogg
sound/custom_monsters/mercs/current.ogg
sound/custom_monsters/mercs/death1.ogg
sound/custom_monsters/mercs/death2.ogg
sound/custom_monsters/mercs/death3.ogg
sound/custom_monsters/mercs/disney.ogg
sound/custom_monsters/mercs/dogs.ogg
sound/custom_monsters/mercs/down.ogg
sound/custom_monsters/mercs/flank.ogg
sound/custom_monsters/mercs/freaks.ogg
sound/custom_monsters/mercs/fubar.ogg
sound/custom_monsters/mercs/getsome.ogg
sound/custom_monsters/mercs/go.ogg
sound/custom_monsters/mercs/gr_pain1.ogg
sound/custom_monsters/mercs/gr_pain2.ogg
sound/custom_monsters/mercs/gr_pain3.ogg
sound/custom_monsters/mercs/gr_pain4.ogg
sound/custom_monsters/mercs/grenade.ogg
sound/custom_monsters/mercs/hear.ogg
sound/custom_monsters/mercs/hearsome.ogg
sound/custom_monsters/mercs/hellosir.ogg
sound/custom_monsters/mercs/hostiles.ogg
sound/custom_monsters/mercs/incoming.ogg
sound/custom_monsters/mercs/lost.ogg
sound/custom_monsters/mercs/makeit.ogg
sound/custom_monsters/mercs/marines.ogg
sound/custom_monsters/mercs/mission.ogg
sound/custom_monsters/mercs/mister.ogg
sound/custom_monsters/mercs/move.ogg
sound/custom_monsters/mercs/moveup.ogg
sound/custom_monsters/mercs/no.ogg
sound/custom_monsters/mercs/nothing.ogg
sound/custom_monsters/mercs/now.ogg
sound/custom_monsters/mercs/outof.ogg
sound/custom_monsters/mercs/pain1.ogg
sound/custom_monsters/mercs/pain2.ogg
sound/custom_monsters/mercs/pain3.ogg
sound/custom_monsters/mercs/pain4.ogg
sound/custom_monsters/mercs/quiet.ogg
sound/custom_monsters/mercs/rapidfire.ogg
sound/custom_monsters/mercs/recon.ogg
sound/custom_monsters/mercs/roger.ogg
sound/custom_monsters/mercs/seensquad.ogg
sound/custom_monsters/mercs/short.ogg
sound/custom_monsters/mercs/sniper.ogg
sound/custom_monsters/mercs/suppressing.ogg
sound/custom_monsters/mercs/sweep.ogg
sound/custom_monsters/mercs/tag.ogg
sound/custom_monsters/mercs/take.ogg
sound/custom_monsters/mercs/wantsome.ogg
sound/custom_monsters/mercs/zone.ogg
sound/custom_monsters/necroscasm/claw_miss1.ogg
sound/custom_monsters/necroscasm/claw_miss2.ogg
sound/custom_monsters/necroscasm/claw_strike1.ogg
sound/custom_monsters/necroscasm/claw_strike2.ogg
sound/custom_monsters/necroscasm/claw_strike3.ogg
sound/custom_monsters/necroscasm/zo_alert10.ogg
sound/custom_monsters/necroscasm/zo_alert20.ogg
sound/custom_monsters/necroscasm/zo_alert30.ogg
sound/custom_monsters/necroscasm/zo_attack1.ogg
sound/custom_monsters/necroscasm/zo_attack2.ogg
sound/custom_monsters/necroscasm/zo_idle1.ogg
sound/custom_monsters/necroscasm/zo_idle2.ogg
sound/custom_monsters/necroscasm/zo_idle3.ogg
sound/custom_monsters/necroscasm/zo_idle4.ogg
sound/custom_monsters/necroscasm/zo_pain1.ogg
sound/custom_monsters/necroscasm/zo_pain2.ogg
sound/custom_monsters/plagueskull/ps_float.ogg
sound/custom_monsters/portal.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_mission/ambience1.ogg
sound/st_mission/angelic_energy.ogg
sound/st_mission/doors/bookshelf.ogg
sound/st_mission/events/hs_c4/broadcast.ogg
sound/st_mission/events/hs_c4/darkness_humming01.ogg
sound/st_mission/events/hs_c4/darkness_humming02.ogg
sound/st_mission/events/hs_c4/darkness_humming03.ogg
sound/st_mission/events/hs_c4/darkness_humming04.ogg
sound/st_mission/events/hs_c4/darkness_humming05.ogg
sound/st_mission/events/hs_c4/distant_angel_shadows.ogg
sound/st_mission/events/hs_c4/distant_angel_shoot.ogg
sound/st_mission/events/hs_c4/distant_angel_warp.ogg
sound/st_mission/events/hs_c4/distant_demon_attack.ogg
sound/st_mission/events/hs_c4/distant_demon_dash.ogg
sound/st_mission/events/hs_c4/distant_displace.ogg
sound/st_mission/events/hs_c4/distant_explosion.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/holyeffect.ogg
sound/st_mission/largebeamstart1.ogg
sound/st_mission/music/hs_c4_ambient.ogg
sound/st_mission/outdoorbattle_inside.ogg
sound/st_mission/portal_charge.ogg
sound/st_mission/radio/hs_c4_adinnah.ogg
sound/st_mission/radio/hs_c4_angels.ogg
sound/st_mission/radio/hs_c4_dagger.ogg
sound/st_mission/radio/hs_c4_hearme.ogg
sound/st_mission/radio/hs_c4_roger.ogg
sound/st_mission/radio/hs_c4_stfu.ogg
sound/st_mission/radio/hs_c4_wtf.ogg
sound/st_mission/radio/hs_c4_yessir.ogg
sound/st_mission/rain1.ogg
sound/st_mission/rain2.ogg
sound/st_mission/rain_inside.ogg
sound/st_mission/rain_window.ogg
sound/st_mission/thunder1.ogg
sound/st_mission/thunder2.ogg
sound/st_mission/thunder3.ogg
sound/st_mission/thunder4.ogg
sound/st_mission/weapons/g3_fire1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/c-tele1_blu.spr
sprites/singularity/prtl/kz_exit1.spr
