// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
bigcity2.wad
cars.wad
cs_assault.wad
cs_office.wad
hs4.wad
kz-kargo.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/alienslave/blueslave.mdl
models/custom_monsters/alienslave/blueslave01.mdl
models/custom_monsters/alienslave/blueslave02.mdl
models/custom_monsters/alienslave/blueslavet.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/babygarg/evoluted_skeleton.mdl
models/custom_monsters/gonome/skull_hunter.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/hgrunt/mgrunt01.mdl
models/custom_monsters/hgrunt/mgrunt02.mdl
models/custom_monsters/hgrunt/mgrunt03.mdl
models/custom_monsters/hgrunt/possesed_survivor.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/corrupted_experiment_clone.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/slasher_ghost01.mdl
models/custom_monsters/zombie/slasher_ghost02.mdl
models/custom_monsters/zombie/slasher_ghostt.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/szombiet.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie_scguard.mdl
models/st_allies/civilian.mdl
models/st_allies/crimsoncommando/crimson2.mdl
models/st_allies/crimsoncommando/crimson201.mdl
models/st_allies/crimsoncommando/crimson202.mdl
models/st_allies/crimsoncommando/crimson203.mdl
models/st_allies/crimsoncommando/crimson4.mdl
models/st_allies/crimsoncommando/crimson401.mdl
models/st_allies/crimsoncommando/crimson402.mdl
models/st_allies/crimsoncommando/crimson403.mdl
models/st_allies/crimsoncommando/crimson_hev.mdl
models/st_allies/darkwing.mdl
models/st_allies/darkwing01.mdl
models/st_allies/darkwing02.mdl
models/st_allies/darkwing03.mdl
models/st_allies/nimblegrunt/ngrunt_opfor3.mdl
models/st_allies/nimblegrunt/ngrunt_opfor301.mdl
models/st_allies/nimblegrunt/ngrunt_opfor302.mdl
models/st_allies/nimblegrunt/ngrunt_opfor303.mdl
models/st_allies/plinky_assasin.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/props/2_wrecked_hatchback_grey.mdl
models/st_mission1/props/cheap_forklift.mdl
models/st_mission1/props/muscle_car_grey.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
siege_apc.wad
sound/custom_monsters/cec/cec_alert10.wav
sound/custom_monsters/cec/cec_alert20.wav
sound/custom_monsters/cec/cec_alert30.wav
sound/custom_monsters/cec/cec_attack1.wav
sound/custom_monsters/cec/cec_attack2.wav
sound/custom_monsters/cec/cec_idle1.wav
sound/custom_monsters/cec/cec_idle2.wav
sound/custom_monsters/cec/cec_idle3.wav
sound/custom_monsters/cec/cec_pain1.wav
sound/custom_monsters/cec/cec_pain2.wav
sound/custom_monsters/evoskeleton/evo_alert1.wav
sound/custom_monsters/evoskeleton/evo_alert2.wav
sound/custom_monsters/evoskeleton/evo_alert3.wav
sound/custom_monsters/evoskeleton/evo_attack1.wav
sound/custom_monsters/evoskeleton/evo_attack2.wav
sound/custom_monsters/evoskeleton/evo_attack3.wav
sound/custom_monsters/evoskeleton/evo_pain1.wav
sound/custom_monsters/evoskeleton/evo_pain2.wav
sound/custom_monsters/guns/shotgun/sbarrel1.wav
sound/custom_monsters/guns/smg/hks1.wav
sound/custom_monsters/guns/smg/hks2.wav
sound/custom_monsters/guns/smg/hks3.wav
sound/custom_monsters/mercs/alert.wav
sound/custom_monsters/mercs/area.wav
sound/custom_monsters/mercs/ass.wav
sound/custom_monsters/mercs/babysitting.wav
sound/custom_monsters/mercs/backup.wav
sound/custom_monsters/mercs/bfeeling.wav
sound/custom_monsters/mercs/bogies.wav
sound/custom_monsters/mercs/charge.wav
sound/custom_monsters/mercs/check.wav
sound/custom_monsters/mercs/checkrecon.wav
sound/custom_monsters/mercs/chicken.wav
sound/custom_monsters/mercs/clear.wav
sound/custom_monsters/mercs/corners.wav
sound/custom_monsters/mercs/cover.wav
sound/custom_monsters/mercs/covering.wav
sound/custom_monsters/mercs/coverup.wav
sound/custom_monsters/mercs/critical.wav
sound/custom_monsters/mercs/current.wav
sound/custom_monsters/mercs/death1.wav
sound/custom_monsters/mercs/death2.wav
sound/custom_monsters/mercs/death3.wav
sound/custom_monsters/mercs/disney.wav
sound/custom_monsters/mercs/dogs.wav
sound/custom_monsters/mercs/down.wav
sound/custom_monsters/mercs/flank.wav
sound/custom_monsters/mercs/freaks.wav
sound/custom_monsters/mercs/fubar.wav
sound/custom_monsters/mercs/getsome.wav
sound/custom_monsters/mercs/go.wav
sound/custom_monsters/mercs/gr_pain1.wav
sound/custom_monsters/mercs/gr_pain2.wav
sound/custom_monsters/mercs/gr_pain3.wav
sound/custom_monsters/mercs/gr_pain4.wav
sound/custom_monsters/mercs/grenade.wav
sound/custom_monsters/mercs/hear.wav
sound/custom_monsters/mercs/hearsome.wav
sound/custom_monsters/mercs/hellosir.wav
sound/custom_monsters/mercs/hostiles.wav
sound/custom_monsters/mercs/incoming.wav
sound/custom_monsters/mercs/lost.wav
sound/custom_monsters/mercs/makeit.wav
sound/custom_monsters/mercs/marines.wav
sound/custom_monsters/mercs/mission.wav
sound/custom_monsters/mercs/mister.wav
sound/custom_monsters/mercs/move.wav
sound/custom_monsters/mercs/moveup.wav
sound/custom_monsters/mercs/no.wav
sound/custom_monsters/mercs/nothing.wav
sound/custom_monsters/mercs/now.wav
sound/custom_monsters/mercs/outof.wav
sound/custom_monsters/mercs/pain1.wav
sound/custom_monsters/mercs/pain2.wav
sound/custom_monsters/mercs/pain3.wav
sound/custom_monsters/mercs/pain4.wav
sound/custom_monsters/mercs/quiet.wav
sound/custom_monsters/mercs/rapidfire.wav
sound/custom_monsters/mercs/recon.wav
sound/custom_monsters/mercs/roger.wav
sound/custom_monsters/mercs/seensquad.wav
sound/custom_monsters/mercs/short.wav
sound/custom_monsters/mercs/sniper.wav
sound/custom_monsters/mercs/suppressing.wav
sound/custom_monsters/mercs/sweep.wav
sound/custom_monsters/mercs/tag.wav
sound/custom_monsters/mercs/take.wav
sound/custom_monsters/mercs/wantsome.wav
sound/custom_monsters/mercs/zone.wav
sound/custom_monsters/slasherghost/sg_alert1.wav
sound/custom_monsters/slasherghost/sg_alert2.wav
sound/custom_monsters/slasherghost/sg_alert3.wav
sound/custom_monsters/slasherghost/sg_attack1.wav
sound/custom_monsters/slasherghost/sg_attack2.wav
sound/custom_monsters/slasherghost/sg_miss1.wav
sound/custom_monsters/slasherghost/sg_miss2.wav
sound/custom_monsters/slasherghost/sg_pain1.wav
sound/custom_monsters/slasherghost/sg_pain2.wav
sound/custom_monsters/slasherghost/sg_slash1.wav
sound/custom_monsters/slasherghost/sg_slash2.wav
sound/custom_monsters/slasherghost/sg_slash3.wav
sound/custom_monsters/slasherghost/sg_voice1.wav
sound/custom_monsters/slasherghost/sg_voice2.wav
sound/custom_monsters/slasherghost/sg_voice3.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_allies/crimson_commando/alert.wav
sound/st_allies/crimson_commando/area.wav
sound/st_allies/crimson_commando/ass.wav
sound/st_allies/crimson_commando/babysitting.wav
sound/st_allies/crimson_commando/backup.wav
sound/st_allies/crimson_commando/bfeeling.wav
sound/st_allies/crimson_commando/bogies.wav
sound/st_allies/crimson_commando/charge.wav
sound/st_allies/crimson_commando/check.wav
sound/st_allies/crimson_commando/checkrecon.wav
sound/st_allies/crimson_commando/chicken.wav
sound/st_allies/crimson_commando/clear.wav
sound/st_allies/crimson_commando/command.wav
sound/st_allies/crimson_commando/corners.wav
sound/st_allies/crimson_commando/corporal.wav
sound/st_allies/crimson_commando/corporal_01.wav
sound/st_allies/crimson_commando/cover.wav
sound/st_allies/crimson_commando/covering.wav
sound/st_allies/crimson_commando/coverup.wav
sound/st_allies/crimson_commando/current.wav
sound/st_allies/crimson_commando/damage.wav
sound/st_allies/crimson_commando/death1.wav
sound/st_allies/crimson_commando/death2.wav
sound/st_allies/crimson_commando/death3.wav
sound/st_allies/crimson_commando/disney.wav
sound/st_allies/crimson_commando/dogs.wav
sound/st_allies/crimson_commando/down.wav
sound/st_allies/crimson_commando/flank.wav
sound/st_allies/crimson_commando/freaks.wav
sound/st_allies/crimson_commando/friendly.wav
sound/st_allies/crimson_commando/fubar.wav
sound/st_allies/crimson_commando/getsome.wav
sound/st_allies/crimson_commando/go.wav
sound/st_allies/crimson_commando/gotit.wav
sound/st_allies/crimson_commando/gr_pain1.wav
sound/st_allies/crimson_commando/gr_pain2.wav
sound/st_allies/crimson_commando/gr_pain3.wav
sound/st_allies/crimson_commando/gr_pain4.wav
sound/st_allies/crimson_commando/grenade.wav
sound/st_allies/crimson_commando/guard.wav
sound/st_allies/crimson_commando/guardduty.wav
sound/st_allies/crimson_commando/hellosir.wav
sound/st_allies/crimson_commando/hellout.wav
sound/st_allies/crimson_commando/hitbad.wav
sound/st_allies/crimson_commando/hostiles.wav
sound/st_allies/crimson_commando/imhit.wav
sound/st_allies/crimson_commando/incoming.wav
sound/st_allies/crimson_commando/lost.wav
sound/st_allies/crimson_commando/marines.wav
sound/st_allies/crimson_commando/mission.wav
sound/st_allies/crimson_commando/mister.wav
sound/st_allies/crimson_commando/move.wav
sound/st_allies/crimson_commando/moveup.wav
sound/st_allies/crimson_commando/moving.wav
sound/st_allies/crimson_commando/no.wav
sound/st_allies/crimson_commando/notfail.wav
sound/st_allies/crimson_commando/now.wav
sound/st_allies/crimson_commando/oneshot.wav
sound/st_allies/crimson_commando/orders.wav
sound/st_allies/crimson_commando/outof.wav
sound/st_allies/crimson_commando/pain1.wav
sound/st_allies/crimson_commando/pain2.wav
sound/st_allies/crimson_commando/pain3.wav
sound/st_allies/crimson_commando/pain4.wav
sound/st_allies/crimson_commando/quiet.wav
sound/st_allies/crimson_commando/rapidfire.wav
sound/st_allies/crimson_commando/recon.wav
sound/st_allies/crimson_commando/right.wav
sound/st_allies/crimson_commando/roger.wav
sound/st_allies/crimson_commando/scout.wav
sound/st_allies/crimson_commando/secure.wav
sound/st_allies/crimson_commando/seensquad.wav
sound/st_allies/crimson_commando/short.wav
sound/st_allies/crimson_commando/six.wav
sound/st_allies/crimson_commando/sniper.wav
sound/st_allies/crimson_commando/suppressing.wav
sound/st_allies/crimson_commando/sweep.wav
sound/st_allies/crimson_commando/tag.wav
sound/st_allies/crimson_commando/take.wav
sound/st_allies/crimson_commando/talking.wav
sound/st_allies/crimson_commando/wantsome.wav
sound/st_allies/crimson_commando/watchfire.wav
sound/st_allies/crimson_commando/watchit.wav
sound/st_allies/crimson_commando/yes.wav
sound/st_allies/crimson_commando/zone.wav
sound/st_allies/darkwing/alert0.wav
sound/st_allies/darkwing/alert1.wav
sound/st_allies/darkwing/alert2.wav
sound/st_allies/darkwing/alert3.wav
sound/st_allies/darkwing/answer0.wav
sound/st_allies/darkwing/answer1.wav
sound/st_allies/darkwing/answer2.wav
sound/st_allies/darkwing/charge0.wav
sound/st_allies/darkwing/charge1.wav
sound/st_allies/darkwing/charge2.wav
sound/st_allies/darkwing/check0.wav
sound/st_allies/darkwing/check1.wav
sound/st_allies/darkwing/clear0.wav
sound/st_allies/darkwing/clear1.wav
sound/st_allies/darkwing/cover0.wav
sound/st_allies/darkwing/cover1.wav
sound/st_allies/darkwing/cover2.wav
sound/st_allies/darkwing/death1.wav
sound/st_allies/darkwing/death2.wav
sound/st_allies/darkwing/death3.wav
sound/st_allies/darkwing/dw_c5_checkout.wav
sound/st_allies/darkwing/dw_c5_door.wav
sound/st_allies/darkwing/dw_c5_hello.wav
sound/st_allies/darkwing/dw_c5_outside.wav
sound/st_allies/darkwing/dw_c5_shit.wav
sound/st_allies/darkwing/dw_c5_stupid.wav
sound/st_allies/darkwing/gren0.wav
sound/st_allies/darkwing/gren1.wav
sound/st_allies/darkwing/hello0.wav
sound/st_allies/darkwing/hello1.wav
sound/st_allies/darkwing/hello2.wav
sound/st_allies/darkwing/idle0.wav
sound/st_allies/darkwing/idle1.wav
sound/st_allies/darkwing/idle10.wav
sound/st_allies/darkwing/idle11.wav
sound/st_allies/darkwing/idle12.wav
sound/st_allies/darkwing/idle2.wav
sound/st_allies/darkwing/idle3.wav
sound/st_allies/darkwing/idle4.wav
sound/st_allies/darkwing/idle5.wav
sound/st_allies/darkwing/idle6.wav
sound/st_allies/darkwing/idle7.wav
sound/st_allies/darkwing/idle8.wav
sound/st_allies/darkwing/idle9.wav
sound/st_allies/darkwing/kill0.wav
sound/st_allies/darkwing/kill1.wav
sound/st_allies/darkwing/kill2.wav
sound/st_allies/darkwing/kill3.wav
sound/st_allies/darkwing/kill4.wav
sound/st_allies/darkwing/kill5.wav
sound/st_allies/darkwing/kill6.wav
sound/st_allies/darkwing/kill7.wav
sound/st_allies/darkwing/kill8.wav
sound/st_allies/darkwing/kill9.wav
sound/st_allies/darkwing/mad0.wav
sound/st_allies/darkwing/mad1.wav
sound/st_allies/darkwing/monster0.wav
sound/st_allies/darkwing/monster1.wav
sound/st_allies/darkwing/mortal0.wav
sound/st_allies/darkwing/mortal1.wav
sound/st_allies/darkwing/mortal2.wav
sound/st_allies/darkwing/ok0.wav
sound/st_allies/darkwing/ok1.wav
sound/st_allies/darkwing/ok2.wav
sound/st_allies/darkwing/ok3.wav
sound/st_allies/darkwing/ok4.wav
sound/st_allies/darkwing/ok5.wav
sound/st_allies/darkwing/ok6.wav
sound/st_allies/darkwing/ok7.wav
sound/st_allies/darkwing/ok8.wav
sound/st_allies/darkwing/ok9.wav
sound/st_allies/darkwing/pain1.wav
sound/st_allies/darkwing/pain2.wav
sound/st_allies/darkwing/pain3.wav
sound/st_allies/darkwing/pain4.wav
sound/st_allies/darkwing/pok0.wav
sound/st_allies/darkwing/pok1.wav
sound/st_allies/darkwing/pok2.wav
sound/st_allies/darkwing/pok3.wav
sound/st_allies/darkwing/quest0.wav
sound/st_allies/darkwing/quest00.wav
sound/st_allies/darkwing/quest01.wav
sound/st_allies/darkwing/quest1.wav
sound/st_allies/darkwing/quest2.wav
sound/st_allies/darkwing/quest3.wav
sound/st_allies/darkwing/quest4.wav
sound/st_allies/darkwing/quest5.wav
sound/st_allies/darkwing/scared0.wav
sound/st_allies/darkwing/scared1.wav
sound/st_allies/darkwing/shot0.wav
sound/st_allies/darkwing/shot1.wav
sound/st_allies/darkwing/shot2.wav
sound/st_allies/darkwing/shot3.wav
sound/st_allies/darkwing/shot5.wav
sound/st_allies/darkwing/taunt0.wav
sound/st_allies/darkwing/taunt1.wav
sound/st_allies/darkwing/taunt2.wav
sound/st_allies/darkwing/taunt3.wav
sound/st_allies/darkwing/taunt4.wav
sound/st_allies/darkwing/taunt5.wav
sound/st_allies/darkwing/wait0.wav
sound/st_allies/darkwing/wait1.wav
sound/st_allies/darkwing/wait2.wav
sound/st_allies/darkwing/wait3.wav
sound/st_allies/darkwing/wound0.wav
sound/st_allies/darkwing/wound1.wav
sound/st_allies/darkwing/wound2.wav
sound/st_allies/nimble_grunt/alert.wav
sound/st_allies/nimble_grunt/area.wav
sound/st_allies/nimble_grunt/ass.wav
sound/st_allies/nimble_grunt/babysitting.wav
sound/st_allies/nimble_grunt/backup.wav
sound/st_allies/nimble_grunt/bfeeling.wav
sound/st_allies/nimble_grunt/bogies.wav
sound/st_allies/nimble_grunt/charge.wav
sound/st_allies/nimble_grunt/check.wav
sound/st_allies/nimble_grunt/checkrecon.wav
sound/st_allies/nimble_grunt/chicken.wav
sound/st_allies/nimble_grunt/clear.wav
sound/st_allies/nimble_grunt/command.wav
sound/st_allies/nimble_grunt/corners.wav
sound/st_allies/nimble_grunt/corporal.wav
sound/st_allies/nimble_grunt/corporal_01.wav
sound/st_allies/nimble_grunt/cover.wav
sound/st_allies/nimble_grunt/covering.wav
sound/st_allies/nimble_grunt/coverup.wav
sound/st_allies/nimble_grunt/current.wav
sound/st_allies/nimble_grunt/damage.wav
sound/st_allies/nimble_grunt/death1.wav
sound/st_allies/nimble_grunt/death2.wav
sound/st_allies/nimble_grunt/death3.wav
sound/st_allies/nimble_grunt/disney.wav
sound/st_allies/nimble_grunt/dogs.wav
sound/st_allies/nimble_grunt/down.wav
sound/st_allies/nimble_grunt/flank.wav
sound/st_allies/nimble_grunt/freaks.wav
sound/st_allies/nimble_grunt/friendly.wav
sound/st_allies/nimble_grunt/fubar.wav
sound/st_allies/nimble_grunt/getsome.wav
sound/st_allies/nimble_grunt/go.wav
sound/st_allies/nimble_grunt/gotit.wav
sound/st_allies/nimble_grunt/gr_pain1.wav
sound/st_allies/nimble_grunt/gr_pain2.wav
sound/st_allies/nimble_grunt/gr_pain3.wav
sound/st_allies/nimble_grunt/gr_pain4.wav
sound/st_allies/nimble_grunt/grenade.wav
sound/st_allies/nimble_grunt/guard.wav
sound/st_allies/nimble_grunt/guardduty.wav
sound/st_allies/nimble_grunt/hellosir.wav
sound/st_allies/nimble_grunt/hellout.wav
sound/st_allies/nimble_grunt/hitbad.wav
sound/st_allies/nimble_grunt/hostiles.wav
sound/st_allies/nimble_grunt/imhit.wav
sound/st_allies/nimble_grunt/incoming.wav
sound/st_allies/nimble_grunt/lost.wav
sound/st_allies/nimble_grunt/marines.wav
sound/st_allies/nimble_grunt/mission.wav
sound/st_allies/nimble_grunt/mister.wav
sound/st_allies/nimble_grunt/move.wav
sound/st_allies/nimble_grunt/moveup.wav
sound/st_allies/nimble_grunt/moving.wav
sound/st_allies/nimble_grunt/no.wav
sound/st_allies/nimble_grunt/notfail.wav
sound/st_allies/nimble_grunt/nothing.wav
sound/st_allies/nimble_grunt/now.wav
sound/st_allies/nimble_grunt/oneshot.wav
sound/st_allies/nimble_grunt/orders.wav
sound/st_allies/nimble_grunt/outof.wav
sound/st_allies/nimble_grunt/pain1.wav
sound/st_allies/nimble_grunt/pain2.wav
sound/st_allies/nimble_grunt/pain3.wav
sound/st_allies/nimble_grunt/pain4.wav
sound/st_allies/nimble_grunt/quiet.wav
sound/st_allies/nimble_grunt/rapidfire.wav
sound/st_allies/nimble_grunt/recon.wav
sound/st_allies/nimble_grunt/right.wav
sound/st_allies/nimble_grunt/roger.wav
sound/st_allies/nimble_grunt/scout.wav
sound/st_allies/nimble_grunt/secure.wav
sound/st_allies/nimble_grunt/seensquad.wav
sound/st_allies/nimble_grunt/short.wav
sound/st_allies/nimble_grunt/six.wav
sound/st_allies/nimble_grunt/sniper.wav
sound/st_allies/nimble_grunt/suppressing.wav
sound/st_allies/nimble_grunt/sweep.wav
sound/st_allies/nimble_grunt/tag.wav
sound/st_allies/nimble_grunt/take.wav
sound/st_allies/nimble_grunt/talking.wav
sound/st_allies/nimble_grunt/wantsome.wav
sound/st_allies/nimble_grunt/watchfire.wav
sound/st_allies/nimble_grunt/watchit.wav
sound/st_allies/nimble_grunt/yes.wav
sound/st_allies/nimble_grunt/zone.wav
sound/st_allies/plinky/pl_idle1.ogg
sound/st_allies/plinky/pl_idle3.ogg
sound/st_allies/plinky/pl_idle4.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_hs_c5_brad.wav
sound/st_allies/sobrobo/sr_hs_c5_correct.wav
sound/st_mission/bunkersiren.wav
sound/st_mission/caralarm.wav
sound/st_mission/events/hs_c4/hs_c5_background.wav
sound/st_mission/events/hs_c4/hs_c5_battle.wav
sound/st_mission/events/hs_c4/stabbing.wav
sound/st_mission/music/hs_c5_music02.wav
sound/st_mission/radio/hs_c5_backup.wav
sound/st_mission/radio/hs_c5_civies.wav
sound/st_mission/radio/hs_c5_copy.wav
sound/st_mission/radio/hs_c5_evacuating.wav
sound/st_mission/radio/hs_c5_oscar.wav
sound/st_mission/truck3.wav
sound/st_mission/truck_goes.wav
sound/st_mission/weapons/f2000.wav
sound/st_mission/weapons/g36.wav
sound/st_mission/weapons/g3_fire1.wav
sound/st_mission/weapons/m4a1-fire.wav
sound/st_mission/weapons/m60-fire1.wav
sound/st_mission/weapons/sbarrel1.wav
sound/st_mission/weapons/scar-fire.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sound/st_mission/weapons/wa2000_shoot1.wav
sound/st_mission/weapons/xm8-fire.wav
sprites/c-tele1_red.spr
sprites/kezaeiv/prtl/kz_exit1.spr
