// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
aomreal.wad
cs_siege.wad
hs.wad
hs3.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/alienslave/blueslave.mdl
models/custom_monsters/alienslave/skeleton.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/gonome/archvile.mdl
models/custom_monsters/gonome/glitcherswift.mdl
models/custom_monsters/hgrunt/haunted_ngrunt.mdl
models/custom_monsters/hgrunt/haunted_ngrunt2.mdl
models/custom_monsters/hgrunt/haunted_security_ar.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_helmet.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_shotgun.mdl
models/custom_monsters/hgrunt/infected_sgrunt.mdl
models/custom_monsters/hgrunt/security_infected.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/darkzombie.mdl
models/custom_monsters/zombie/elite_slasher.mdl
models/custom_monsters/zombie/nimblezombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_sven.mdl
models/st_allies/darkwing.mdl
models/st_allies/dead_hev.mdl
models/st_allies/miles.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/security_ar.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/w_9mmm41a.mdl
models/st_mission1/props/w_famas.mdl
models/st_mission1/props/w_fnfal.mdl
models/st_mission1/props/w_lasergun.mdl
models/st_mission1/props/w_msg90.mdl
models/st_mission1/props/w_p904.mdl
models/st_mission1/scientist.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_spore_launcher.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/guns/g3/g3_fire.ogg
sound/custom_monsters/necroscasm/claw_miss1.ogg
sound/custom_monsters/necroscasm/claw_miss2.ogg
sound/custom_monsters/necroscasm/claw_strike1.ogg
sound/custom_monsters/necroscasm/claw_strike2.ogg
sound/custom_monsters/necroscasm/claw_strike3.ogg
sound/custom_monsters/necroscasm/zo_alert10.ogg
sound/custom_monsters/necroscasm/zo_alert20.ogg
sound/custom_monsters/necroscasm/zo_alert30.ogg
sound/custom_monsters/necroscasm/zo_attack1.ogg
sound/custom_monsters/necroscasm/zo_attack2.ogg
sound/custom_monsters/necroscasm/zo_idle1.ogg
sound/custom_monsters/necroscasm/zo_idle2.ogg
sound/custom_monsters/necroscasm/zo_idle3.ogg
sound/custom_monsters/necroscasm/zo_idle4.ogg
sound/custom_monsters/necroscasm/zo_pain1.ogg
sound/custom_monsters/necroscasm/zo_pain2.ogg
sound/custom_monsters/slasherghost/sg_alert1.ogg
sound/custom_monsters/slasherghost/sg_alert2.ogg
sound/custom_monsters/slasherghost/sg_alert3.ogg
sound/custom_monsters/slasherghost/sg_miss1.ogg
sound/custom_monsters/slasherghost/sg_miss2.ogg
sound/custom_monsters/slasherghost/sg_pain1.ogg
sound/custom_monsters/slasherghost/sg_pain2.ogg
sound/custom_monsters/slasherghost/sg_slash1.ogg
sound/custom_monsters/slasherghost/sg_slash2.ogg
sound/custom_monsters/slasherghost/sg_slash3.ogg
sound/custom_monsters/slasherghost/sg_voice1.ogg
sound/custom_monsters/slasherghost/sg_voice2.ogg
sound/custom_monsters/slasherghost/sg_voice3.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/darkwing/alert0.ogg
sound/st_allies/darkwing/alert1.ogg
sound/st_allies/darkwing/alert2.ogg
sound/st_allies/darkwing/alert3.ogg
sound/st_allies/darkwing/answer0.ogg
sound/st_allies/darkwing/answer1.ogg
sound/st_allies/darkwing/answer2.ogg
sound/st_allies/darkwing/charge0.ogg
sound/st_allies/darkwing/charge1.ogg
sound/st_allies/darkwing/charge2.ogg
sound/st_allies/darkwing/check0.ogg
sound/st_allies/darkwing/check1.ogg
sound/st_allies/darkwing/clear0.ogg
sound/st_allies/darkwing/clear1.ogg
sound/st_allies/darkwing/cover0.ogg
sound/st_allies/darkwing/cover1.ogg
sound/st_allies/darkwing/cover2.ogg
sound/st_allies/darkwing/death1.ogg
sound/st_allies/darkwing/death2.ogg
sound/st_allies/darkwing/death3.ogg
sound/st_allies/darkwing/dw_b8_move.ogg
sound/st_allies/darkwing/dw_b8_welcome.ogg
sound/st_allies/darkwing/dw_b9_miles.ogg
sound/st_allies/darkwing/dw_b9_movein.ogg
sound/st_allies/darkwing/gren0.ogg
sound/st_allies/darkwing/gren1.ogg
sound/st_allies/darkwing/hello0.ogg
sound/st_allies/darkwing/hello1.ogg
sound/st_allies/darkwing/hello2.ogg
sound/st_allies/darkwing/idle0.ogg
sound/st_allies/darkwing/idle1.ogg
sound/st_allies/darkwing/idle10.ogg
sound/st_allies/darkwing/idle11.ogg
sound/st_allies/darkwing/idle12.ogg
sound/st_allies/darkwing/idle2.ogg
sound/st_allies/darkwing/idle3.ogg
sound/st_allies/darkwing/idle4.ogg
sound/st_allies/darkwing/idle5.ogg
sound/st_allies/darkwing/idle6.ogg
sound/st_allies/darkwing/idle7.ogg
sound/st_allies/darkwing/idle8.ogg
sound/st_allies/darkwing/idle9.ogg
sound/st_allies/darkwing/kill0.ogg
sound/st_allies/darkwing/kill1.ogg
sound/st_allies/darkwing/kill2.ogg
sound/st_allies/darkwing/kill3.ogg
sound/st_allies/darkwing/kill4.ogg
sound/st_allies/darkwing/kill5.ogg
sound/st_allies/darkwing/kill6.ogg
sound/st_allies/darkwing/kill7.ogg
sound/st_allies/darkwing/kill8.ogg
sound/st_allies/darkwing/kill9.ogg
sound/st_allies/darkwing/mad0.ogg
sound/st_allies/darkwing/mad1.ogg
sound/st_allies/darkwing/monster0.ogg
sound/st_allies/darkwing/monster1.ogg
sound/st_allies/darkwing/mortal0.ogg
sound/st_allies/darkwing/mortal1.ogg
sound/st_allies/darkwing/mortal2.ogg
sound/st_allies/darkwing/ok0.ogg
sound/st_allies/darkwing/ok1.ogg
sound/st_allies/darkwing/ok2.ogg
sound/st_allies/darkwing/ok3.ogg
sound/st_allies/darkwing/ok4.ogg
sound/st_allies/darkwing/ok5.ogg
sound/st_allies/darkwing/ok6.ogg
sound/st_allies/darkwing/ok7.ogg
sound/st_allies/darkwing/ok8.ogg
sound/st_allies/darkwing/ok9.ogg
sound/st_allies/darkwing/pain1.ogg
sound/st_allies/darkwing/pain2.ogg
sound/st_allies/darkwing/pain3.ogg
sound/st_allies/darkwing/pain4.ogg
sound/st_allies/darkwing/pok0.ogg
sound/st_allies/darkwing/pok1.ogg
sound/st_allies/darkwing/pok2.ogg
sound/st_allies/darkwing/pok3.ogg
sound/st_allies/darkwing/quest0.ogg
sound/st_allies/darkwing/quest00.ogg
sound/st_allies/darkwing/quest01.ogg
sound/st_allies/darkwing/quest1.ogg
sound/st_allies/darkwing/quest2.ogg
sound/st_allies/darkwing/quest3.ogg
sound/st_allies/darkwing/quest4.ogg
sound/st_allies/darkwing/quest5.ogg
sound/st_allies/darkwing/scared0.ogg
sound/st_allies/darkwing/scared1.ogg
sound/st_allies/darkwing/shot0.ogg
sound/st_allies/darkwing/shot1.ogg
sound/st_allies/darkwing/shot2.ogg
sound/st_allies/darkwing/shot3.ogg
sound/st_allies/darkwing/shot5.ogg
sound/st_allies/darkwing/taunt0.ogg
sound/st_allies/darkwing/taunt1.ogg
sound/st_allies/darkwing/taunt2.ogg
sound/st_allies/darkwing/taunt3.ogg
sound/st_allies/darkwing/taunt4.ogg
sound/st_allies/darkwing/taunt5.ogg
sound/st_allies/darkwing/wait0.ogg
sound/st_allies/darkwing/wait1.ogg
sound/st_allies/darkwing/wait2.ogg
sound/st_allies/darkwing/wait3.ogg
sound/st_allies/darkwing/wound0.ogg
sound/st_allies/darkwing/wound1.ogg
sound/st_allies/darkwing/wound2.ogg
sound/st_allies/miles/death1.wav
sound/st_allies/miles/death2.wav
sound/st_allies/miles/death3.wav
sound/st_allies/miles/ml_answer1.wav
sound/st_allies/miles/ml_answer10.wav
sound/st_allies/miles/ml_answer11.wav
sound/st_allies/miles/ml_answer12.wav
sound/st_allies/miles/ml_answer13.wav
sound/st_allies/miles/ml_answer14.wav
sound/st_allies/miles/ml_answer15.wav
sound/st_allies/miles/ml_answer16.wav
sound/st_allies/miles/ml_answer17.wav
sound/st_allies/miles/ml_answer18.wav
sound/st_allies/miles/ml_answer19.wav
sound/st_allies/miles/ml_answer2.wav
sound/st_allies/miles/ml_answer20.wav
sound/st_allies/miles/ml_answer21.wav
sound/st_allies/miles/ml_answer22.wav
sound/st_allies/miles/ml_answer3.wav
sound/st_allies/miles/ml_answer4.wav
sound/st_allies/miles/ml_answer5.wav
sound/st_allies/miles/ml_answer6.wav
sound/st_allies/miles/ml_answer7.wav
sound/st_allies/miles/ml_answer8.wav
sound/st_allies/miles/ml_answer9.wav
sound/st_allies/miles/ml_attack1.wav
sound/st_allies/miles/ml_attack2.wav
sound/st_allies/miles/ml_attack3.wav
sound/st_allies/miles/ml_attack4.wav
sound/st_allies/miles/ml_attack5.wav
sound/st_allies/miles/ml_b9_heard.ogg
sound/st_allies/miles/ml_cure-a.wav
sound/st_allies/miles/ml_cure-b.wav
sound/st_allies/miles/ml_cure-c.wav
sound/st_allies/miles/ml_hear1.wav
sound/st_allies/miles/ml_hear2.wav
sound/st_allies/miles/ml_hear3.wav
sound/st_allies/miles/ml_hello1.wav
sound/st_allies/miles/ml_hello2.wav
sound/st_allies/miles/ml_hello3.wav
sound/st_allies/miles/ml_hello4.wav
sound/st_allies/miles/ml_hello5.wav
sound/st_allies/miles/ml_hello6.wav
sound/st_allies/miles/ml_hello7.wav
sound/st_allies/miles/ml_idle1.wav
sound/st_allies/miles/ml_idle10.wav
sound/st_allies/miles/ml_idle11.wav
sound/st_allies/miles/ml_idle2.wav
sound/st_allies/miles/ml_idle3.wav
sound/st_allies/miles/ml_idle4.wav
sound/st_allies/miles/ml_idle5.wav
sound/st_allies/miles/ml_idle6.wav
sound/st_allies/miles/ml_idle7.wav
sound/st_allies/miles/ml_idle8.wav
sound/st_allies/miles/ml_idle9.wav
sound/st_allies/miles/ml_kill1.wav
sound/st_allies/miles/ml_kill2.wav
sound/st_allies/miles/ml_kill3.wav
sound/st_allies/miles/ml_kill4.wav
sound/st_allies/miles/ml_kill5.wav
sound/st_allies/miles/ml_kill6.wav
sound/st_allies/miles/ml_kill7.wav
sound/st_allies/miles/ml_mad1.wav
sound/st_allies/miles/ml_mad2.wav
sound/st_allies/miles/ml_mad3.wav
sound/st_allies/miles/ml_mad4.wav
sound/st_allies/miles/ml_mad5.wav
sound/st_allies/miles/ml_mad6.wav
sound/st_allies/miles/ml_mad7.wav
sound/st_allies/miles/ml_mortal.wav
sound/st_allies/miles/ml_ok1.wav
sound/st_allies/miles/ml_ok2.wav
sound/st_allies/miles/ml_ok3.wav
sound/st_allies/miles/ml_ok4.wav
sound/st_allies/miles/ml_ok5.wav
sound/st_allies/miles/ml_ok6.wav
sound/st_allies/miles/ml_pok1.wav
sound/st_allies/miles/ml_pok2.wav
sound/st_allies/miles/ml_pok3.wav
sound/st_allies/miles/ml_pok4.wav
sound/st_allies/miles/ml_quest1.wav
sound/st_allies/miles/ml_quest10.wav
sound/st_allies/miles/ml_quest11.wav
sound/st_allies/miles/ml_quest12.wav
sound/st_allies/miles/ml_quest13.wav
sound/st_allies/miles/ml_quest14.wav
sound/st_allies/miles/ml_quest15.wav
sound/st_allies/miles/ml_quest2.wav
sound/st_allies/miles/ml_quest3.wav
sound/st_allies/miles/ml_quest4.wav
sound/st_allies/miles/ml_quest5.wav
sound/st_allies/miles/ml_quest6.wav
sound/st_allies/miles/ml_quest7.wav
sound/st_allies/miles/ml_quest8.wav
sound/st_allies/miles/ml_quest9.wav
sound/st_allies/miles/ml_scared1.ogg
sound/st_allies/miles/ml_scared2.wav
sound/st_allies/miles/ml_shot1.wav
sound/st_allies/miles/ml_shot2.wav
sound/st_allies/miles/ml_shot3.wav
sound/st_allies/miles/ml_shot4.wav
sound/st_allies/miles/ml_shot5.wav
sound/st_allies/miles/ml_smell1.wav
sound/st_allies/miles/ml_smell2.wav
sound/st_allies/miles/ml_smell3.wav
sound/st_allies/miles/ml_stare1.wav
sound/st_allies/miles/ml_stare2.wav
sound/st_allies/miles/ml_stare3.wav
sound/st_allies/miles/ml_stare4.wav
sound/st_allies/miles/ml_wait1.wav
sound/st_allies/miles/ml_wait2.wav
sound/st_allies/miles/ml_wait3.wav
sound/st_allies/miles/ml_wait4.wav
sound/st_allies/miles/ml_wait5.wav
sound/st_allies/miles/ml_wait6.wav
sound/st_allies/miles/ml_wound.wav
sound/st_allies/miles/ml_wound2.wav
sound/st_allies/miles/pain1.wav
sound/st_allies/miles/pain2.wav
sound/st_allies/miles/pain3.wav
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_mission/22noice2.ogg
sound/st_mission/announcements/soiz/announcement01.ogg
sound/st_mission/announcements/soiz/announcement02.ogg
sound/st_mission/announcements/soiz/announcement03.ogg
sound/st_mission/announcements/soiz/announcement04.ogg
sound/st_mission/announcements/soiz/announcement05.ogg
sound/st_mission/announcements/soiz/announcement06.ogg
sound/st_mission/distantfirefight.ogg
sound/st_mission/easteregg.ogg
sound/st_mission/music/hs_b9_raid.ogg
sound/st_mission/night.ogg
sound/st_mission/weapons/f2000.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sprites/singularity/prtl/kz_exit1.spr
