// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomreal.wad
cs_747.wad
hs.wad
hs2.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/hgrunt/mgrunt01.mdl
models/custom_monsters/hgrunt/mgrunt02.mdl
models/custom_monsters/hgrunt/mgrunt03.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/tor/overlord_wizard.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/slasher_ghost01.mdl
models/custom_monsters/zombie/slasher_ghost02.mdl
models/custom_monsters/zombie/slasher_ghostt.mdl
models/custom_monsters/zombie/zombie.mdl
models/st_allies/civilian.mdl
models/st_allies/crimsoncommando/crimson3.mdl
models/st_allies/crimsoncommando/crimson301.mdl
models/st_allies/crimsoncommando/crimson302.mdl
models/st_allies/crimsoncommando/crimson303.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hevt.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor01.mdl
models/st_allies/nimblegrunt/ngrunt_opfor02.mdl
models/st_allies/nimblegrunt/ngrunt_opfor03.mdl
models/st_allies/nimblegrunt/ngrunt_opfor2.mdl
models/st_allies/nimblegrunt/ngrunt_opfor201.mdl
models/st_allies/nimblegrunt/ngrunt_opfor202.mdl
models/st_allies/nimblegrunt/ngrunt_opfor203.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/survivor.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/props/100usd.mdl
models/st_mission1/tracking_device.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/w_nyctophilia_dagger1.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
sound/custom_monsters/guns/shotgun/sbarrel1.wav
sound/custom_monsters/guns/smg/hks1.wav
sound/custom_monsters/guns/smg/hks2.wav
sound/custom_monsters/guns/smg/hks3.wav
sound/custom_monsters/mercs/hs_c5_dagger.wav
sound/custom_monsters/mercs/hs_c5_getout.wav
sound/custom_monsters/overlordwizard/ow_hs_c5_god.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_allies/crimson_commando/alert.wav
sound/st_allies/crimson_commando/area.wav
sound/st_allies/crimson_commando/ass.wav
sound/st_allies/crimson_commando/babysitting.wav
sound/st_allies/crimson_commando/backup.wav
sound/st_allies/crimson_commando/bfeeling.wav
sound/st_allies/crimson_commando/bogies.wav
sound/st_allies/crimson_commando/charge.wav
sound/st_allies/crimson_commando/check.wav
sound/st_allies/crimson_commando/checkrecon.wav
sound/st_allies/crimson_commando/chicken.wav
sound/st_allies/crimson_commando/clear.wav
sound/st_allies/crimson_commando/command.wav
sound/st_allies/crimson_commando/corners.wav
sound/st_allies/crimson_commando/corporal.wav
sound/st_allies/crimson_commando/corporal_01.wav
sound/st_allies/crimson_commando/cover.wav
sound/st_allies/crimson_commando/covering.wav
sound/st_allies/crimson_commando/coverup.wav
sound/st_allies/crimson_commando/current.wav
sound/st_allies/crimson_commando/damage.wav
sound/st_allies/crimson_commando/death1.wav
sound/st_allies/crimson_commando/death2.wav
sound/st_allies/crimson_commando/death3.wav
sound/st_allies/crimson_commando/disney.wav
sound/st_allies/crimson_commando/dogs.wav
sound/st_allies/crimson_commando/down.wav
sound/st_allies/crimson_commando/flank.wav
sound/st_allies/crimson_commando/freaks.wav
sound/st_allies/crimson_commando/friendly.wav
sound/st_allies/crimson_commando/fubar.wav
sound/st_allies/crimson_commando/getsome.wav
sound/st_allies/crimson_commando/go.wav
sound/st_allies/crimson_commando/gotit.wav
sound/st_allies/crimson_commando/gr_pain1.wav
sound/st_allies/crimson_commando/gr_pain2.wav
sound/st_allies/crimson_commando/gr_pain3.wav
sound/st_allies/crimson_commando/gr_pain4.wav
sound/st_allies/crimson_commando/grenade.wav
sound/st_allies/crimson_commando/guard.wav
sound/st_allies/crimson_commando/guardduty.wav
sound/st_allies/crimson_commando/hellosir.wav
sound/st_allies/crimson_commando/hellout.wav
sound/st_allies/crimson_commando/hitbad.wav
sound/st_allies/crimson_commando/hostiles.wav
sound/st_allies/crimson_commando/imhit.wav
sound/st_allies/crimson_commando/incoming.wav
sound/st_allies/crimson_commando/lost.wav
sound/st_allies/crimson_commando/marines.wav
sound/st_allies/crimson_commando/mission.wav
sound/st_allies/crimson_commando/mister.wav
sound/st_allies/crimson_commando/move.wav
sound/st_allies/crimson_commando/moveup.wav
sound/st_allies/crimson_commando/moving.wav
sound/st_allies/crimson_commando/no.wav
sound/st_allies/crimson_commando/notfail.wav
sound/st_allies/crimson_commando/now.wav
sound/st_allies/crimson_commando/oneshot.wav
sound/st_allies/crimson_commando/orders.wav
sound/st_allies/crimson_commando/outof.wav
sound/st_allies/crimson_commando/pain1.wav
sound/st_allies/crimson_commando/pain2.wav
sound/st_allies/crimson_commando/pain3.wav
sound/st_allies/crimson_commando/pain4.wav
sound/st_allies/crimson_commando/quiet.wav
sound/st_allies/crimson_commando/rapidfire.wav
sound/st_allies/crimson_commando/recon.wav
sound/st_allies/crimson_commando/right.wav
sound/st_allies/crimson_commando/roger.wav
sound/st_allies/crimson_commando/scout.wav
sound/st_allies/crimson_commando/secure.wav
sound/st_allies/crimson_commando/seensquad.wav
sound/st_allies/crimson_commando/short.wav
sound/st_allies/crimson_commando/six.wav
sound/st_allies/crimson_commando/sniper.wav
sound/st_allies/crimson_commando/suppressing.wav
sound/st_allies/crimson_commando/sweep.wav
sound/st_allies/crimson_commando/tag.wav
sound/st_allies/crimson_commando/take.wav
sound/st_allies/crimson_commando/talking.wav
sound/st_allies/crimson_commando/wantsome.wav
sound/st_allies/crimson_commando/watchfire.wav
sound/st_allies/crimson_commando/watchit.wav
sound/st_allies/crimson_commando/yes.wav
sound/st_allies/crimson_commando/zone.wav
sound/st_mission/angelic_energy.wav
sound/st_mission/events/hs_c4/a_grabdagger.wav
sound/st_mission/events/hs_c4/distant_angel_shadows.wav
sound/st_mission/events/hs_c4/distant_angel_shoot.wav
sound/st_mission/events/hs_c4/distant_angel_warp.wav
sound/st_mission/events/hs_c4/distant_demon_attack.wav
sound/st_mission/events/hs_c4/distant_demon_dash.wav
sound/st_mission/events/hs_c4/distant_displace.wav
sound/st_mission/events/hs_c4/distant_explosion.wav
sound/st_mission/events/hs_c4/warp_in.wav
sound/st_mission/rain_inside.wav
sound/st_mission/rain_window.wav
sound/st_mission/thunder1.wav
sound/st_mission/thunder2.wav
sound/st_mission/thunder3.wav
sound/st_mission/thunder4.wav
sound/st_mission/weapons/m60-fire1.wav
sound/st_mission/weapons/sbarrel1.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sound/st_mission/weapons/xm8-fire.wav
sprites/c-tele1_blu.spr
sprites/kezaeiv/prtl/kz_exit1.spr
