// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

aomdc22.wad
aomreal.wad
bigcity2.wad
cars.wad
cs_747.wad
cs_assault_halloween.wad
cs_office.wad
cs_siege.wad
fi.wad
gfx/env/arcssbk.tga
gfx/env/arcssdn.tga
gfx/env/arcssft.tga
gfx/env/arcsslf.tga
gfx/env/arcssrt.tga
gfx/env/arcssup.tga
hle.wad
hs.wad
hs2.wad
hs3.wad
hs5.wad
models/custom_monsters/agrunt/agrunt_snow.mdl
models/custom_monsters/agrunt/paralyzed_subject.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/gonome/licker.mdl
models/custom_monsters/gonome/mutant_runner.mdl
models/custom_monsters/hgrunt/haunted_crimson3.mdl
models/custom_monsters/hgrunt/haunted_ngrunt2.mdl
models/custom_monsters/hgrunt/haunted_security_ar.mdl
models/custom_monsters/hgrunt/haunted_svenhelmet_helmet.mdl
models/custom_monsters/hgrunt/possessed_zngrunt.mdl
models/custom_monsters/ichthyosaur/skeleshark.mdl
models/custom_monsters/pitdrone/frost_slasher.mdl
models/custom_monsters/zombie/corpse.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/lpzombie.mdl
models/custom_monsters/zombie/nimblezombie.mdl
models/custom_monsters/zombie/shryk.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie2.mdl
models/custom_monsters/zombie/zombie3.mdl
models/custom_monsters/zombie/zombie_construct.mdl
models/custom_monsters/zombie/zombie_crowbar.mdl
models/custom_monsters/zombie/zombika.mdl
models/sp_portal/ginsengavenger/gins_bucket.mdl
models/st_allies/crimsoncommando/crimson.mdl
models/st_allies/crimsoncommando/crimson2.mdl
models/st_allies/crimsoncommando/crimson3.mdl
models/st_allies/cyrex_upgraded.mdl
models/st_allies/darkwing.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hev2.mdl
models/st_allies/fat_scientist.mdl
models/st_allies/janitor.mdl
models/st_allies/scientist.mdl
models/st_allies/security_ar.mdl
models/st_allies/zngrunt.mdl
models/st_mission1/flag_empire.mdl
models/st_mission1/phone_pay-us.mdl
models/st_mission1/props/agonizand/ag_light_small.mdl
models/st_mission1/props/agonizand/ag_limb_large.mdl
models/st_mission1/props/agonizand/ag_limb_mid.mdl
models/st_mission1/props/arty_radio.mdl
models/st_mission1/props/big_bucket.mdl
models/st_mission1/props/db_pipes2.mdl
models/st_mission1/props/delta_duct_fans.mdl
models/st_mission1/props/delta_fans.mdl
models/st_mission1/props/dn_hughrvs1.mdl
models/st_mission1/props/es_3pipes_corner.mdl
models/st_mission1/props/es_pipes_roof.mdl
models/st_mission1/props/es_pipes_up2.mdl
models/st_mission1/props/es_pipes_up3.mdl
models/st_mission1/props/food_tray.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/lamp_portable_standup.mdl
models/st_mission1/props/papers_detail.mdl
models/st_mission1/props/pc_ub_mb_ebox_a.mdl
models/st_mission1/props/pipe1_es.mdl
models/st_mission1/props/pipes_airpad_double_smallend1.mdl
models/st_mission1/props/pipes_airpad_double_vert.mdl
models/st_mission1/props/pipes_airpad_l112.mdl
models/st_mission1/props/pipes_airpad_l424.mdl
models/st_mission1/props/qmeal.mdl
models/st_mission1/props/s_cables_ceiling.mdl
models/st_mission1/props/scaffold.mdl
models/st_mission1/props/skeleton_rope.mdl
models/st_mission1/props/trash.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/tree3.mdl
models/st_mission1/props/truck_old.mdl
models/st_mission1/props/wall_basement_computer1.mdl
models/st_mission1/props/wall_basement_computer2.mdl
models/st_mission1/props/wall_basement_computer3.mdl
models/st_mission1/props/wall_box_transf2.mdl
models/st_mission1/props/wall_box_transf3.mdl
models/st_mission1/props/wall_box_transf5.mdl
models/st_mission1/props/wall_box_transf6.mdl
models/st_mission1/props/wall_box_transf7.mdl
models/st_mission1/props/wall_computer2.mdl
models/st_mission1/props/wall_computer5.mdl
models/st_mission1/props/wall_computer6.mdl
models/st_mission1/props/wall_db_oldcase.mdl
models/st_mission1/props/wall_ele_shield1.mdl
models/st_mission1/props/wall_ele_shield1_open.mdl
models/st_mission1/props/wall_ele_shield_double.mdl
models/st_mission1/scientist.mdl
models/st_mission1/snowflake.mdl
models/st_mission1/teleporter.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/crimson/v_357.mdl
models/st_mission1/weapons_classic/crimson/v_9mmar.mdl
models/st_mission1/weapons_classic/crimson/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/crimson/v_crossbow.mdl
models/st_mission1/weapons_classic/crimson/v_crowbar.mdl
models/st_mission1/weapons_classic/crimson/v_displacer.mdl
models/st_mission1/weapons_classic/crimson/v_eagle.mdl
models/st_mission1/weapons_classic/crimson/v_egon.mdl
models/st_mission1/weapons_classic/crimson/v_gauss.mdl
models/st_mission1/weapons_classic/crimson/v_grenade.mdl
models/st_mission1/weapons_classic/crimson/v_m16a2.mdl
models/st_mission1/weapons_classic/crimson/v_m40a1.mdl
models/st_mission1/weapons_classic/crimson/v_medkit.mdl
models/st_mission1/weapons_classic/crimson/v_minigun.mdl
models/st_mission1/weapons_classic/crimson/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/crimson/v_rpg.mdl
models/st_mission1/weapons_classic/crimson/v_satchel.mdl
models/st_mission1/weapons_classic/crimson/v_satchel_radio.mdl
models/st_mission1/weapons_classic/crimson/v_saw.mdl
models/st_mission1/weapons_classic/crimson/v_shotgun.mdl
models/st_mission1/weapons_classic/crimson/v_spore_launcher.mdl
models/st_mission1/weapons_classic/crimson/v_squeak.mdl
models/st_mission1/weapons_classic/crimson/v_tripmine.mdl
models/st_mission1/weapons_classic/crimson/v_uzi.mdl
models/st_mission1/weapons_classic/p_bgrap.mdl
models/st_mission1/weapons_classic/p_displacer.mdl
models/st_mission1/weapons_classic/v_bgrap.mdl
models/st_mission1/weapons_classic/w_bgrap.mdl
models/st_mission1/weapons_classic/w_displacer.mdl
models/st_mission1/weapons_classic/w_gauss.mdl
silenthill.wad
sound/cleaner/spray1.wav
sound/cleaner/spray2.wav
sound/cleaner/sweep1.wav
sound/cleaner/sweep2.wav
sound/cleaner/sweep3.wav
sound/cleaner/wipe.wav
sound/custom_monsters/mutantrunner/mr_alert2.ogg
sound/custom_monsters/mutantrunner/mr_alert3.ogg
sound/custom_monsters/mutantrunner/mr_attack.ogg
sound/custom_monsters/mutantrunner/mr_die1.ogg
sound/custom_monsters/mutantrunner/mr_die2.ogg
sound/custom_monsters/mutantrunner/mr_hit1.ogg
sound/custom_monsters/mutantrunner/mr_hit2.ogg
sound/custom_monsters/mutantrunner/mr_idle1.ogg
sound/custom_monsters/mutantrunner/mr_idle2.ogg
sound/custom_monsters/mutantrunner/mr_pain1.ogg
sound/custom_monsters/mutantrunner/mr_pain2.ogg
sound/custom_monsters/paralyzed_subject/ps_alert1.ogg
sound/custom_monsters/paralyzed_subject/ps_alert3.ogg
sound/custom_monsters/paralyzed_subject/ps_alert4.ogg
sound/custom_monsters/paralyzed_subject/ps_attack1.ogg
sound/custom_monsters/paralyzed_subject/ps_attack2.ogg
sound/custom_monsters/paralyzed_subject/ps_attack3.ogg
sound/custom_monsters/paralyzed_subject/ps_die1.ogg
sound/custom_monsters/paralyzed_subject/ps_die4.ogg
sound/custom_monsters/paralyzed_subject/ps_die5.ogg
sound/custom_monsters/paralyzed_subject/ps_idle1.ogg
sound/custom_monsters/paralyzed_subject/ps_idle2.ogg
sound/custom_monsters/paralyzed_subject/ps_idle3.ogg
sound/custom_monsters/paralyzed_subject/ps_idle4.ogg
sound/custom_monsters/paralyzed_subject/ps_pain1.ogg
sound/custom_monsters/paralyzed_subject/ps_pain2.ogg
sound/custom_monsters/paralyzed_subject/ps_pain3.ogg
sound/custom_monsters/paralyzed_subject/ps_pain4.ogg
sound/custom_monsters/paralyzed_subject/ps_pain5.ogg
sound/custom_monsters/portal.ogg
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/hs/weapons/voidfold_cannon_charge.ogg
sound/hs/weapons/voidfold_cannon_charge2.ogg
sound/hs/weapons/voidfold_cannon_fire.ogg
sound/hs/weapons/voidfold_cannon_impact.ogg
sound/hs/weapons/voidfold_cannon_playertp.ogg
sound/hs/weapons/voidfold_cannon_selftp.ogg
sound/hs/weapons/voidfold_cannon_start.ogg
sound/hs/weapons/voidfold_cannon_teleport.ogg
sound/oghs/misc/cp02_03.mp3
sound/player/pl_wood_scr1.ogg
sound/player/pl_wood_scr2.ogg
sound/player/pl_wood_scr3.ogg
sound/player/pl_wood_scr4.ogg
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/alert.ogg
sound/st_allies/crimson_commando/area.ogg
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/backup.ogg
sound/st_allies/crimson_commando/bfeeling.ogg
sound/st_allies/crimson_commando/bogies.ogg
sound/st_allies/crimson_commando/charge.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/checkrecon.ogg
sound/st_allies/crimson_commando/chicken.ogg
sound/st_allies/crimson_commando/clear.ogg
sound/st_allies/crimson_commando/command.ogg
sound/st_allies/crimson_commando/corners.ogg
sound/st_allies/crimson_commando/corporal.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/cover.ogg
sound/st_allies/crimson_commando/covering.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/current.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/disney.ogg
sound/st_allies/crimson_commando/dogs.ogg
sound/st_allies/crimson_commando/down.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/freaks.ogg
sound/st_allies/crimson_commando/friendly.ogg
sound/st_allies/crimson_commando/fubar.ogg
sound/st_allies/crimson_commando/getsome.ogg
sound/st_allies/crimson_commando/go.ogg
sound/st_allies/crimson_commando/gotit.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/grenade.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hellout.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/incoming.ogg
sound/st_allies/crimson_commando/lost.ogg
sound/st_allies/crimson_commando/marines.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/move.ogg
sound/st_allies/crimson_commando/moveup.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/no.ogg
sound/st_allies/crimson_commando/notfail.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/outof.ogg
sound/st_allies/crimson_commando/pain1.ogg
sound/st_allies/crimson_commando/pain2.ogg
sound/st_allies/crimson_commando/pain3.ogg
sound/st_allies/crimson_commando/pain4.ogg
sound/st_allies/crimson_commando/quiet.ogg
sound/st_allies/crimson_commando/rapidfire.ogg
sound/st_allies/crimson_commando/recon.ogg
sound/st_allies/crimson_commando/right.ogg
sound/st_allies/crimson_commando/roger.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/seensquad.ogg
sound/st_allies/crimson_commando/short.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/suppressing.ogg
sound/st_allies/crimson_commando/sweep.ogg
sound/st_allies/crimson_commando/tag.ogg
sound/st_allies/crimson_commando/take.ogg
sound/st_allies/crimson_commando/talking.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/watchfire.ogg
sound/st_allies/crimson_commando/watchit.ogg
sound/st_allies/crimson_commando/yes.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_allies/cyrex/cy_d10_because.ogg
sound/st_allies/cyrex/cy_d10_bring.ogg
sound/st_allies/cyrex/cy_d10_encounter.ogg
sound/st_allies/cyrex/cy_d10_rodney.ogg
sound/st_allies/cyrex/cy_idle1.ogg
sound/st_allies/cyrex/cy_idle2.ogg
sound/st_allies/cyrex/cy_idle3.ogg
sound/st_allies/cyrex/cy_idle4.ogg
sound/st_allies/cyrex/cy_idle5.ogg
sound/st_allies/darkwing/alert0.ogg
sound/st_allies/darkwing/alert1.ogg
sound/st_allies/darkwing/alert2.ogg
sound/st_allies/darkwing/alert3.ogg
sound/st_allies/darkwing/answer0.ogg
sound/st_allies/darkwing/answer1.ogg
sound/st_allies/darkwing/answer2.ogg
sound/st_allies/darkwing/charge0.ogg
sound/st_allies/darkwing/charge1.ogg
sound/st_allies/darkwing/charge2.ogg
sound/st_allies/darkwing/check0.ogg
sound/st_allies/darkwing/check1.ogg
sound/st_allies/darkwing/clear0.ogg
sound/st_allies/darkwing/clear1.ogg
sound/st_allies/darkwing/cover0.ogg
sound/st_allies/darkwing/cover1.ogg
sound/st_allies/darkwing/cover2.ogg
sound/st_allies/darkwing/death1.ogg
sound/st_allies/darkwing/death2.ogg
sound/st_allies/darkwing/death3.ogg
sound/st_allies/darkwing/dw_d10_askher.ogg
sound/st_allies/darkwing/dw_d10_gooo.ogg
sound/st_allies/darkwing/dw_d10_how.ogg
sound/st_allies/darkwing/dw_d10_killrodney.ogg
sound/st_allies/darkwing/dw_d10_there.ogg
sound/st_allies/darkwing/dw_d10_wait.ogg
sound/st_allies/darkwing/dw_d8_shield.ogg
sound/st_allies/darkwing/gren0.ogg
sound/st_allies/darkwing/gren1.ogg
sound/st_allies/darkwing/hello0.ogg
sound/st_allies/darkwing/hello1.ogg
sound/st_allies/darkwing/hello2.ogg
sound/st_allies/darkwing/idle0.ogg
sound/st_allies/darkwing/idle1.ogg
sound/st_allies/darkwing/idle10.ogg
sound/st_allies/darkwing/idle11.ogg
sound/st_allies/darkwing/idle12.ogg
sound/st_allies/darkwing/idle2.ogg
sound/st_allies/darkwing/idle3.ogg
sound/st_allies/darkwing/idle4.ogg
sound/st_allies/darkwing/idle5.ogg
sound/st_allies/darkwing/idle6.ogg
sound/st_allies/darkwing/idle7.ogg
sound/st_allies/darkwing/idle8.ogg
sound/st_allies/darkwing/idle9.ogg
sound/st_allies/darkwing/kill0.ogg
sound/st_allies/darkwing/kill1.ogg
sound/st_allies/darkwing/kill2.ogg
sound/st_allies/darkwing/kill3.ogg
sound/st_allies/darkwing/kill4.ogg
sound/st_allies/darkwing/kill5.ogg
sound/st_allies/darkwing/kill6.ogg
sound/st_allies/darkwing/kill7.ogg
sound/st_allies/darkwing/kill8.ogg
sound/st_allies/darkwing/kill9.ogg
sound/st_allies/darkwing/mad0.ogg
sound/st_allies/darkwing/mad1.ogg
sound/st_allies/darkwing/monster0.ogg
sound/st_allies/darkwing/monster1.ogg
sound/st_allies/darkwing/mortal0.ogg
sound/st_allies/darkwing/mortal1.ogg
sound/st_allies/darkwing/mortal2.ogg
sound/st_allies/darkwing/ok0.ogg
sound/st_allies/darkwing/ok1.ogg
sound/st_allies/darkwing/ok2.ogg
sound/st_allies/darkwing/ok3.ogg
sound/st_allies/darkwing/ok4.ogg
sound/st_allies/darkwing/ok5.ogg
sound/st_allies/darkwing/ok6.ogg
sound/st_allies/darkwing/ok7.ogg
sound/st_allies/darkwing/ok8.ogg
sound/st_allies/darkwing/ok9.ogg
sound/st_allies/darkwing/pain1.ogg
sound/st_allies/darkwing/pain2.ogg
sound/st_allies/darkwing/pain3.ogg
sound/st_allies/darkwing/pain4.ogg
sound/st_allies/darkwing/pok0.ogg
sound/st_allies/darkwing/pok1.ogg
sound/st_allies/darkwing/pok2.ogg
sound/st_allies/darkwing/pok3.ogg
sound/st_allies/darkwing/quest0.ogg
sound/st_allies/darkwing/quest00.ogg
sound/st_allies/darkwing/quest01.ogg
sound/st_allies/darkwing/quest1.ogg
sound/st_allies/darkwing/quest2.ogg
sound/st_allies/darkwing/quest3.ogg
sound/st_allies/darkwing/quest4.ogg
sound/st_allies/darkwing/quest5.ogg
sound/st_allies/darkwing/scared0.ogg
sound/st_allies/darkwing/scared1.ogg
sound/st_allies/darkwing/shot0.ogg
sound/st_allies/darkwing/shot1.ogg
sound/st_allies/darkwing/shot2.ogg
sound/st_allies/darkwing/shot3.ogg
sound/st_allies/darkwing/shot5.ogg
sound/st_allies/darkwing/taunt0.ogg
sound/st_allies/darkwing/taunt1.ogg
sound/st_allies/darkwing/taunt2.ogg
sound/st_allies/darkwing/taunt3.ogg
sound/st_allies/darkwing/taunt4.ogg
sound/st_allies/darkwing/taunt5.ogg
sound/st_allies/darkwing/wait0.ogg
sound/st_allies/darkwing/wait1.ogg
sound/st_allies/darkwing/wait2.ogg
sound/st_allies/darkwing/wait3.ogg
sound/st_allies/darkwing/wound0.ogg
sound/st_allies/darkwing/wound1.ogg
sound/st_allies/darkwing/wound2.ogg
sound/st_allies/nimble_grunt/alert.ogg
sound/st_allies/nimble_grunt/area.ogg
sound/st_allies/nimble_grunt/ass.ogg
sound/st_allies/nimble_grunt/babysitting.ogg
sound/st_allies/nimble_grunt/backup.ogg
sound/st_allies/nimble_grunt/bfeeling.ogg
sound/st_allies/nimble_grunt/bogies.ogg
sound/st_allies/nimble_grunt/charge.ogg
sound/st_allies/nimble_grunt/check.ogg
sound/st_allies/nimble_grunt/checkrecon.ogg
sound/st_allies/nimble_grunt/chicken.ogg
sound/st_allies/nimble_grunt/clear.ogg
sound/st_allies/nimble_grunt/command.ogg
sound/st_allies/nimble_grunt/corners.ogg
sound/st_allies/nimble_grunt/corporal.ogg
sound/st_allies/nimble_grunt/corporal_01.ogg
sound/st_allies/nimble_grunt/cover.ogg
sound/st_allies/nimble_grunt/covering.ogg
sound/st_allies/nimble_grunt/coverup.ogg
sound/st_allies/nimble_grunt/current.ogg
sound/st_allies/nimble_grunt/damage.ogg
sound/st_allies/nimble_grunt/death1.ogg
sound/st_allies/nimble_grunt/death2.ogg
sound/st_allies/nimble_grunt/death3.ogg
sound/st_allies/nimble_grunt/disney.ogg
sound/st_allies/nimble_grunt/dogs.ogg
sound/st_allies/nimble_grunt/down.ogg
sound/st_allies/nimble_grunt/flank.ogg
sound/st_allies/nimble_grunt/freaks.ogg
sound/st_allies/nimble_grunt/friendly.ogg
sound/st_allies/nimble_grunt/fubar.ogg
sound/st_allies/nimble_grunt/getsome.ogg
sound/st_allies/nimble_grunt/go.ogg
sound/st_allies/nimble_grunt/gotit.ogg
sound/st_allies/nimble_grunt/gr_pain1.ogg
sound/st_allies/nimble_grunt/gr_pain2.ogg
sound/st_allies/nimble_grunt/gr_pain3.ogg
sound/st_allies/nimble_grunt/gr_pain4.ogg
sound/st_allies/nimble_grunt/grenade.ogg
sound/st_allies/nimble_grunt/guard.ogg
sound/st_allies/nimble_grunt/guardduty.ogg
sound/st_allies/nimble_grunt/hellosir.ogg
sound/st_allies/nimble_grunt/hellout.ogg
sound/st_allies/nimble_grunt/hitbad.ogg
sound/st_allies/nimble_grunt/hostiles.ogg
sound/st_allies/nimble_grunt/imhit.ogg
sound/st_allies/nimble_grunt/incoming.ogg
sound/st_allies/nimble_grunt/lost.ogg
sound/st_allies/nimble_grunt/marines.ogg
sound/st_allies/nimble_grunt/mission.ogg
sound/st_allies/nimble_grunt/mister.ogg
sound/st_allies/nimble_grunt/move.ogg
sound/st_allies/nimble_grunt/moveup.ogg
sound/st_allies/nimble_grunt/moving.ogg
sound/st_allies/nimble_grunt/no.ogg
sound/st_allies/nimble_grunt/notfail.ogg
sound/st_allies/nimble_grunt/nothing.ogg
sound/st_allies/nimble_grunt/now.ogg
sound/st_allies/nimble_grunt/oneshot.ogg
sound/st_allies/nimble_grunt/orders.ogg
sound/st_allies/nimble_grunt/outof.ogg
sound/st_allies/nimble_grunt/pain1.ogg
sound/st_allies/nimble_grunt/pain2.ogg
sound/st_allies/nimble_grunt/pain3.ogg
sound/st_allies/nimble_grunt/pain4.ogg
sound/st_allies/nimble_grunt/quiet.ogg
sound/st_allies/nimble_grunt/rapidfire.ogg
sound/st_allies/nimble_grunt/recon.ogg
sound/st_allies/nimble_grunt/right.ogg
sound/st_allies/nimble_grunt/roger.ogg
sound/st_allies/nimble_grunt/scout.ogg
sound/st_allies/nimble_grunt/secure.ogg
sound/st_allies/nimble_grunt/seensquad.ogg
sound/st_allies/nimble_grunt/short.ogg
sound/st_allies/nimble_grunt/six.ogg
sound/st_allies/nimble_grunt/sniper.ogg
sound/st_allies/nimble_grunt/suppressing.ogg
sound/st_allies/nimble_grunt/sweep.ogg
sound/st_allies/nimble_grunt/tag.ogg
sound/st_allies/nimble_grunt/take.ogg
sound/st_allies/nimble_grunt/talking.ogg
sound/st_allies/nimble_grunt/wantsome.ogg
sound/st_allies/nimble_grunt/watchfire.ogg
sound/st_allies/nimble_grunt/watchit.ogg
sound/st_allies/nimble_grunt/yes.ogg
sound/st_allies/nimble_grunt/zone.ogg
sound/st_allies/sobrobo/sr_bip1.ogg
sound/st_allies/sobrobo/sr_bip2.ogg
sound/st_allies/sobrobo/sr_bip3.ogg
sound/st_allies/sobrobo/sr_bip4.ogg
sound/st_allies/sobrobo/sr_hs_d10_access.ogg
sound/st_mission/blizzard.ogg
sound/st_mission/broken_fan2.ogg
sound/st_mission/events/hs_c4/warp_in.ogg
sound/st_mission/events/hs_c4/warp_out.ogg
sound/st_mission/events/hs_d/hs_d10_darkwing_final.ogg
sound/st_mission/flareidle.ogg
sound/st_mission/helicopter13.ogg
sound/st_mission/jet_inside.ogg
sound/st_mission/music/background/c/c3_amb_facility01.ogg
sound/st_mission/music/background/c/c3_amb_facility02.ogg
sound/st_mission/music/background/c/c3_amb_facility03.ogg
sound/st_mission/music/background/c/c3_amb_facility04.ogg
sound/st_mission/music/background/c/c3_amb_facility05.ogg
sound/st_mission/music/background/c/c3_amb_facility06.ogg
sound/st_mission/music/hs_d9_combat.ogg
sound/st_mission/plats/flyingspark.ogg
sound/st_mission/tunnel_wind1.ogg
sound/st_mission/weapons/f2000.ogg
sound/st_mission/weapons/fn_in1.ogg
sound/st_mission/weapons/fn_out1.ogg
sound/st_mission/weapons/g36.ogg
sound/st_mission/weapons/g3_in.ogg
sound/st_mission/weapons/g3_out.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/xm8-fire.ogg
sprites/arctic_incident/ws_snow_fx.spr
sprites/singularity/prtl/kz_exit1.spr
