// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/mil_crategibs.mdl
9.wad
aomreal.wad
BigCity2.wad
cs_747.wad
cs_office.wad
hs.wad
hs2.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/gonome/glitcherswift.mdl
models/custom_monsters/gonome/praetorian.mdl
models/custom_monsters/hgrunt/mgrunt.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/tor/overlord_wizard.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/lpzombie.mdl
models/custom_monsters/zombie/slasher_ghost.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/zombie.mdl
models/custom_monsters/zombie/zombie_crowbar.mdl
models/st_allies/civilian.mdl
models/st_allies/crimsoncommando/crimson3.mdl
models/st_allies/dead_hev.mdl
models/st_allies/nimblegrunt/ngrunt_opfor.mdl
models/st_allies/nimblegrunt/ngrunt_opfor2.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_allies/survivor.mdl
models/st_mission1/backpack_bio.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/blackhawk_down.mdl
models/st_mission1/c4.mdl
models/st_mission1/eatencorpse.mdl
models/st_mission1/props/100usd.mdl
models/st_mission1/props/aa_lod_breach_01_cmz_smesh.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/cheap_police_sedan2.mdl
models/st_mission1/props/cheap_wrecked_sedan_white.mdl
models/st_mission1/props/compost_tower_short.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/trash2.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/props/wrecked_car_brown.mdl
models/st_mission1/researcher_corpse.mdl
models/st_mission1/tracking_device.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/w_nyctophilia_dagger1.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
siege_apc.wad
sound/custom_monsters/guns/shotgun/sbarrel1.ogg
sound/custom_monsters/guns/smg/hks1.ogg
sound/custom_monsters/guns/smg/hks2.ogg
sound/custom_monsters/guns/smg/hks3.ogg
sound/custom_monsters/mercs/hs_c5_dagger.wav
sound/custom_monsters/mercs/hs_c5_getout.wav
sound/custom_monsters/overlordwizard/ow_hs_c5_god.wav
sound/custom_monsters/spitter/bc_acid1.ogg
sound/custom_monsters/spitter/bc_acid2.ogg
sound/custom_monsters/spitter/bc_attack1.ogg
sound/custom_monsters/spitter/bc_attack2.ogg
sound/custom_monsters/spitter/bc_attack3.ogg
sound/custom_monsters/spitter/bc_attackgrowl.ogg
sound/custom_monsters/spitter/bc_attackgrowl2.ogg
sound/custom_monsters/spitter/bc_attackgrowl3.ogg
sound/custom_monsters/spitter/bc_bite1.ogg
sound/custom_monsters/spitter/bc_bite2.ogg
sound/custom_monsters/spitter/bc_bite3.ogg
sound/custom_monsters/spitter/bc_die1.ogg
sound/custom_monsters/spitter/bc_die2.ogg
sound/custom_monsters/spitter/bc_die3.ogg
sound/custom_monsters/spitter/bc_idle1.ogg
sound/custom_monsters/spitter/bc_idle2.ogg
sound/custom_monsters/spitter/bc_idle3.ogg
sound/custom_monsters/spitter/bc_idle4.ogg
sound/custom_monsters/spitter/bc_idle5.ogg
sound/custom_monsters/spitter/bc_pain1.ogg
sound/custom_monsters/spitter/bc_pain2.ogg
sound/custom_monsters/spitter/bc_pain3.ogg
sound/custom_monsters/spitter/bc_pain4.ogg
sound/custom_monsters/spitter/bc_spithit1.ogg
sound/custom_monsters/spitter/bc_spithit2.ogg
sound/custom_monsters/spitter/bc_spithit3.ogg
sound/custom_monsters/zombie/claw_miss1.ogg
sound/custom_monsters/zombie/claw_miss2.ogg
sound/custom_monsters/zombie/claw_strike1.ogg
sound/custom_monsters/zombie/claw_strike2.ogg
sound/custom_monsters/zombie/claw_strike3.ogg
sound/custom_monsters/zombie/zo_alert10.ogg
sound/custom_monsters/zombie/zo_alert20.ogg
sound/custom_monsters/zombie/zo_alert30.ogg
sound/custom_monsters/zombie/zo_attack1.ogg
sound/custom_monsters/zombie/zo_attack2.ogg
sound/custom_monsters/zombie/zo_idle1.ogg
sound/custom_monsters/zombie/zo_idle2.ogg
sound/custom_monsters/zombie/zo_idle3.ogg
sound/custom_monsters/zombie/zo_idle4.ogg
sound/custom_monsters/zombie/zo_pain1.ogg
sound/custom_monsters/zombie/zo_pain2.ogg
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/st_allies/crimson_commando/alert.ogg
sound/st_allies/crimson_commando/area.ogg
sound/st_allies/crimson_commando/ass.ogg
sound/st_allies/crimson_commando/babysitting.ogg
sound/st_allies/crimson_commando/backup.ogg
sound/st_allies/crimson_commando/bfeeling.ogg
sound/st_allies/crimson_commando/bogies.ogg
sound/st_allies/crimson_commando/charge.ogg
sound/st_allies/crimson_commando/check.ogg
sound/st_allies/crimson_commando/checkrecon.ogg
sound/st_allies/crimson_commando/chicken.ogg
sound/st_allies/crimson_commando/clear.ogg
sound/st_allies/crimson_commando/command.ogg
sound/st_allies/crimson_commando/corners.ogg
sound/st_allies/crimson_commando/corporal.ogg
sound/st_allies/crimson_commando/corporal_01.ogg
sound/st_allies/crimson_commando/cover.ogg
sound/st_allies/crimson_commando/covering.ogg
sound/st_allies/crimson_commando/coverup.ogg
sound/st_allies/crimson_commando/current.ogg
sound/st_allies/crimson_commando/damage.ogg
sound/st_allies/crimson_commando/death1.ogg
sound/st_allies/crimson_commando/death2.ogg
sound/st_allies/crimson_commando/death3.ogg
sound/st_allies/crimson_commando/disney.ogg
sound/st_allies/crimson_commando/dogs.ogg
sound/st_allies/crimson_commando/down.ogg
sound/st_allies/crimson_commando/flank.ogg
sound/st_allies/crimson_commando/freaks.ogg
sound/st_allies/crimson_commando/friendly.ogg
sound/st_allies/crimson_commando/fubar.ogg
sound/st_allies/crimson_commando/getsome.ogg
sound/st_allies/crimson_commando/go.ogg
sound/st_allies/crimson_commando/gotit.ogg
sound/st_allies/crimson_commando/gr_pain1.ogg
sound/st_allies/crimson_commando/gr_pain2.ogg
sound/st_allies/crimson_commando/gr_pain3.ogg
sound/st_allies/crimson_commando/gr_pain4.ogg
sound/st_allies/crimson_commando/grenade.ogg
sound/st_allies/crimson_commando/guard.ogg
sound/st_allies/crimson_commando/guardduty.ogg
sound/st_allies/crimson_commando/hellosir.ogg
sound/st_allies/crimson_commando/hellout.ogg
sound/st_allies/crimson_commando/hitbad.ogg
sound/st_allies/crimson_commando/hostiles.ogg
sound/st_allies/crimson_commando/imhit.ogg
sound/st_allies/crimson_commando/incoming.ogg
sound/st_allies/crimson_commando/lost.ogg
sound/st_allies/crimson_commando/marines.ogg
sound/st_allies/crimson_commando/mission.ogg
sound/st_allies/crimson_commando/mister.ogg
sound/st_allies/crimson_commando/move.ogg
sound/st_allies/crimson_commando/moveup.ogg
sound/st_allies/crimson_commando/moving.ogg
sound/st_allies/crimson_commando/no.ogg
sound/st_allies/crimson_commando/notfail.ogg
sound/st_allies/crimson_commando/now.ogg
sound/st_allies/crimson_commando/oneshot.ogg
sound/st_allies/crimson_commando/orders.ogg
sound/st_allies/crimson_commando/outof.ogg
sound/st_allies/crimson_commando/pain1.ogg
sound/st_allies/crimson_commando/pain2.ogg
sound/st_allies/crimson_commando/pain3.ogg
sound/st_allies/crimson_commando/pain4.ogg
sound/st_allies/crimson_commando/quiet.ogg
sound/st_allies/crimson_commando/rapidfire.ogg
sound/st_allies/crimson_commando/recon.ogg
sound/st_allies/crimson_commando/right.ogg
sound/st_allies/crimson_commando/roger.ogg
sound/st_allies/crimson_commando/scout.ogg
sound/st_allies/crimson_commando/secure.ogg
sound/st_allies/crimson_commando/seensquad.ogg
sound/st_allies/crimson_commando/short.ogg
sound/st_allies/crimson_commando/six.ogg
sound/st_allies/crimson_commando/sniper.ogg
sound/st_allies/crimson_commando/suppressing.ogg
sound/st_allies/crimson_commando/sweep.ogg
sound/st_allies/crimson_commando/tag.ogg
sound/st_allies/crimson_commando/take.ogg
sound/st_allies/crimson_commando/talking.ogg
sound/st_allies/crimson_commando/wantsome.ogg
sound/st_allies/crimson_commando/watchfire.ogg
sound/st_allies/crimson_commando/watchit.ogg
sound/st_allies/crimson_commando/yes.ogg
sound/st_allies/crimson_commando/zone.ogg
sound/st_mission/22noice2.ogg
sound/st_mission/angelic_energy.ogg
sound/st_mission/events/hs_c4/a_grabdagger.ogg
sound/st_mission/events/hs_c4/distant_angel_shadows.ogg
sound/st_mission/events/hs_c4/distant_angel_shoot.ogg
sound/st_mission/events/hs_c4/distant_angel_warp.ogg
sound/st_mission/events/hs_c4/distant_demon_attack.ogg
sound/st_mission/events/hs_c4/distant_demon_dash.ogg
sound/st_mission/events/hs_c4/distant_displace.ogg
sound/st_mission/events/hs_c4/distant_explosion.ogg
sound/st_mission/events/hs_c4/warp_in.ogg
sound/st_mission/rain1.ogg
sound/st_mission/rain_inside.ogg
sound/st_mission/rain_window.ogg
sound/st_mission/thunder1.ogg
sound/st_mission/thunder2.ogg
sound/st_mission/thunder3.ogg
sound/st_mission/thunder4.ogg
sound/st_mission/weapons/m60-fire1.ogg
sound/st_mission/weapons/sbarrel1.ogg
sound/st_mission/weapons/spas12/dbarrel1.ogg
sound/st_mission/weapons/spas12/sbarrel1.ogg
sound/st_mission/weapons/spas12/scock1.ogg
sound/st_mission/weapons/xm8-fire.ogg
sound/st_mission/wind2.ogg
sprites/c-tele1_blu.spr
sprites/singularity/prtl/kz_exit1.spr
