// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

9.wad
aomreal.wad
bigcity2.wad
cs_office.wad
hs.wad
models/custom_monsters/agrunt/agrunt_demon.mdl
models/custom_monsters/agrunt/agrunt_demon01.mdl
models/custom_monsters/bullsquid/mistakesquid.mdl
models/custom_monsters/bullsquid/mistakesquid01.mdl
models/custom_monsters/bullsquid/mistakesquidt.mdl
models/custom_monsters/gonome/praetorian.mdl
models/custom_monsters/pitdrone/helldrone.mdl
models/custom_monsters/titans/titanskull.mdl
models/custom_monsters/zombie/dagadt.mdl
models/custom_monsters/zombie/lpzombie.mdl
models/custom_monsters/zombie/szombie.mdl
models/custom_monsters/zombie/szombiet.mdl
models/custom_monsters/zombie/zombie_crowbar.mdl
models/st_allies/civilian.mdl
models/st_allies/dead_hev.mdl
models/st_allies/dead_hevt.mdl
models/st_allies/security_grunt.mdl
models/st_allies/sgrunt.mdl
models/st_mission1/backpack_bio.mdl
models/st_mission1/backpack_fate.mdl
models/st_mission1/biobomb.mdl
models/st_mission1/blackhawk_down.mdl
models/st_mission1/c4.mdl
models/st_mission1/eatencorpse.mdl
models/st_mission1/props/AA_LOD_Breach_01_CMZ_SMesh.mdl
models/st_mission1/props/bigbush.mdl
models/st_mission1/props/cheap_police_sedan2.mdl
models/st_mission1/props/cheap_wrecked_sedan_white.mdl
models/st_mission1/props/gutspile.mdl
models/st_mission1/props/trash2.mdl
models/st_mission1/props/trash4.mdl
models/st_mission1/props/tree1.mdl
models/st_mission1/props/tree2.mdl
models/st_mission1/props/wrecked_car_brown.mdl
models/st_mission1/researcher_corpse.mdl
models/st_mission1/w_isotopebox_bio.mdl
models/st_mission1/w_isotopebox_biot.mdl
models/st_mission1/w_longjump.mdl
models/st_mission1/weapons_classic/p_biolauncher.mdl
models/st_mission1/weapons_classic/v_357.mdl
models/st_mission1/weapons_classic/v_9mmar.mdl
models/st_mission1/weapons_classic/v_9mmhandgun.mdl
models/st_mission1/weapons_classic/v_biolauncher.mdl
models/st_mission1/weapons_classic/v_crossbow.mdl
models/st_mission1/weapons_classic/v_crowbar.mdl
models/st_mission1/weapons_classic/v_displacer.mdl
models/st_mission1/weapons_classic/v_eagle.mdl
models/st_mission1/weapons_classic/v_egon.mdl
models/st_mission1/weapons_classic/v_gauss.mdl
models/st_mission1/weapons_classic/v_grenade.mdl
models/st_mission1/weapons_classic/v_m40a1.mdl
models/st_mission1/weapons_classic/v_medkit.mdl
models/st_mission1/weapons_classic/v_pipe_wrench.mdl
models/st_mission1/weapons_classic/v_rpg.mdl
models/st_mission1/weapons_classic/v_satchel.mdl
models/st_mission1/weapons_classic/v_satchel_radio.mdl
models/st_mission1/weapons_classic/v_saw.mdl
models/st_mission1/weapons_classic/v_shotgun.mdl
models/st_mission1/weapons_classic/v_squeak.mdl
models/st_mission1/weapons_classic/v_tripmine.mdl
models/st_mission1/weapons_classic/v_uzi.mdl
siege_apc.wad
sound/custom_monsters/spitter/bc_acid1.wav
sound/custom_monsters/spitter/bc_acid2.wav
sound/custom_monsters/spitter/bc_attack1.wav
sound/custom_monsters/spitter/bc_attack2.wav
sound/custom_monsters/spitter/bc_attack3.wav
sound/custom_monsters/spitter/bc_attackgrowl.wav
sound/custom_monsters/spitter/bc_attackgrowl2.wav
sound/custom_monsters/spitter/bc_attackgrowl3.wav
sound/custom_monsters/spitter/bc_bite1.wav
sound/custom_monsters/spitter/bc_bite2.wav
sound/custom_monsters/spitter/bc_bite3.wav
sound/custom_monsters/spitter/bc_die1.wav
sound/custom_monsters/spitter/bc_die2.wav
sound/custom_monsters/spitter/bc_die3.wav
sound/custom_monsters/spitter/bc_idle1.wav
sound/custom_monsters/spitter/bc_idle2.wav
sound/custom_monsters/spitter/bc_idle3.wav
sound/custom_monsters/spitter/bc_idle4.wav
sound/custom_monsters/spitter/bc_idle5.wav
sound/custom_monsters/spitter/bc_pain1.wav
sound/custom_monsters/spitter/bc_pain2.wav
sound/custom_monsters/spitter/bc_pain3.wav
sound/custom_monsters/spitter/bc_pain4.wav
sound/custom_monsters/spitter/bc_spithit1.wav
sound/custom_monsters/spitter/bc_spithit2.wav
sound/custom_monsters/spitter/bc_spithit3.wav
sound/custom_monsters/zombie/claw_miss1.wav
sound/custom_monsters/zombie/claw_miss2.wav
sound/custom_monsters/zombie/claw_strike1.wav
sound/custom_monsters/zombie/claw_strike2.wav
sound/custom_monsters/zombie/claw_strike3.wav
sound/custom_monsters/zombie/zo_alert10.wav
sound/custom_monsters/zombie/zo_alert20.wav
sound/custom_monsters/zombie/zo_alert30.wav
sound/custom_monsters/zombie/zo_attack1.wav
sound/custom_monsters/zombie/zo_attack2.wav
sound/custom_monsters/zombie/zo_idle1.wav
sound/custom_monsters/zombie/zo_idle2.wav
sound/custom_monsters/zombie/zo_idle3.wav
sound/custom_monsters/zombie/zo_idle4.wav
sound/custom_monsters/zombie/zo_pain1.wav
sound/custom_monsters/zombie/zo_pain2.wav
sound/kezaeiv/misc/teleport.wav
sound/oghs/misc/cp02_03.mp3
sound/st_mission/22noice2.wav
sound/st_mission/events/hs_c4/distant_angel_shadows.wav
sound/st_mission/events/hs_c4/distant_angel_shoot.wav
sound/st_mission/events/hs_c4/distant_angel_warp.wav
sound/st_mission/events/hs_c4/distant_demon_attack.wav
sound/st_mission/events/hs_c4/distant_demon_dash.wav
sound/st_mission/events/hs_c4/distant_displace.wav
sound/st_mission/events/hs_c4/distant_explosion.wav
sound/st_mission/rain1.wav
sound/st_mission/rain_window.wav
sound/st_mission/thunder1.wav
sound/st_mission/thunder2.wav
sound/st_mission/thunder3.wav
sound/st_mission/thunder4.wav
sound/st_mission/weapons/spas12/dbarrel1.wav
sound/st_mission/weapons/spas12/sbarrel1.wav
sound/st_mission/weapons/spas12/scock1.wav
sound/st_mission/wind2.wav
sprites/kezaeiv/prtl/kz_exit1.spr
