// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/player/babaalien_kezaeiv/babaalien_kezaeiv.bmp
models/player/babaalien_kezaeiv/babaalien_kezaeiv.mdl
models/player/babarobo_kezaeiv/babarobo_kezaeiv.bmp
models/player/babarobo_kezaeiv/babarobo_kezaeiv.mdl
models/player/blackhelmet/blackhelmet.bmp
models/player/blackhelmet/blackhelmet.mdl
models/player/braixen/braixen.bmp
models/player/braixen/braixen.mdl
models/player/cheems/cheems.bmp
models/player/cheems/cheems.mdl
models/player/colette_cyan&white/colette_cyan&white.bmp
models/player/colette_cyan&white/colette_cyan&white.mdl
models/player/hololive_fubuki/hololive_fubuki.bmp
models/player/hololive_fubuki/hololive_fubuki.mdl
models/player/iiotoko/iiotoko.bmp
models/player/iiotoko/iiotoko.mdl
models/player/lucario_p_mega/lucario_p_mega.bmp
models/player/lucario_p_mega/lucario_p_mega.mdl
models/player/lucario_p_mega2/lucario_p_mega2.bmp
models/player/lucario_p_mega2/lucario_p_mega2.mdl
models/player/lycanroc/lycanroc.bmp
models/player/lycanroc/lycanroc.mdl
models/player/petdrone/petdrone.mdl
models/player/shockroach_kez/shockroach_kez.mdl
models/player/spenguin/spenguin.bmp
models/player/spenguin/spenguin.mdl
models/player/sw_cinderace_c/sw_cinderace_c.bmp
models/player/sw_cinderace_c/sw_cinderace_c.mdl
models/player/weaponbox/weaponbox.mdl
sound/kezaeiv/misc/teleport.wav
sound/oghs/cs06/!.wav
sound/oghs/cs06/1812.wav
sound/oghs/cs06/1mas.wav
sound/oghs/cs06/321.wav
sound/oghs/cs06/a!!.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/aaah.wav
sound/oghs/cs06/aagh.wav
sound/oghs/cs06/ab.wav
sound/oghs/cs06/aboose.wav
sound/oghs/cs06/aea.wav
sound/oghs/cs06/afk.wav
sound/oghs/cs06/again.wav
sound/oghs/cs06/agh.wav
sound/oghs/cs06/aha!.wav
sound/oghs/cs06/ahaha.wav
sound/oghs/cs06/ahh.wav
sound/oghs/cs06/ahhh.wav
sound/oghs/cs06/ahhhh.wav
sound/oghs/cs06/ahhnoo.wav
sound/oghs/cs06/ahorasi.wav
sound/oghs/cs06/alab.wav
sound/oghs/cs06/allimite.wav
sound/oghs/cs06/alo.wav
sound/oghs/cs06/alo2.wav
sound/oghs/cs06/ambience.wav
sound/oghs/cs06/apura.wav
sound/oghs/cs06/armonb.wav
sound/oghs/cs06/asi.wav
sound/oghs/cs06/asumareb.wav
sound/oghs/cs06/au.wav
sound/oghs/cs06/avisa.wav
sound/oghs/cs06/ay!.wav
sound/oghs/cs06/ay.wav
sound/oghs/cs06/ayaya.wav
sound/oghs/cs06/aynob.wav
sound/oghs/cs06/ayuda.wav
sound/oghs/cs06/ayuda2.wav
sound/oghs/cs06/ayuda3b.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/banana.wav
sound/oghs/cs06/barney.wav
sound/oghs/cs06/bees.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/benny.wav
sound/oghs/cs06/better.wav
sound/oghs/cs06/bhop.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/bonk.wav
sound/oghs/cs06/boom.wav
sound/oghs/cs06/boom2.wav
sound/oghs/cs06/br0leg.wav
sound/oghs/cs06/brainfart.wav
sound/oghs/cs06/bruh.wav
sound/oghs/cs06/bruhmomento.wav
sound/oghs/cs06/bugibugi.wav
sound/oghs/cs06/burro.wav
sound/oghs/cs06/cacaeres.wav
sound/oghs/cs06/cachado2.wav
sound/oghs/cs06/cagon.wav
sound/oghs/cs06/calla.wav
sound/oghs/cs06/calla2c.wav
sound/oghs/cs06/callense.wav
sound/oghs/cs06/caos.wav
sound/oghs/cs06/car.wav
sound/oghs/cs06/cave1.wav
sound/oghs/cs06/cave2.wav
sound/oghs/cs06/cerra.wav
sound/oghs/cs06/chad.wav
sound/oghs/cs06/chipib.wav
sound/oghs/cs06/cholo.wav
sound/oghs/cs06/chupapinga.wav
sound/oghs/cs06/clr.wav
sound/oghs/cs06/coletemurio.wav
sound/oghs/cs06/coleterage2.wav
sound/oghs/cs06/comemelculo.wav
sound/oghs/cs06/comenten.wav
sound/oghs/cs06/corre.wav
sound/oghs/cs06/corre2.wav
sound/oghs/cs06/correct.wav
sound/oghs/cs06/crabrave.wav
sound/oghs/cs06/crazy2.wav
sound/oghs/cs06/cries.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/curame.wav
sound/oghs/cs06/cyka.wav
sound/oghs/cs06/death.wav
sound/oghs/cs06/dementia.wav
sound/oghs/cs06/denied.wav
sound/oghs/cs06/dfac.wav
sound/oghs/cs06/dies.wav
sound/oghs/cs06/dmg.wav
sound/oghs/cs06/doctor.wav
sound/oghs/cs06/dominating.wav
sound/oghs/cs06/doorstuck.wav
sound/oghs/cs06/double.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/dross2.wav
sound/oghs/cs06/dross3.wav
sound/oghs/cs06/dross4.wav
sound/oghs/cs06/dude.wav
sound/oghs/cs06/duke1.wav
sound/oghs/cs06/duke2.wav
sound/oghs/cs06/elcp.wav
sound/oghs/cs06/endgame.wav
sound/oghs/cs06/ending.wav
sound/oghs/cs06/english.wav
sound/oghs/cs06/ensuboca.wav
sound/oghs/cs06/esakk.wav
sound/oghs/cs06/eseaudio.wav
sound/oghs/cs06/estupido.wav
sound/oghs/cs06/explosion.wav
sound/oghs/cs06/fack.wav
sound/oghs/cs06/fack2.wav
sound/oghs/cs06/fail.wav
sound/oghs/cs06/fall.wav
sound/oghs/cs06/fall2.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/ffs.wav
sound/oghs/cs06/fight1.wav
sound/oghs/cs06/filha.wav
sound/oghs/cs06/finale.wav
sound/oghs/cs06/fix.wav
sound/oghs/cs06/flip.wav
sound/oghs/cs06/freebird.wav
sound/oghs/cs06/frenzy.wav
sound/oghs/cs06/fuckhim.wav
sound/oghs/cs06/gameover.wav
sound/oghs/cs06/gane.wav
sound/oghs/cs06/gasgasgas.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/gay2.wav
sound/oghs/cs06/getpranked.wav
sound/oghs/cs06/gib.wav
sound/oghs/cs06/gnomob.wav
sound/oghs/cs06/go.wav
sound/oghs/cs06/god.wav
sound/oghs/cs06/gracias.wav
sound/oghs/cs06/gracias2.wav
sound/oghs/cs06/granadab.wav
sound/oghs/cs06/green2.wav
sound/oghs/cs06/gta.wav
sound/oghs/cs06/haha.wav
sound/oghs/cs06/hahaha.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/hellouda.wav
sound/oghs/cs06/help.wav
sound/oghs/cs06/helphelp.wav
sound/oghs/cs06/helpme.wav
sound/oghs/cs06/hi.wav
sound/oghs/cs06/hijos.wav
sound/oghs/cs06/hmhaha.wav
sound/oghs/cs06/holyshit.wav
sound/oghs/cs06/how.wav
sound/oghs/cs06/huah.wav
sound/oghs/cs06/huh.wav
sound/oghs/cs06/humiliation.wav
sound/oghs/cs06/hype.wav
sound/oghs/cs06/imbeciles.wav
sound/oghs/cs06/imgonna.wav
sound/oghs/cs06/imkillingyou.wav
sound/oghs/cs06/impressive.wav
sound/oghs/cs06/inc.wav
sound/oghs/cs06/inc3.wav
sound/oghs/cs06/instinct.wav
sound/oghs/cs06/interesante.wav
sound/oghs/cs06/irn.wav
sound/oghs/cs06/itried.wav
sound/oghs/cs06/jackiechan.wav
sound/oghs/cs06/jajaja.wav
sound/oghs/cs06/jajaxd.wav
sound/oghs/cs06/juega.wav
sound/oghs/cs06/jumpscare.wav
sound/oghs/cs06/juyjuyjuy.wav
sound/oghs/cs06/kaleun.wav
sound/oghs/cs06/kick.wav
sound/oghs/cs06/kidding.wav
sound/oghs/cs06/kidding2.wav
sound/oghs/cs06/killingspree.wav
sound/oghs/cs06/killme.wav
sound/oghs/cs06/l8r.wav
sound/oghs/cs06/laconcha.wav
sound/oghs/cs06/lag.wav
sound/oghs/cs06/laputa.wav
sound/oghs/cs06/larecagaron.wav
sound/oghs/cs06/lastone.wav
sound/oghs/cs06/lodijo.wav
sound/oghs/cs06/logibio.wav
sound/oghs/cs06/loviste.wav
sound/oghs/cs06/macizo.wav
sound/oghs/cs06/mamahuevo.wav
sound/oghs/cs06/mariachi.wav
sound/oghs/cs06/masdespacio.wav
sound/oghs/cs06/mata.wav
sound/oghs/cs06/maxwell.wav
sound/oghs/cs06/meahogob.wav
sound/oghs/cs06/mecaigo2.wav
sound/oghs/cs06/mecaigob.wav
sound/oghs/cs06/meconfundib.wav
sound/oghs/cs06/medarisab.wav
sound/oghs/cs06/medic.wav
sound/oghs/cs06/medico.wav
sound/oghs/cs06/mefregaste.wav
sound/oghs/cs06/megibio.wav
sound/oghs/cs06/memori.wav
sound/oghs/cs06/metacomiendo.wav
sound/oghs/cs06/mevoy.wav
sound/oghs/cs06/mevoyb.wav
sound/oghs/cs06/mierda.wav
sound/oghs/cs06/mihuevo.wav
sound/oghs/cs06/miralo.wav
sound/oghs/cs06/mire.wav
sound/oghs/cs06/missioncompletada.wav
sound/oghs/cs06/monsterkill.wav
sound/oghs/cs06/moriparao.wav
sound/oghs/cs06/move.wav
sound/oghs/cs06/moyai.wav
sound/oghs/cs06/mrwhite1.wav
sound/oghs/cs06/muchavidab.wav
sound/oghs/cs06/mueromucho.wav
sound/oghs/cs06/muted.wav
sound/oghs/cs06/mylife.wav
sound/oghs/cs06/nep.wav
sound/oghs/cs06/nicetry.wav
sound/oghs/cs06/no.wav
sound/oghs/cs06/no2.wav
sound/oghs/cs06/no3.wav
sound/oghs/cs06/noaab.wav
sound/oghs/cs06/noasomen.wav
sound/oghs/cs06/nodesinforme.wav
sound/oghs/cs06/noice.wav
sound/oghs/cs06/nollego.wav
sound/oghs/cs06/nomeatrapas.wav
sound/oghs/cs06/nooo.wav
sound/oghs/cs06/nuclearmissionb.wav
sound/oghs/cs06/nya.wav
sound/oghs/cs06/oemrd.wav
sound/oghs/cs06/oguo.wav
sound/oghs/cs06/oh.wav
sound/oghs/cs06/ohfuck.wav
sound/oghs/cs06/ohno.wav
sound/oghs/cs06/okletsgo.wav
sound/oghs/cs06/ola.wav
sound/oghs/cs06/omg.wav
sound/oghs/cs06/omg2.wav
sound/oghs/cs06/omnom.wav
sound/oghs/cs06/onichan.wav
sound/oghs/cs06/oogh.wav
sound/oghs/cs06/oops.wav
sound/oghs/cs06/ownage.wav
sound/oghs/cs06/oww.wav
sound/oghs/cs06/panico.wav
sound/oghs/cs06/papus.wav
sound/oghs/cs06/peerreview.wav
sound/oghs/cs06/perreo.wav
sound/oghs/cs06/peru.wav
sound/oghs/cs06/peru2.wav
sound/oghs/cs06/peru3.wav
sound/oghs/cs06/pingu.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pit.wav
sound/oghs/cs06/pit2b.wav
sound/oghs/cs06/pootis.wav
sound/oghs/cs06/porno.wav
sound/oghs/cs06/prepare.wav
sound/oghs/cs06/pucutu.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/pum.wav
sound/oghs/cs06/punch.wav
sound/oghs/cs06/pwnd.wav
sound/oghs/cs06/pyro.wav
sound/oghs/cs06/qbajob.wav
sound/oghs/cs06/qfeocpb.wav
sound/oghs/cs06/qhacenb.wav
sound/oghs/cs06/qhaces.wav
sound/oghs/cs06/qpasob.wav
sound/oghs/cs06/quad.wav
sound/oghs/cs06/quemepegas.wav
sound/oghs/cs06/quitate.wav
sound/oghs/cs06/quitate2.wav
sound/oghs/cs06/rampage.wav
sound/oghs/cs06/rdy.wav
sound/oghs/cs06/rec.wav
sound/oghs/cs06/restart.wav
sound/oghs/cs06/retarded.wav
sound/oghs/cs06/revb.wav
sound/oghs/cs06/revive.wav
sound/oghs/cs06/revive2.wav
sound/oghs/cs06/riko.wav
sound/oghs/cs06/rip.wav
sound/oghs/cs06/run.wav
sound/oghs/cs06/rushittingme.wav
sound/oghs/cs06/sad.wav
sound/oghs/cs06/sadistic.wav
sound/oghs/cs06/sau.wav
sound/oghs/cs06/saved.wav
sound/oghs/cs06/scaped.wav
sound/oghs/cs06/scream.wav
sound/oghs/cs06/scream2.wav
sound/oghs/cs06/sex.wav
sound/oghs/cs06/shockb.wav
sound/oghs/cs06/si.wav
sound/oghs/cs06/sick.wav
sound/oghs/cs06/sisepuede.wav
sound/oghs/cs06/sisyphus.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/sniper.wav
sound/oghs/cs06/sorry.wav
sound/oghs/cs06/soyese.wav
sound/oghs/cs06/soygod.wav
sound/oghs/cs06/soyun.wav
sound/oghs/cs06/spanish.wav
sound/oghs/cs06/spook.wav
sound/oghs/cs06/spook2.wav
sound/oghs/cs06/spook3.wav
sound/oghs/cs06/spookd.wav
sound/oghs/cs06/srs.wav
sound/oghs/cs06/stfu.wav
sound/oghs/cs06/stfu2.wav
sound/oghs/cs06/stfu3.wav
sound/oghs/cs06/stupid.wav
sound/oghs/cs06/suck.wav
sound/oghs/cs06/suicide.wav
sound/oghs/cs06/surprise.wav
sound/oghs/cs06/sus.wav
sound/oghs/cs06/tarado.wav
sound/oghs/cs06/tecagaste.wav
sound/oghs/cs06/tecrees.wav
sound/oghs/cs06/tensionb.wav
sound/oghs/cs06/terror.wav
sound/oghs/cs06/tevio.wav
sound/oghs/cs06/tevoya.wav
sound/oghs/cs06/texto.wav
sound/oghs/cs06/thisdude.wav
sound/oghs/cs06/timewaste.wav
sound/oghs/cs06/tmr.wav
sound/oghs/cs06/tmr2.wav
sound/oghs/cs06/tom1.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/tom3.wav
sound/oghs/cs06/toma.wav
sound/oghs/cs06/tooez.wav
sound/oghs/cs06/tp.wav
sound/oghs/cs06/triple.wav
sound/oghs/cs06/trololo.wav
sound/oghs/cs06/tuvieja.wav
sound/oghs/cs06/ty.wav
sound/oghs/cs06/tyler1.wav
sound/oghs/cs06/ufo.wav
sound/oghs/cs06/ugly.wav
sound/oghs/cs06/uhh.wav
sound/oghs/cs06/uhoh.wav
sound/oghs/cs06/ultrakill.wav
sound/oghs/cs06/unshockb.wav
sound/oghs/cs06/unstoppable.wav
sound/oghs/cs06/uvu.wav
sound/oghs/cs06/uy2.wav
sound/oghs/cs06/uyb.wav
sound/oghs/cs06/vajguar.wav
sound/oghs/cs06/vamos.wav
sound/oghs/cs06/ven.wav
sound/oghs/cs06/vete.wav
sound/oghs/cs06/violacion.wav
sound/oghs/cs06/vortalcombat.wav
sound/oghs/cs06/voya.wav
sound/oghs/cs06/waiting.wav
sound/oghs/cs06/wakeup.wav
sound/oghs/cs06/watch.wav
sound/oghs/cs06/weewee.wav
sound/oghs/cs06/what.wav
sound/oghs/cs06/whatiswrongwithyou.wav
sound/oghs/cs06/whistle.wav
sound/oghs/cs06/why.wav
sound/oghs/cs06/woah.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/wtf2.wav
sound/oghs/cs06/wtf3.wav
sound/oghs/cs06/wtf4.wav
sound/oghs/cs06/yallege.wav
sound/oghs/cs06/yatata.wav
sound/oghs/cs06/yay.wav
sound/oghs/cs06/yes.wav
sound/oghs/cs06/yes2.wav
sound/oghs/cs06/yipe.wav
sound/oghs/cs06/zombies.wav
sound/oghs/cs06/zurdos.wav
sound/oghs/cs06/zzz.wav
sound/oghs/cs06/zzz2.wav
sound/oghs/misc/cp02_03.mp3
sprites/kezaeiv/prtl/kz_exit1.spr
