// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/med_crategibs.mdl
Models/tech_crategibs.mdl
models/hlclassic/p_desert_eagle.mdl
models/hlclassic/p_m40a1.mdl
models/hlclassic/p_saw.mdl
models/hlclassic/saw_shell.mdl
models/hlclassic/v_desert_eagle.mdl
models/hlclassic/v_m40a1.mdl
models/hlclassic/v_saw.mdl
models/hlclassic/w_desert_eagle.mdl
models/hlclassic/w_m40a1.mdl
models/hlclassic/w_m40a1clip.mdl
models/hlclassic/w_saw.mdl
models/hlclassic/w_saw_clip.mdl
models/kezaeiv/icons/mk_logo_cyan.mdl
models/kezaeiv/kof/npc/agrunt.mdl
models/kezaeiv/kof/npc/agruntf.mdl
models/kezaeiv/kof/npc/apache.mdl
models/kezaeiv/kof/npc/apachef.mdl
models/kezaeiv/kof/npc/baby_voltigore.mdl
models/kezaeiv/kof/npc/babygarg.mdl
models/kezaeiv/kof/npc/babygargf.mdl
models/kezaeiv/kof/npc/barnabushev.mdl
models/kezaeiv/kof/npc/barneyhev.mdl
models/kezaeiv/kof/npc/bgman.mdl
models/kezaeiv/kof/npc/bullsquid.mdl
models/kezaeiv/kof/npc/chubby.mdl
models/kezaeiv/kof/npc/chumtoad.mdl
models/kezaeiv/kof/npc/controller.mdl
models/kezaeiv/kof/npc/gonome.mdl
models/kezaeiv/kof/npc/hassassin.mdl
models/kezaeiv/kof/npc/hassassinf.mdl
models/kezaeiv/kof/npc/headcrab.mdl
models/kezaeiv/kof/npc/hgrunt.mdl
models/kezaeiv/kof/npc/hgrunt_medic.mdl
models/kezaeiv/kof/npc/hgrunt_medicf.mdl
models/kezaeiv/kof/npc/hgrunt_opfor.mdl
models/kezaeiv/kof/npc/hgrunt_opforf.mdl
models/kezaeiv/kof/npc/hgrunt_torch.mdl
models/kezaeiv/kof/npc/hgruntf.mdl
models/kezaeiv/kof/npc/houndeye.mdl
models/kezaeiv/kof/npc/hwgrunt.mdl
models/kezaeiv/kof/npc/hwgruntf.mdl
models/kezaeiv/kof/npc/islave.mdl
models/kezaeiv/kof/npc/islavef.mdl
models/kezaeiv/kof/npc/kingpin.mdl
models/kezaeiv/kof/npc/massn.mdl
models/kezaeiv/kof/npc/massnf.mdl
models/kezaeiv/kof/npc/osprey.mdl
models/kezaeiv/kof/npc/ospreyf.mdl
models/kezaeiv/kof/npc/otis.mdl
models/kezaeiv/kof/npc/otisf.mdl
models/kezaeiv/kof/npc/p_minigunidle.mdl
models/kezaeiv/kof/npc/p_minigunspin.mdl
models/kezaeiv/kof/npc/pit_drone.mdl
models/kezaeiv/kof/npc/rgrunt.mdl
models/kezaeiv/kof/npc/rgruntf.mdl
models/kezaeiv/kof/npc/strooper.mdl
models/kezaeiv/kof/npc/tor.mdl
models/kezaeiv/kof/npc/torf.mdl
models/kezaeiv/kof/npc/v_minigun.mdl
models/kezaeiv/kof/npc/v_minigunblueshift.mdl
models/kezaeiv/kof/npc/v_minigunopfor.mdl
models/kezaeiv/kof/npc/voltigore.mdl
models/kezaeiv/kof/npc/w_minigun.mdl
models/kezaeiv/kof/npc/zombie.mdl
models/kezaeiv/kof/npc/zombie_barney.mdl
models/kezaeiv/kof/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
sound/../sound/kezaeiv/misc/cp_nod_reinf.mp3
sound/hlclassic/weapons/desert_eagle_reload.wav
sound/hlclassic/weapons/saw_reload.wav
sound/hlclassic/weapons/saw_reload2.wav
sound/hlclassic/weapons/sniper_bolt1.wav
sound/hlclassic/weapons/sniper_bolt2.wav
sound/hlclassic/weapons/sniper_fire.wav
sound/hlclassic/weapons/sniper_reload_first_seq.wav
sound/hlclassic/weapons/sniper_reload_second_seq.wav
sound/kezaeiv/misc/teleport.wav
sound/kezaeiv/singularity/npc/csgo_deag_shot.wav
sound/kezaeiv/singularity/npc/dusk_shotgun_shot.wav
sound/kezaeiv/singularity/npc/exp1.wav
sound/kezaeiv/singularity/npc/exp3.wav
sound/kezaeiv/singularity/npc/exp5.wav
sound/kezaeiv/singularity/npc/hgrunt_3shot.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit1.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit2.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit3.wav
sound/kezaeiv/singularity/npc/igi2_dragunov_shot.wav
sound/kezaeiv/singularity/npc/igi2_g36_shot.wav
sound/kezaeiv/singularity/npc/quake3_grenade_shot.wav
sound/kezaeiv/singularity/npc/quake4_plasma_shot.wav
sound/kezaeiv/singularity/npc/starcraft_ghost_rifle.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sprites/hl_weapons//weapon_hlpython.txt
sprites/hl_weapons//weapon_ofeagle.txt
sprites/hl_weapons//weapon_ofm249.txt
sprites/hl_weapons//weapon_ofshockrifle.txt
sprites/hl_weapons//weapon_ofsniperrifle.txt
sprites/kezaeiv/prtl/kz_exit1.spr
