// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/snglrt_outspace_bk.tga
gfx/env/snglrt_outspace_dn.tga
gfx/env/snglrt_outspace_ft.tga
gfx/env/snglrt_outspace_lf.tga
gfx/env/snglrt_outspace_rt.tga
gfx/env/snglrt_outspace_up.tga
kez_singularity.wad
kz_snglrt_sky.wad
models/kezaeiv/kof/npc/ragh_aknah.mdl
models/singularity/c_weps/misc/laser_stick_bl.mdl
models/singularity/c_weps/misc/laser_stick_grn.mdl
models/singularity/c_weps/misc/laser_stick_prpl2.mdl
models/singularity/c_weps/misc/laser_stick_red.mdl
models/singularity/misc/kz_mxa_box.mdl
models/singularity/misc/rockgibs_lightrock.mdl
sound/singularity/c_wep/ammo/pku_ammo4.wav
sound/singularity/c_wep/ehve/roach_blast.wav
sound/singularity/c_wep/hblst/hb_beam_shot.wav
sound/singularity/c_wep/misc/enrg_hit.wav
sound/singularity/c_wep/xl2/xl2_shot.wav
sound/singularity/door/keyinserted.wav
sound/singularity/kof/ragh_aknah/atack1.wav
sound/singularity/kof/ragh_aknah/hurt2.wav
sound/singularity/kof/ragh_aknah/hurt3.wav
sound/singularity/kof/ragh_aknah/hurt4.wav
sound/singularity/kof/ragh_aknah/taunt.wav
sound/singularity/misc/kleerofski_laugh2.wav
sound/singularity/misc/kleerofski_laugh3.wav
sound/singularity/misc/kleerofski_laugh5.wav
sound/singularity/misc/nova_charge.wav
sound/singularity/misc/shockwave.wav
sound/singularity/misc/ss2_nade.wav
sound/singularity/misc/victory.wav
sound/singularity/music/trbslsh_drug.ogg
sound/singularity/music/trbslsh_lostconnection.ogg
sound/singularity/null.wav
sprites/singularity/fx/b-tele_prpl_bl.spr
sprites/singularity/fx/b-tele_prpl_pk.spr
sprites/singularity/fx/laser_crshr.spr
sprites/singularity/fx/strchs_sr_exp.spr
sprites/singularity/prtl/kz_exit2.spr
sprites/singularity/prtl/kz_exit4.spr
sprites/singularity/prtl/kz_exit6.spr
