// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/burgbk.tga
gfx/env/burgdn.tga
gfx/env/burgft.tga
gfx/env/burglf.tga
gfx/env/burgrt.tga
gfx/env/burgup.tga
models/sadpuppy/a2/puppy_originals/giga.mdl
models/sadpuppy/a2/puppy_originals/giga_pillar.mdl
models/sadpuppy/a2/puppy_originals/puppy_gigatext.mdl
models/sadpuppy/a2/puppy_originals/puppy_grats.mdl
models/sadpuppy/a2/puppy_originals/puppy_puppy.mdl
models/sadpuppy/a2/puppy_originals/puppy_sign6.mdl
models/sadpuppy/a2/puppy_originals/puppy_the_end.mdl
models/sadpuppy/a2/signs/mappers/oldschool_map_by_sadpuppy2.mdl
models/sadpuppy/a2/signs/puppymaps/area18_3.mdl
models/sadpuppy/a2/signs/puppymaps/blockrunner7.mdl
models/sadpuppy/a2/signs/puppymaps/canyon6.mdl
models/sadpuppy/a2/signs/puppymaps/corruo1.mdl
models/sadpuppy/a2/signs/puppymaps/godspeed7.mdl
models/sadpuppy/a2/signs/puppymaps/ljcomplex1.mdl
models/sadpuppy/a2/signs/puppymaps/novus3.mdl
models/sadpuppy/a2/signs/puppymaps/prisonyard2.mdl
models/sadpuppy/a2/signs/puppymaps/puppycademy5.mdl
models/sadpuppy/a2/signs/puppymaps/templearena3.mdl
models/sadpuppy/characters/animals/insects/dragonfly.mdl
models/sadpuppy/characters/humans/dead/dead1.mdl
models/sadpuppy/characters/skulls/skeleton.mdl
models/sadpuppy/characters/statues/guardian_statue.mdl
models/sadpuppy/characters/statues/khtulhu.mdl
models/sadpuppy/characters/statues/lion.mdl
models/sadpuppy/characters/statues/q3gargoyle.mdl
models/sadpuppy/characters/statues/wik_gatx8.mdl
models/sadpuppy/characters/statues/wik_gax.mdl
models/sadpuppy/characters/statues/wik_gmn.mdl
models/sadpuppy/counter/counterflag.mdl
models/sadpuppy/egypt/anubis.mdl
models/sadpuppy/egypt/egypt_dog1.mdl
models/sadpuppy/nature/bushes/bush5.mdl
models/sadpuppy/nature/bushes/bush6.mdl
models/sadpuppy/nature/rocks/rock2.mdl
models/sadpuppy/objects/fire/torchh.mdl
models/sadpuppy/objects/misc/sun_clock.mdl
models/sadpuppy/stations/ut2exit.mdl
sound/ambience/sadpuppy/computers/nost_Compa.wav
sound/ambience/sadpuppy/fire/fire.wav
sound/ambience/sadpuppy/water/waterstream.wav
sound/sadpuppy/gigablockier/end_room_loop___sw_throne_room.ogg
sound/sadpuppy/gigablockier/lvl_100___running.ogg
sound/sadpuppy/gigablockier/lvl_10_short___loca.ogg
sound/sadpuppy/gigablockier/lvl_20___on_the_run.ogg
sound/sadpuppy/gigablockier/lvl_32view___es_candle.ogg
sound/sadpuppy/gigablockier/lvl_4041___wasp_revengeance.ogg
sound/sadpuppy/gigablockier/lvl_49___f242_headhunter.ogg
sound/sadpuppy/gigablockier/lvl_5658___run_it.ogg
sound/sadpuppy/gigablockier/lvl_66___mk_annihilation.ogg
sound/sadpuppy/gigablockier/lvl_7475___f_everytime.ogg
sound/sadpuppy/gigablockier/lvl_83___y_oh_yeah.ogg
sound/sadpuppy/gigablockier/lvl_96___mr_myers.ogg
sound/sadpuppy/gigablockier/nice_lady___eq_voice.ogg
sound/sadpuppy/gigablockier/startbutton_enter_giga.ogg
sound/sadpuppy/gigablockier/startpos___wnl_selection.ogg
sound/sadpuppy/gigablockier/templeroom___to_the_stars.ogg
sprites/sadpuppy/42/digits/2013/redc05x.spr
sprites/sadpuppy/42/digits/2013/redc09x.spr
sprites/sadpuppy/carma_tele1.spr
sprites/sadpuppy/z-locked/d2_impaled.spr
sprites/sadpuppy/z-locked/d2_techlight3.spr
sprites/sadpuppy/z-locked/dead_fire.spr
sprites/sadpuppy/z-locked/flare2.spr
sprites/sadpuppy/z-locked/prioryflame.spr
