// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

MODELS/ABONE_Template1.mdl
MODELS/BSKULL_Template1.mdl
MODELS/PELVIS.mdl
MODELS/RIBCAGE.mdl
MODELS/Riblet1.mdl
MODELS/ZOMBIEGibs1.mdl
models/cubemath/chars/d6.mdl
models/cubemath/chars/percent.mdl
models/cubemath/key.mdl
models/cubemath/padlock.mdl
models/kezaeiv/icons/mk_logo_blue.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn.mdl
models/oghs/cm/npc/massnf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/Tor.mdl
sound/ambience/liftmuzak.wav
sound/epone/music/In.mp3
sound/oghs/cs/!.wav
sound/oghs/cs/1812.wav
sound/oghs/cs/321.wav
sound/oghs/cs/90s.wav
sound/oghs/cs/a!.wav
sound/oghs/cs/again.wav
sound/oghs/cs/ahaha.wav
sound/oghs/cs/ambience.wav
sound/oghs/cs/bell.wav
sound/oghs/cs/bhop.wav
sound/oghs/cs/boing.wav
sound/oghs/cs/bonk.wav
sound/oghs/cs/boom.wav
sound/oghs/cs/calladawn.wav
sound/oghs/cs/carson.wav
sound/oghs/cs/chad.wav
sound/oghs/cs/correct.wav
sound/oghs/cs/crabrave.wav
sound/oghs/cs/crazy.wav
sound/oghs/cs/cries1.wav
sound/oghs/cs/crit.wav
sound/oghs/cs/csm.wav
sound/oghs/cs/cum.wav
sound/oghs/cs/curb.wav
sound/oghs/cs/cykablyat.wav
sound/oghs/cs/damage.wav
sound/oghs/cs/damnn.wav
sound/oghs/cs/dawei.wav
sound/oghs/cs/dejavu.wav
sound/oghs/cs/denied.wav
sound/oghs/cs/dontyou.wav
sound/oghs/cs/doorstuck.wav
sound/oghs/cs/doot.wav
sound/oghs/cs/dross.wav
sound/oghs/cs/drums.wav
sound/oghs/cs/endgame.wav
sound/oghs/cs/ending.wav
sound/oghs/cs/enemy.wav
sound/oghs/cs/english.wav
sound/oghs/cs/explosion.wav
sound/oghs/cs/ez.wav
sound/oghs/cs/fail.wav
sound/oghs/cs/failiture.wav
sound/oghs/cs/fall.wav
sound/oghs/cs/fall2.wav
sound/oghs/cs/fart.wav
sound/oghs/cs/ffs.wav
sound/oghs/cs/finale.wav
sound/oghs/cs/flute.wav
sound/oghs/cs/fool.wav
sound/oghs/cs/freebird.wav
sound/oghs/cs/gasgasgas.wav
sound/oghs/cs/gay.wav
sound/oghs/cs/getpranked.wav
sound/oghs/cs/gib.wav
sound/oghs/cs/gta.wav
sound/oghs/cs/headshot.wav
sound/oghs/cs/help.wav
sound/oghs/cs/hostiles.wav
sound/oghs/cs/houndeye.wav
sound/oghs/cs/how.wav
sound/oghs/cs/huegh.wav
sound/oghs/cs/iamthestorm.wav
sound/oghs/cs/imbeciles.wav
sound/oghs/cs/impressive.wav
sound/oghs/cs/itried.wav
sound/oghs/cs/jajaja.wav
sound/oghs/cs/kaleun.wav
sound/oghs/cs/knock.wav
sound/oghs/cs/l8r.wav
sound/oghs/cs/lastone.wav
sound/oghs/cs/mariachi.wav
sound/oghs/cs/move.wav
sound/oghs/cs/moyai.wav
sound/oghs/cs/mylife.wav
sound/oghs/cs/noice.wav
sound/oghs/cs/nuclearmission.wav
sound/oghs/cs/oww.wav
sound/oghs/cs/panico.wav
sound/oghs/cs/papus.wav
sound/oghs/cs/pingu.wav
sound/oghs/cs/pipe.wav
sound/oghs/cs/pizzatime.wav
sound/oghs/cs/prepare.wav
sound/oghs/cs/pui.wav
sound/oghs/cs/pum.wav
sound/oghs/cs/pwnd.wav
sound/oghs/cs/quad.wav
sound/oghs/cs/restart.wav
sound/oghs/cs/revive.wav
sound/oghs/cs/riders.wav
sound/oghs/cs/rip.wav
sound/oghs/cs/sad.wav
sound/oghs/cs/scaped.wav
sound/oghs/cs/sisyphus.wav
sound/oghs/cs/slip.wav
sound/oghs/cs/snail.wav
sound/oghs/cs/sniper.wav
sound/oghs/cs/sorry.wav
sound/oghs/cs/spanish.wav
sound/oghs/cs/spook.wav
sound/oghs/cs/spookd.wav
sound/oghs/cs/stfu.wav
sound/oghs/cs/stfu2.wav
sound/oghs/cs/sueltame.wav
sound/oghs/cs/surprise.wav
sound/oghs/cs/sus.wav
sound/oghs/cs/tension.wav
sound/oghs/cs/terror.wav
sound/oghs/cs/tevoya.wav
sound/oghs/cs/texto.wav
sound/oghs/cs/thebest.wav
sound/oghs/cs/tom1.wav
sound/oghs/cs/tom2.wav
sound/oghs/cs/train.wav
sound/oghs/cs/waiting.wav
sound/oghs/cs/wakeup.wav
sound/oghs/cs/weewee.wav
sound/oghs/cs/why.wav
sound/oghs/cs/wrong.wav
sound/oghs/cs/wtf1.wav
sound/oghs/cs/wtf2.wav
sound/oghs/cs/wtfboom.wav
sound/oghs/cs/yay.wav
sound/oghs/cs/yeahbaby.wav
sound/oghs/cs/yesyes.wav
sound/oghs/cs/yipe.wav
sound/oghs/cs/zzz.wav
sound/oghs/cs02/au.wav
sound/oghs/cs02/ay!.wav
sound/oghs/cs02/ayuda.wav
sound/oghs/cs02/banana.wav
sound/oghs/cs02/beanos.wav
sound/oghs/cs02/bees.wav
sound/oghs/cs02/benny.wav
sound/oghs/cs02/boss.wav
sound/oghs/cs02/bruh.wav
sound/oghs/cs02/burro.wav
sound/oghs/cs02/calla.wav
sound/oghs/cs02/callate.wav
sound/oghs/cs02/car.wav
sound/oghs/cs02/carrot.wav
sound/oghs/cs02/chaos.wav
sound/oghs/cs02/city.wav
sound/oghs/cs02/corre.wav
sound/oghs/cs02/dies.wav
sound/oghs/cs02/dominating.wav
sound/oghs/cs02/double.wav
sound/oghs/cs02/fix.wav
sound/oghs/cs02/flip.wav
sound/oghs/cs02/gangsta.wav
sound/oghs/cs02/god.wav
sound/oghs/cs02/gracias.wav
sound/oghs/cs02/hellouda.wav
sound/oghs/cs02/holyshit.wav
sound/oghs/cs02/huh.wav
sound/oghs/cs02/juega.wav
sound/oghs/cs02/kick.wav
sound/oghs/cs02/killingspree.wav
sound/oghs/cs02/laconcha.wav
sound/oghs/cs02/lag.wav
sound/oghs/cs02/lcdtm.wav
sound/oghs/cs02/macizo.wav
sound/oghs/cs02/mata.wav
sound/oghs/cs02/miralo.wav
sound/oghs/cs02/monsterkill.wav
sound/oghs/cs02/muted.wav
sound/oghs/cs02/oh.wav
sound/oghs/cs02/ohno.wav
sound/oghs/cs02/omg.wav
sound/oghs/cs02/peru.wav
sound/oghs/cs02/pipe.wav
sound/oghs/cs02/punch.wav
sound/oghs/cs02/pyro.wav
sound/oghs/cs02/rampage.wav
sound/oghs/cs02/retard.wav
sound/oghs/cs02/retarded.wav
sound/oghs/cs02/saved.wav
sound/oghs/cs02/scream.wav
sound/oghs/cs02/sex.wav
sound/oghs/cs02/stahp.wav
sound/oghs/cs02/terminator.wav
sound/oghs/cs02/thisdude.wav
sound/oghs/cs02/tp.wav
sound/oghs/cs02/triple.wav
sound/oghs/cs02/tyler1.wav
sound/oghs/cs02/ufo.wav
sound/oghs/cs02/ultra.wav
sound/oghs/cs02/ultrakill.wav
sound/oghs/cs02/unstoppable.wav
sound/oghs/cs02/uvu.wav
sound/oghs/cs02/vamos.wav
sound/oghs/cs02/ven.wav
sound/oghs/cs02/vete.wav
sound/oghs/cs02/wafn.wav
sound/oghs/cs02/watch.wav
sound/oghs/cs02/xtremesex.wav
sound/oghs/cs02/zurdos.wav
sound/oghs/cs03/aboose.wav
sound/oghs/cs03/badbone.wav
sound/oghs/cs03/beanos.wav
sound/oghs/cs03/bruhmomento.wav
sound/oghs/cs03/cerra.wav
sound/oghs/cs03/cries.wav
sound/oghs/cs03/dementia.wav
sound/oghs/cs03/elcp.wav
sound/oghs/cs03/ensuboca.wav
sound/oghs/cs03/fight1.wav
sound/oghs/cs03/fuckhim.wav
sound/oghs/cs03/gameover.wav
sound/oghs/cs03/gib2.wav
sound/oghs/cs03/gotem.wav
sound/oghs/cs03/green.wav
sound/oghs/cs03/green2.wav
sound/oghs/cs03/hype.wav
sound/oghs/cs03/instinct.wav
sound/oghs/cs03/interesante.wav
sound/oghs/cs03/loviste.wav
sound/oghs/cs03/memori.wav
sound/oghs/cs03/metacomiendo.wav
sound/oghs/cs03/mueromucho.wav
sound/oghs/cs03/nonono.wav
sound/oghs/cs03/nooo.wav
sound/oghs/cs03/perreo.wav
sound/oghs/cs03/pit.wav
sound/oghs/cs03/prepare.wav
sound/oghs/cs03/quemepegas.wav
sound/oghs/cs03/soyun.wav
sound/oghs/cs03/stupid.wav
sound/oghs/cs03/tecrees.wav
sound/oghs/cs03/tevio.wav
sound/oghs/cs03/tuvieja.wav
sound/oghs/cs03/uwu.wav
