// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/kezaeiv/icons/mk_logo_orange.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/barnabus.mdl
models/oghs/cm/npc/crashed_osprey.mdl
models/oghs/cm/npc/gman.mdl
models/oghs/cm/npc/gonome.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn2.mdl
models/oghs/cm/npc/massnf2.mdl
models/oghs/cm/npc/osprey.mdl
models/oghs/cm/npc/osprey2.mdl
models/oghs/cm/npc/ospreyf.mdl
models/oghs/cm/npc/otis.mdl
models/oghs/cm/npc/otisf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/tor2.mdl
models/oghs/cm/npc/zombie_barney.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_minigun.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
models/residuallife/aworker.mdl
models/residuallife/cleansuit_scientist.mdl
models/residuallife/dissected_headcrab.mdl
models/residuallife/gonome.mdl
models/residuallife/hassassin.mdl
models/residuallife/scientist.mdl
models/residuallife/skeleton2_.mdl
models/residuallife/w_bloodly_9mmAR.mdl
models/residuallife/w_suit.mdl
models/residuallife/zgrunt.mdl
rl_.wad
sound/oghs/cs07/ahhhh.wav
sound/oghs/cs07/ala.wav
sound/oghs/cs07/bell.wav
sound/oghs/cs07/boing.wav
sound/oghs/cs07/cave1.wav
sound/oghs/cs07/csm.wav
sound/oghs/cs07/dies.wav
sound/oghs/cs07/dross.wav
sound/oghs/cs07/fack2.wav
sound/oghs/cs07/fah.wav
sound/oghs/cs07/fart.wav
sound/oghs/cs07/gay.wav
sound/oghs/cs07/nooo.wav
sound/oghs/cs07/oogh.wav
sound/oghs/cs07/pipe.wav
sound/oghs/cs07/pluh.wav
sound/oghs/cs07/pui.wav
sound/oghs/cs07/rip2.wav
sound/oghs/cs07/slip.wav
sound/oghs/cs07/toma.wav
sound/oghs/cs07/vine.wav
sound/oghs/misc/cp02_03.mp3
sound/residuallife/barney/ba_late.wav
sound/residuallife/barney/ba_security2_desk0.wav
sound/residuallife/barney/s02ba_hello.wav
sound/residuallife/barney/s02ba_pl_door.wav
sound/residuallife/barney/sk02_ba_headdown.wav
sound/residuallife/debris/a_teleport.wav
sound/residuallife/fgrunt/ok03b_fg01.wav
sound/residuallife/fvox/inject1.wav
sound/residuallife/gman/gman_intro_talk0.wav
sound/residuallife/gman/intro_gman_tulk1a.wav
sound/residuallife/gman/intro_gman_tulk1b.wav
sound/residuallife/ngrunt/ng_idle0.wav
sound/residuallife/ngrunt/ng_idle1.wav
sound/residuallife/ngrunt/ng_idle2.wav
sound/residuallife/ngrunt/ng_idle3.wav
sound/residuallife/residual_materials.txt
sound/residuallife/scientist/dk01_sci_talk.wav
sound/residuallife/scientist/sc_crazer.wav
sound/singularity/misc/teleport.wav
sprites/gst/extra.spr
sprites/gst/spritefont1.spr
sprites/singularity/prtl/kz_exit1.spr
