// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/cm_v3/otis.mdl
models/cm_v3/zombie_barney.mdl
models/cm_v3/zombie_soldier.mdl
models/cubemath/arrow2d.mdl
models/cubemath/skull.mdl
models/mikk/hlclassic/massn.mdl
models/mikk/misc/limitless_potential.mdl
models/mikk/monsters/zombie_hev.mdl
models/mikk/residualpoint/aworker.mdl
models/mikk/residualpoint/hgrunt_opfor.mdl
models/mikk/residualpoint/hlclassic/aworker.mdl
models/mikk/residualpoint/hlclassic/hgrunt_opfor.mdl
models/mikk/residualpoint/hlclassic/ngrunt.mdl
models/mikk/residualpoint/hlclassic/w_bloodly_9mmar.mdl
models/mikk/residualpoint/hlclassic/w_bloodly_shotgun.mdl
models/mikk/residualpoint/hlclassic/xenocrab.mdl
models/mikk/residualpoint/hlclassic/zgrunt.mdl
models/mikk/residualpoint/level_change.spr
models/mikk/residualpoint/ngrunt.mdl
models/mikk/residualpoint/w_bloodly_9mmar.mdl
models/mikk/residualpoint/w_bloodly_shotgun.mdl
models/mikk/residualpoint/xenocrab.mdl
models/mikk/residualpoint/zgrunt.mdl
models/mikk/weapons/v_teleporter.mdl
models/mikk/weapons/w_teleporter.mdl
models/portalgun/p_portalgun.mdl
models/portalgun/portal.mdl
models/portalgun/v_portalgun.mdl
models/portalgun/w_portalgun.mdl
rplobbyv2.wad
sound/mikk/music/jazy_intro.mp3
sound/mikk/music/permadeath.mp3
sound/mikk/residualpoint/barney/ba_late.wav
sound/mikk/residualpoint/barney/ba_security2_desk0.wav
sound/mikk/residualpoint/barney/ok03x_ba_topside.wav
sound/mikk/residualpoint/barney/s02ba_hello.wav
sound/mikk/residualpoint/barney/s02ba_pl_door.wav
sound/mikk/residualpoint/barney/sk02_ba_headdown.wav
sound/mikk/residualpoint/fgrunt/ok03b_fg01.wav
sound/mikk/residualpoint/otis/of1a1_ot0.wav
sound/mikk/residualpoint/otis/of1a1_ot2.wav
sound/mikk/residualpoint/scientist/dk01_sci_talk.wav
sound/mikk/residualpoint/scientist/sci_portopen.wav
sound/portalgun/portal_close1.wav
sound/portalgun/portal_close2.wav
sound/portalgun/portal_enter1.wav
sound/portalgun/portal_enter2.wav
sound/portalgun/portal_invalid_surface3.wav
sound/portalgun/portal_open1.wav
sound/portalgun/portal_open2.wav
sound/portalgun/portal_open3.wav
sound/portalgun/portalgun_shoot_blue1.wav
sound/portalgun/portalgun_shoot_orange1.wav
sound/weapons/weapon_draw.wav
sprites/kezaeiv/kezammo_v2.spr
sprites/kezaeiv/kezcrosshairs.spr
sprites/kezaeiv/kweps_vanil.spr
sprites/kezaeiv/kweps_vanil_slct.spr
sprites/portalgun/nieb.spr
sprites/portalgun/pom.spr
sprites/portalgun/portalgunhud.spr
sprites/portalgun/portalgunxhair.spr
sprites/portalgun/weapon_portalgun.txt
