// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/mountainpassbk.tga
gfx/env/mountainpassdn.tga
gfx/env/mountainpassft.tga
gfx/env/mountainpasslf.tga
gfx/env/mountainpassrt.tga
gfx/env/mountainpassup.tga
models/kezaeiv/kz_npcs/snglrt2/strooper_red_violent.mdl
models/sc_cyclone/APC.mdl
models/sc_cyclone/audi80.mdl
models/sc_cyclone/baby_voltigore_pink.mdl
models/sc_cyclone/bil1.mdl
models/sc_cyclone/hevcharge_wall.mdl
models/sc_cyclone/medkit_wall.mdl
models/sc_cyclone/Truckrussian.mdl
sc_cyclone.wad
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/sc_cyclone/blue.ogg
sound/sc_cyclone/buttonpower.wav
sound/sc_cyclone/buzzer_pipe1.wav
sound/sc_cyclone/buzzer_wind3.wav
sound/sc_cyclone/cat.wav
sound/sc_cyclone/comp3.wav
sound/sc_cyclone/computer_beeps.wav
sound/sc_cyclone/Explo_metal01.wav
sound/sc_cyclone/grate_close.wav
sound/sc_cyclone/high_wind1.wav
sound/sc_cyclone/moveon.wav
sound/sc_cyclone/objecdone.wav
sound/sc_cyclone/securityalarm.wav
sound/singularity/misc/teleport.wav
sound/weapons/spas12_foley.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
sprites/sc_cyclone/prok.spr
sprites/singularity/prtl/kz_exit1.spr
