// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Models/garbagegibs.mdl
Models/med_crategibs.mdl
Models/tech_crategibs.mdl
models/sc_strangers/diablo.mdl
models/sc_strangers/gonome.mdl
models/sc_strangers/Helldrone.mdl
models/sc_strangers/islave.mdl
sound/oghs/cs07/ahhhh.wav
sound/oghs/cs07/ala.wav
sound/oghs/cs07/bell.wav
sound/oghs/cs07/boing.wav
sound/oghs/cs07/cave1.wav
sound/oghs/cs07/csm.wav
sound/oghs/cs07/dies.wav
sound/oghs/cs07/dross.wav
sound/oghs/cs07/fack2.wav
sound/oghs/cs07/fah.wav
sound/oghs/cs07/fart.wav
sound/oghs/cs07/gay.wav
sound/oghs/cs07/nooo.wav
sound/oghs/cs07/oogh.wav
sound/oghs/cs07/pipe.wav
sound/oghs/cs07/pluh.wav
sound/oghs/cs07/pui.wav
sound/oghs/cs07/rip2.wav
sound/oghs/cs07/slip.wav
sound/oghs/cs07/toma.wav
sound/oghs/cs07/vine.wav
sound/oghs/misc/cp02_03.mp3
sound/sc_strangers/panther/p_alert1.wav
sound/sc_strangers/panther/p_alert2.wav
sound/sc_strangers/panther/p_alert3.wav
sound/sc_strangers/panther/p_die1.wav
sound/sc_strangers/panther/p_die2.wav
sound/sc_strangers/panther/p_idle1.wav
sound/sc_strangers/panther/p_idle2.wav
sound/sc_strangers/panther/p_idle3.wav
sound/sc_strangers/panther/p_pain1.wav
sound/sc_strangers/panther/p_pain2.wav
sound/sc_strangers/panther/p_zap1.wav
sound/sc_strangers/panther/p_zap2.wav
sound/sc_strangers/ripandtear.ogg
sound/singularity/misc/teleport.wav
sprites/singularity/prtl/kz_exit1.spr
