// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/cs16_flashx.txt
events/cso/muzzle_ethereal.txt
events/cso/muzzle_m95.txt
events/cso/muzzle_qbarrel.txt
events/muzzle_balrog9.txt
events/muzzle_fvulcan1.txt
events/muzzle_fvulcan2.txt
events/muzzle_plasmagun.txt
gfx/env/londonbk.tga
gfx/env/londondn.tga
gfx/env/londonft.tga
gfx/env/londonlf.tga
gfx/env/londonrt.tga
gfx/env/londonup.tga
models/cs16/shells/pshell.mdl
models/cs16/shells/rshell.mdl
models/cs16/shells/rshell_big.mdl
models/cs16/wpn/scope.mdl
models/cso/floating_damage.mdl
models/cso_edit/at4ex/p_at4ex.mdl
models/cso_edit/at4ex/v_at4ex.mdl
models/cso_edit/at4ex/v_at4ex_scope.mdl
models/cso_edit/at4ex/w_at4ex.mdl
models/cso_edit/clip_savery.mdl
models/cso_edit/cs16/57/p_57.mdl
models/cso_edit/cs16/57/v_57.mdl
models/cso_edit/cs16/57/w_57.mdl
models/cso_edit/cs16/ak47/p_ak47.mdl
models/cso_edit/cs16/ak47/v_ak47.mdl
models/cso_edit/cs16/ak47/w_ak47.mdl
models/cso_edit/cs16/ammo/mags.mdl
models/cso_edit/cs16/c4/p_c4.mdl
models/cso_edit/cs16/c4/v_c4.mdl
models/cso_edit/cs16/c4/w_bp.mdl
models/cso_edit/cs16/c4/w_c4.mdl
models/cso_edit/cs16/eagle/p_eagle.mdl
models/cso_edit/cs16/eagle/v_eagle.mdl
models/cso_edit/cs16/eagle/w_eagle.mdl
models/cso_edit/cs16/he/p_he.mdl
models/cso_edit/cs16/he/v_he.mdl
models/cso_edit/cs16/he/w_he.mdl
models/cso_edit/cs16/he/w_he2.mdl
models/cso_edit/cs16/knf/p_knife.mdl
models/cso_edit/cs16/knf/v_knife.mdl
models/cso_edit/cs16/knf/w_knife.mdl
models/cso_edit/cs16/m4a1/p_m4a1.mdl
models/cso_edit/cs16/m4a1/v_m4a1.mdl
models/cso_edit/cs16/m4a1/w_m4a1.mdl
models/cso_edit/cs16/mp5/p_mp5.mdl
models/cso_edit/cs16/mp5/v_mp5.mdl
models/cso_edit/cs16/mp5/w_mp5.mdl
models/cso_edit/cs16/w_762natobox_big.mdl
models/cso_edit/desperado/p_desperado_m.mdl
models/cso_edit/desperado/p_desperado_w.mdl
models/cso_edit/desperado/v_desperado.mdl
models/cso_edit/desperado/w_desperado.mdl
models/cso_edit/desperado/w_desperado_ammo.mdl
models/cso_edit/dualsword_skill.mdl
models/cso_edit/dualsword_skillfx1.mdl
models/cso_edit/dualsword_skillfx2.mdl
models/cso_edit/dualswordfx.mdl
models/cso_edit/ef_gundrop.mdl
models/cso_edit/ef_scorpion_hole.mdl
models/cso_edit/ethereal/p_ethereal.mdl
models/cso_edit/ethereal/v_ethereal.mdl
models/cso_edit/ethereal/w_etherammo.mdl
models/cso_edit/ethereal/w_ethereal.mdl
models/cso_edit/gunkata/ef_gunkata.mdl
models/cso_edit/gunkata/ef_gunkata_man.mdl
models/cso_edit/gunkata/ef_gunkata_woman.mdl
models/cso_edit/gunkata/p_gunkata.mdl
models/cso_edit/gunkata/v_gunkata.mdl
models/cso_edit/gunkata/w_gunkata.mdl
models/cso_edit/gunkata/w_gunkata_ammo.mdl
models/cso_edit/m95/p_m95.mdl
models/cso_edit/m95/v_m95.mdl
models/cso_edit/m95/w_m95.mdl
models/cso_edit/mag_ak47.mdl
models/cso_edit/mag_csocrossbow.mdl
models/cso_edit/p_balrog9.mdl
models/cso_edit/p_dualsword_a.mdl
models/cso_edit/p_dualsword_b.mdl
models/cso_edit/p_firevulcan.mdl
models/cso_edit/p_m3.mdl
models/cso_edit/p_m400.mdl
models/cso_edit/p_m79.mdl
models/cso_edit/p_m82.mdl
models/cso_edit/p_mk3a1.mdl
models/cso_edit/p_plasmagun.mdl
models/cso_edit/p_qbarrel.mdl
models/cso_edit/p_savery.mdl
models/cso_edit/plasmashell.mdl
models/cso_edit/pshell.mdl
models/cso_edit/rpgrocket.mdl
models/cso_edit/rshell_big.mdl
models/cso_edit/shell_savery.mdl
models/cso_edit/shell_svdex.mdl
models/cso_edit/shell_svdex2.mdl
models/cso_edit/shotgunshell2.mdl
models/cso_edit/sniper_ammo.mdl
models/cso_edit/sniper_ammo2.mdl
models/cso_edit/v_balrog9.mdl
models/cso_edit/v_dualsword.mdl
models/cso_edit/v_firevulcan.mdl
models/cso_edit/v_m3.mdl
models/cso_edit/v_m400.mdl
models/cso_edit/v_m79.mdl
models/cso_edit/v_m82.mdl
models/cso_edit/v_mk3a1.mdl
models/cso_edit/v_plasmagun.mdl
models/cso_edit/v_qbarrel.mdl
models/cso_edit/v_savery.mdl
models/cso_edit/w_45acp.mdl
models/cso_edit/w_50bmg.mdl
models/cso_edit/w_balrog9.mdl
models/cso_edit/w_dualsword.mdl
models/cso_edit/w_firevulcan.mdl
models/cso_edit/w_m3.mdl
models/cso_edit/w_m400.mdl
models/cso_edit/w_m79.mdl
models/cso_edit/w_m82.mdl
models/cso_edit/w_mk3a1.mdl
models/cso_edit/w_plasmagun.mdl
models/cso_edit/w_qbarrel.mdl
models/cso_edit/w_savery.mdl
models/cso_edit/w_shotbox.mdl
models/cso_edit/w_shotbox2.mdl
models/kezaeiv/icons/mk_logo_orange.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/barnabus.mdl
models/oghs/cm/npc/crashed_osprey.mdl
models/oghs/cm/npc/gman.mdl
models/oghs/cm/npc/gonome.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn2.mdl
models/oghs/cm/npc/massnf2.mdl
models/oghs/cm/npc/osprey.mdl
models/oghs/cm/npc/osprey2.mdl
models/oghs/cm/npc/ospreyf.mdl
models/oghs/cm/npc/otis.mdl
models/oghs/cm/npc/otisf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/tor2.mdl
models/oghs/cm/npc/zombie_barney.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_minigunidle.mdl
models/oghs/cm/wep/p_minigunspin.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_minigun.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_minigun.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
models/tower/parachute_sven.mdl
sound/cs16/57/magin.wav
sound/cs16/57/magout.wav
sound/cs16/57/shoot.wav
sound/cs16/57/sldbk.wav
sound/cs16/57/sldrl.wav
sound/cs16/ak47/bltbk.wav
sound/cs16/ak47/magin.wav
sound/cs16/ak47/magout.wav
sound/cs16/c4/beep.wav
sound/cs16/c4/click.wav
sound/cs16/c4/plant.wav
sound/cs16/eagle/magin.wav
sound/cs16/eagle/magout.wav
sound/cs16/eagle/shoot.wav
sound/cs16/he/bounce.wav
sound/cs16/he/pin.wav
sound/cs16/knf/hit1.wav
sound/cs16/knf/hit2.wav
sound/cs16/knf/hit3.wav
sound/cs16/knf/hit4.wav
sound/cs16/knf/stab.wav
sound/cs16/knf/wall.wav
sound/cs16/m249/shoot.wav
sound/cs16/m4a1/bltbk.wav
sound/cs16/m4a1/draw.wav
sound/cs16/m4a1/magin.wav
sound/cs16/m4a1/magout.wav
sound/cs16/m4a1/shoot.wav
sound/cs16/m4a1/siloff.wav
sound/cs16/m4a1/silon.wav
sound/cs16/misc/emptyp.wav
sound/cs16/misc/emptyr.wav
sound/cs16/misc/zoom.wav
sound/cs16/mp5/magin.wav
sound/cs16/mp5/magout.wav
sound/cs16/mp5/shoot.wav
sound/cs16/mp5/sldbk.wav
sound/cs16/scout/shoot.wav
sound/cs16/xm1014/shoot.wav
sound/cso_edit/at4-1.wav
sound/cso_edit/at4_clipin1.wav
sound/cso_edit/at4_clipin2.wav
sound/cso_edit/at4_clipin3.wav
sound/cso_edit/at4_draw.wav
sound/cso_edit/awp_deploy.wav
sound/cso_edit/balrog9_charge_attack.wav
sound/cso_edit/balrog9_charge_finish.wav
sound/cso_edit/balrog9_charge_start.wav
sound/cso_edit/balrog9_draw.wav
sound/cso_edit/balrog9_hit1.wav
sound/cso_edit/balrog9_hit2.wav
sound/cso_edit/balrog9_slash1.wav
sound/cso_edit/balrog9_slash2.wav
sound/cso_edit/balrog9_slash3.wav
sound/cso_edit/balrog9_slash4.wav
sound/cso_edit/balrog9_slash5.wav
sound/cso_edit/boltup.wav
sound/cso_edit/cs16/57/magin.wav
sound/cso_edit/cs16/57/magout.wav
sound/cso_edit/cs16/57/shoot.wav
sound/cso_edit/cs16/57/sldbk.wav
sound/cso_edit/cs16/57/sldrl.wav
sound/cso_edit/cs16/ak47/shoot.wav
sound/cso_edit/cs16/c4/bombpl.wav
sound/cso_edit/cs16/c4/boom.wav
sound/cso_edit/cs16/dryfire_rifle.wav
sound/cso_edit/cs16/eagle/magin.wav
sound/cso_edit/cs16/eagle/magout.wav
sound/cso_edit/cs16/he/throw.wav
sound/cso_edit/cs16/knf/draw.wav
sound/cso_edit/cs16/knf/swg1.wav
sound/cso_edit/cs16/knf/swg2.wav
sound/cso_edit/cs16/m4a1/shoot2.wav
sound/cso_edit/cs16/m4a1/siloff.wav
sound/cso_edit/dprd-1.wav
sound/cso_edit/dprd_reload_m.wav
sound/cso_edit/dryfire_pistol.wav
sound/cso_edit/dryfire_rifle.wav
sound/cso_edit/dualsword_fly1.wav
sound/cso_edit/dualsword_fly2.wav
sound/cso_edit/dualsword_fly3.wav
sound/cso_edit/dualsword_fly4.wav
sound/cso_edit/dualsword_fly5.wav
sound/cso_edit/dualsword_hit1.wav
sound/cso_edit/dualsword_hit2.wav
sound/cso_edit/dualsword_hit3.wav
sound/cso_edit/dualsword_idle_a.wav
sound/cso_edit/dualsword_idle_b.wav
sound/cso_edit/dualsword_skill_end.wav
sound/cso_edit/dualsword_skill_loop_end.wav
sound/cso_edit/dualsword_skill_start.wav
sound/cso_edit/dualsword_slash_1.wav
sound/cso_edit/dualsword_slash_2.wav
sound/cso_edit/dualsword_slash_3.wav
sound/cso_edit/dualsword_slash_4.wav
sound/cso_edit/dualsword_slash_4_1.wav
sound/cso_edit/dualsword_slash_4_2.wav
sound/cso_edit/dualsword_slash_end.wav
sound/cso_edit/dualsword_stab1.wav
sound/cso_edit/dualsword_stab1_hit.wav
sound/cso_edit/dualsword_stab2.wav
sound/cso_edit/dualsword_stab2_hit.wav
sound/cso_edit/dualsword_stab_end.wav
sound/cso_edit/ethereal-1.wav
sound/cso_edit/ethereal_draw.wav
sound/cso_edit/ethereal_reload.wav
sound/cso_edit/gatling_boltpull.wav
sound/cso_edit/gatling_clipin1.wav
sound/cso_edit/gatling_clipin2.wav
sound/cso_edit/gatling_clipout1.wav
sound/cso_edit/gatling_clipout2.wav
sound/cso_edit/gatlingm-1.wav
sound/cso_edit/gunkata-1.wav
sound/cso_edit/gunkata_draw.wav
sound/cso_edit/gunkata_draw2.wav
sound/cso_edit/gunkata_reload.wav
sound/cso_edit/gunkata_reload2.wav
sound/cso_edit/gunkata_skill_01.wav
sound/cso_edit/gunkata_skill_02.wav
sound/cso_edit/gunkata_skill_03.wav
sound/cso_edit/gunkata_skill_04.wav
sound/cso_edit/gunkata_skill_05.wav
sound/cso_edit/gunkata_skill_last.wav
sound/cso_edit/gunkata_skill_last_exp.wav
sound/cso_edit/m3-1.wav
sound/cso_edit/m3_insertshell.wav
sound/cso_edit/m3_pump.wav
sound/cso_edit/m400-1.wav
sound/cso_edit/m400_clipin.wav
sound/cso_edit/m400_clipout.wav
sound/cso_edit/m400_foley1.wav
sound/cso_edit/m400_foley2.wav
sound/cso_edit/m79-1.wav
sound/cso_edit/m79_clipin.wav
sound/cso_edit/m79_clipon.wav
sound/cso_edit/m79_clipout.wav
sound/cso_edit/m79_draw.wav
sound/cso_edit/m82-1.wav
sound/cso_edit/m82_clipin1.wav
sound/cso_edit/m82_clipin2.wav
sound/cso_edit/m82_clipout1.wav
sound/cso_edit/m82_clipout2.wav
sound/cso_edit/m95-1.wav
sound/cso_edit/m95_boltpull.wav
sound/cso_edit/m95_clipin.wav
sound/cso_edit/m95_clipout.wav
sound/cso_edit/mastercombat_wall.wav
sound/cso_edit/mk3a1-1.wav
sound/cso_edit/mk3a1_clipin1.wav
sound/cso_edit/mk3a1_clipin2.wav
sound/cso_edit/mk3a1_clipout1.wav
sound/cso_edit/mk3a1_clipout2.wav
sound/cso_edit/plasmagun-1.wav
sound/cso_edit/plasmagun_clipin1.wav
sound/cso_edit/plasmagun_clipin2.wav
sound/cso_edit/plasmagun_clipout.wav
sound/cso_edit/plasmagun_draw.wav
sound/cso_edit/plasmagun_exp.wav
sound/cso_edit/plasmagun_idle.wav
sound/cso_edit/qbarrel-1.wav
sound/cso_edit/qbarrel_clipin1.wav
sound/cso_edit/qbarrel_clipin2.wav
sound/cso_edit/qbarrel_clipout1.wav
sound/cso_edit/qbarrel_draw.wav
sound/cso_edit/ric_metal-1.wav
sound/cso_edit/ric_metal-2.wav
sound/cso_edit/savery-1.wav
sound/cso_edit/savery_clipin.wav
sound/cso_edit/savery_clipout.wav
sound/cso_edit/savery_draw.wav
sound/cso_edit/savery_idle.wav
sound/cso_edit/skullaxe_wall.wav
sound/cso_edit/turbulent9_hit1.wav
sound/cso_edit/turbulent9_hit2.wav
sound/cso_edit/usas_draw.wav
sound/cso_edit/zoom.wav
sound/kezaeiv/c_wep/misc/item_respawn.wav
sound/kezaeiv/cp/starcraft_terran_rescue.mp3
sound/kezaeiv/singularity/npc/hl2_flesh_hit1.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit2.wav
sound/kezaeiv/singularity/npc/hl2_flesh_hit3.wav
sound/kezaeiv/singularity/npc/quake4_plasma_shot.wav
sound/oghs/cs07/ahhhh.wav
sound/oghs/cs07/ala.wav
sound/oghs/cs07/bell.wav
sound/oghs/cs07/boing.wav
sound/oghs/cs07/cave1.wav
sound/oghs/cs07/csm.wav
sound/oghs/cs07/dies.wav
sound/oghs/cs07/dross.wav
sound/oghs/cs07/fack2.wav
sound/oghs/cs07/fah.wav
sound/oghs/cs07/fart.wav
sound/oghs/cs07/gay.wav
sound/oghs/cs07/nooo.wav
sound/oghs/cs07/oogh.wav
sound/oghs/cs07/pipe.wav
sound/oghs/cs07/pluh.wav
sound/oghs/cs07/pui.wav
sound/oghs/cs07/rip2.wav
sound/oghs/cs07/slip.wav
sound/oghs/cs07/toma.wav
sound/oghs/cs07/vine.wav
sound/oghs/cs1_6_wep/m16_burst.wav
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/tower/mine_charge.wav
sound/tower/parachute.ogg
sprites/cs16/csflashx.spr
sprites/cs16/mzcs1.spr
sprites/cs16/mzcs2.spr
sprites/cso/muzzleflash27.spr
sprites/cso/mzbalrog9.spr
sprites/cso_edit/640hud1.spr
sprites/cso_edit/640hud101.spr
sprites/cso_edit/640hud121.spr
sprites/cso_edit/640hud123.spr
sprites/cso_edit/640hud162.spr
sprites/cso_edit/640hud164.spr
sprites/cso_edit/640hud176.spr
sprites/cso_edit/640hud18.spr
sprites/cso_edit/640hud2.spr
sprites/cso_edit/640hud29.spr
sprites/cso_edit/640hud3.spr
sprites/cso_edit/640hud4.spr
sprites/cso_edit/640hud42.spr
sprites/cso_edit/640hud5.spr
sprites/cso_edit/640hud53.spr
sprites/cso_edit/640hud60.spr
sprites/cso_edit/640hud66.spr
sprites/cso_edit/640hud7.spr
sprites/cso_edit/640hud73.spr
sprites/cso_edit/640hud74.spr
sprites/cso_edit/640hud75.spr
sprites/cso_edit/640hud91.spr
sprites/cso_edit/buffhit.spr
sprites/cso_edit/ef_balrog1.spr
sprites/cso_edit/ef_huntbow_explo.spr
sprites/cso_edit/ef_huntbow_trail.spr
sprites/cso_edit/flame_puff01.spr
sprites/cso_edit/leaf01_dualsword.spr
sprites/cso_edit/leaf02_dualsword.spr
sprites/cso_edit/muzzleflash12.spr
sprites/cso_edit/muzzleflash19.spr
sprites/cso_edit/muzzleflash2.spr
sprites/cso_edit/muzzleflash27.spr
sprites/cso_edit/muzzleflash4.spr
sprites/cso_edit/muzzleflash59.spr
sprites/cso_edit/muzzleflash60.spr
sprites/cso_edit/muzzleflash77.spr
sprites/cso_edit/mzbalrog9.spr
sprites/cso_edit/petal01_dualsword.spr
sprites/cso_edit/petal02_dualsword.spr
sprites/cso_edit/plasmaball.spr
sprites/cso_edit/plasmabomb.spr
sprites/cso_edit/scope_vip_grenade.spr
sprites/cso_edit/smoke_thanatos9.spr
sprites/cso_edit/sniper_savery.spr
sprites/cso_edit/sniper_scope.spr
sprites/cso_edit/wall_puff1.spr
sprites/cso_edit/wall_puff2.spr
sprites/cso_edit/wall_puff3.spr
sprites/cso_edit/wall_puff4.spr
sprites/cso_edit/weapon_at4ex.txt
sprites/cso_edit/weapon_balrog9.txt
sprites/cso_edit/weapon_csom79.txt
sprites/cso_edit/weapon_desperado.txt
sprites/cso_edit/weapon_dualsword.txt
sprites/cso_edit/weapon_ethereal.txt
sprites/cso_edit/weapon_gunkata.txt
sprites/cso_edit/weapon_m3.txt
sprites/cso_edit/weapon_m400.txt
sprites/cso_edit/weapon_m82.txt
sprites/cso_edit/weapon_m95.txt
sprites/cso_edit/weapon_mk3a1.txt
sprites/cso_edit/weapon_plasmagun.txt
sprites/cso_edit/weapon_qbarrel.txt
sprites/cso_edit/weapon_savery.txt
sprites/cso_edit/weapon_volcano.txt
sprites/scmod/item_parachute.spr
sprites/singularity/prtl/kz_exit1.spr
tower.wad
