// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

chronic.wad
dkbigoltexturepak1.wad
dkbigoltexturepak2.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/kezaeiv/icons/mk_logo_orange.mdl
models/kezaeiv/icons/mk_logo_teal.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/barnabus.mdl
models/oghs/cm/npc/crashed_osprey.mdl
models/oghs/cm/npc/gman.mdl
models/oghs/cm/npc/gonome.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn2.mdl
models/oghs/cm/npc/massnf2.mdl
models/oghs/cm/npc/osprey.mdl
models/oghs/cm/npc/osprey2.mdl
models/oghs/cm/npc/ospreyf.mdl
models/oghs/cm/npc/otis.mdl
models/oghs/cm/npc/otisf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/tor2.mdl
models/oghs/cm/npc/zombie_barney.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/urbicide/aa_condiments01_gl_smesh.mdl
models/urbicide/aa_stack_plate02_gl_smesh.mdl
models/urbicide/airconditioner.mdl
models/urbicide/bananna_bunch.mdl
models/urbicide/buzzer_beer.mdl
models/urbicide/car_scrap.mdl
models/urbicide/car_scrapped.mdl
models/urbicide/cc_footwear_07.mdl
models/urbicide/cc_footwear_09.mdl
models/urbicide/cc_footwear_12.mdl
models/urbicide/cc_phone.mdl
models/urbicide/cc_prcloth_01_a.mdl
models/urbicide/cc_prcloth_01_b.mdl
models/urbicide/cc_prcloth_01_c.mdl
models/urbicide/cc_prcloth_02_c.mdl
models/urbicide/coffee_props-sugar.mdl
models/urbicide/computer_mouse01.mdl
models/urbicide/deadbody1.mdl
models/urbicide/deadbody2.mdl
models/urbicide/deadbody3.mdl
models/urbicide/dnc_truck1.mdl
models/urbicide/fem_deadbody2.mdl
models/urbicide/fire_extinguisher.mdl
models/urbicide/hummer.mdl
models/urbicide/jrx_foodwrap1.mdl
models/urbicide/jrx_jeans.mdl
models/urbicide/kosobar.mdl
models/urbicide/me3_paper_pile04.mdl
models/urbicide/mex_veh_ikarus_br_low.mdl
models/urbicide/pot-2.mdl
models/urbicide/rebecca2.mdl
models/urbicide/rug_oriental-large.mdl
models/urbicide/rug_oriental-large3.mdl
models/urbicide/s_frypan.mdl
models/urbicide/s_knife.mdl
models/urbicide/s_melon.mdl
models/urbicide/shampoo_bottle.mdl
models/urbicide/soap.mdl
models/urbicide/trash.mdl
models/urbicide/trash_02.mdl
models/urbicide/trash_trashbag.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
models/urbicide/vts_kitchen_tushenka.mdl
models/urbicide/w_cleaver.mdl
models/urbicide/w_kitchenknife.mdl
models/urbicide/zps_radiator.mdl
poke646.wad
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/urbicide/ambience/arcticwind_gust4.wav
sound/urbicide/ambience/biolab_windoutside_loop.wav
sound/urbicide/ambience/button5.wav
sound/urbicide/ambience/cart1.wav
sound/urbicide/ambience/damage_boom_loop.wav
sound/urbicide/ambience/knocking1.wav
sound/urbicide/ambience/rebecca_scream1.wav
sound/urbicide/ambience/refrigerator_loop.wav
sound/urbicide/ambience/tv_chatter1.wav
sound/urbicide/music/half-life07.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/dbarrel1.wav
sound/urbicide/weapons/hks1.wav
sound/urbicide/weapons/hks2.wav
sound/urbicide/weapons/hks3.wav
sound/urbicide/weapons/pl_gun3.wav
sound/urbicide/weapons/sbarrel1.wav
sprites/singularity/prtl/kz_exit1.spr
stlouis.wad
sunnywoods.wad
urbicide.wad
vendetta.wad
