// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

dkbigoltexturepak1.wad
dkbigoltexturepak2.wad
dt_nyc_firstbatch.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/kezaeiv/icons/mk_logo_orange.mdl
models/kezaeiv/icons/mk_logo_teal.mdl
models/oghs/cm/npc/agrunt.mdl
models/oghs/cm/npc/agruntf.mdl
models/oghs/cm/npc/apache.mdl
models/oghs/cm/npc/apachef.mdl
models/oghs/cm/npc/barnabus.mdl
models/oghs/cm/npc/crashed_osprey.mdl
models/oghs/cm/npc/gman.mdl
models/oghs/cm/npc/gonome.mdl
models/oghs/cm/npc/hassassin.mdl
models/oghs/cm/npc/hassassinf.mdl
models/oghs/cm/npc/hgrunt.mdl
models/oghs/cm/npc/hgrunt_medic.mdl
models/oghs/cm/npc/hgrunt_medicf.mdl
models/oghs/cm/npc/hgrunt_opfor.mdl
models/oghs/cm/npc/hgrunt_opforf.mdl
models/oghs/cm/npc/hgrunt_sniper.mdl
models/oghs/cm/npc/hgrunt_torch.mdl
models/oghs/cm/npc/hgrunt_torchf.mdl
models/oghs/cm/npc/hgruntf.mdl
models/oghs/cm/npc/hwgrunt.mdl
models/oghs/cm/npc/hwgruntf.mdl
models/oghs/cm/npc/islave.mdl
models/oghs/cm/npc/islavef.mdl
models/oghs/cm/npc/massn2.mdl
models/oghs/cm/npc/massnf2.mdl
models/oghs/cm/npc/osprey.mdl
models/oghs/cm/npc/osprey2.mdl
models/oghs/cm/npc/ospreyf.mdl
models/oghs/cm/npc/otis.mdl
models/oghs/cm/npc/otisf.mdl
models/oghs/cm/npc/pit_drone.mdl
models/oghs/cm/npc/rgrunt.mdl
models/oghs/cm/npc/rgruntf.mdl
models/oghs/cm/npc/scientist.mdl
models/oghs/cm/npc/scientist2.mdl
models/oghs/cm/npc/scigun.mdl
models/oghs/cm/npc/tor2.mdl
models/oghs/cm/npc/zombie_barney.mdl
models/oghs/cm/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/urbicide/deadbody4.mdl
models/urbicide/v_357.mdl
models/urbicide/v_9mmAR.mdl
models/urbicide/v_9mmhandgun.mdl
models/urbicide/v_crossbow.mdl
models/urbicide/v_crowbar.mdl
models/urbicide/v_egon.mdl
models/urbicide/v_gauss.mdl
models/urbicide/v_grenade.mdl
models/urbicide/v_hgun.mdl
models/urbicide/v_rpg.mdl
models/urbicide/v_satchel.mdl
models/urbicide/v_satchel_radio.mdl
models/urbicide/v_shotgun.mdl
models/urbicide/v_squeak.mdl
models/urbicide/v_tripmine.mdl
poke646.wad
sound/oghs/misc/cp02_03.mp3
sound/singularity/misc/teleport.wav
sound/urbicide/ambience/bhawk_move.wav
sound/urbicide/ambience/camp_water.wav
sound/urbicide/ambience/computalk2.wav
sound/urbicide/ambience/computalk4.wav
sound/urbicide/ambience/damage_guns_loop.wav
sound/urbicide/ambience/fan4_new.wav
sound/urbicide/ambience/flies.wav
sound/urbicide/ambience/industrial2.wav
sound/urbicide/ambience/industrial4.wav
sound/urbicide/ambience/inlnpipes.wav
sound/urbicide/ambience/lnpipes1.wav
sound/urbicide/ambience/trailer_dripecho_loop.wav
sound/urbicide/ambience/tunnel_amb.wav
sound/urbicide/ambience/water_drips.wav
sound/urbicide/ambience/water_flowing1.wav
sound/urbicide/ambience/water_flowing3.wav
sound/urbicide/ambience/water_lap1.wav
sound/urbicide/ambience/waterrun.wav
sound/urbicide/music/half-life03.mp3
sound/urbicide/weapons/357_reload1.wav
sound/urbicide/weapons/357_shot1.wav
sound/urbicide/weapons/357_shot2.wav
sound/urbicide/weapons/dbarrel1.wav
sound/urbicide/weapons/hks1.wav
sound/urbicide/weapons/hks2.wav
sound/urbicide/weapons/hks3.wav
sound/urbicide/weapons/pl_gun3.wav
sound/urbicide/weapons/sbarrel1.wav
sprites/singularity/prtl/kz_exit1.spr
stlouis.wad
sunnywoods.wad
vendetta.wad
